<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0039)https://shop.10086.cn/mall_771_771.html -->
<html xmlns="http://www.w3.org/1999/xhtml" class="">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/x-icon" href="https://img0.shop.10086.cn/favicon.ico__0.ico">
    <meta name="WT.location" content="771">
    <meta name="keywords" content="中国移动网上商城,网上营业厅,话费查询,充话费,查流量 移动4G手机,移动合约机,移动4G套餐,移动业务办理,积分兑换">
    <meta name="description"
          content="中国移动网上商城为移动客户提供充值交费,账单查询,流量、4G套餐、宽带等业务介绍及办理,提供苹果、三星、小米等多款正品低价手机在线购买,让您足不出户,享受便捷移动服务！">
    <title>中国移动网上商城_广西南宁_话费查询与充值,手机流量查询,4G套餐办理,移动宽带,手机正品低价</title>
    <link href="${IMAGE_SERVER}cloud/static/store/css/index.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script r='m'>document.createElement("section")</script><![endif]-->
    <script type="text/javascript">
        (function () {
            var CmChannelID = document.cookie.match(/CmChannelID=([^;]+)/i)
            var CmChannel = (CmChannelID && CmChannelID[1]) ? CmChannelID[1].toLowerCase() : '';
            var u = navigator.userAgent;
            var browserDetect = {
                mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
                ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios系统
                android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或系统
                wp: u.indexOf('IEMobile') > -1,//Windows Phone系统
                iPhone: u.indexOf('iPhone') > -1, //是否为iPhone或者QQHD浏览器
                Safari: u.indexOf("Safari") > -1,//判断是否Safari浏览器
                iPad: u.indexOf('iPad') > -1, //是否iPad
                webApp: u.indexOf('Safari') > -1 //是否web应该程序，没有头部与底部
            };
            if (CmChannel != 'pc' && CmChannel != 'pad' && browserDetect.mobile && !browserDetect.iPad) {
                var urlmap = {
                    touch: "https://touch.10086.cn/mall_771_771.html",
                    wap: 'http://wap.10086.cn/'
                }
                if (CmChannel == 'wap' && urlmap.wap) {
                    location.href = urlmap.wap;
                } else {
                    location.href = urlmap.touch;
                }
            }

        })();
    </script>
    <script charset="utf-8" src="${IMAGE_SERVER}cloud/static/store/js/recharge.js"></script>
    <meta name="WT.mobile" content="">
</head>

<body style="">

<#include "../common/script_screenResize.ftlh">

<script type="text/html" id="login_box">
    <div class="minloginbox loadingBlock clearfix" style="width:350px;">
        <iframe src="https://login.10086.cn/SSOCheck.action?channelID=12002&backUrl=https%3A%2F%2Fshop.10086.cn%2Fsso%2Fminilogincallback.php%3Faction%3Dforcelogin"
                width="350" height="400" allowTransparency="true" frameborder="0" scrolling="no"></iframe>
    </div>
</script>

<#include "../common/topNav.ftlh">

<iframe src="${IMAGE_SERVER}cloud/static/store/images/saved_resource.html" id="ssocheckframe" style="display:none"></iframe>
<#include "../common/script_allcity.ftlh">

<div class="globalMain clearfix" id="header">

    <div class="search_mlogo clearfix">

        <#include "../common/logoWhere.ftlh">

        <!--[if IE]>
        <style>
            /*#header .search .txt{padding-top:6px;}*/
        </style>
        <![endif]-->
        <div class="search">
            <form class="clearfix" action="https://search.10086.cn/shop/list" autocomplete="off" method="get"
                  target="_blank">

                <input id="skeywords" type="text" name="key" autocomplete="off" disableautocomplete="" class="txt"
                       onfocus=" this.style.color ='#333333'" onblur=" this.style.color ='#ccc'"
                       style="position: relative;z-index: 2;float: left;color:#999">

                <ul id="searchKeyWord1598324029636" class="search_toplist" style="display: none;"></ul>
                <ul id="searchHistory1598324029636" class="search_toplist" style="display: none;"></ul>
                <input type="submit" class="b" value="搜索"
                       style="background-color:#25b2fe;color:#fff;border:0;border-radius:3px">
                <input type="hidden" class="txt" name="province_id" value="771">
                <input type="hidden" class="txt" name="city_id" value="771">
                <input type="hidden" class="txt" name="from" value="10603">
                <script type="text/javascript">window.searchDomain = "https://search.10086.cn/";</script>
            </form>
            <ul id="hotsearch" class="floatleft search_hotlist clearfix">
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_1_5G正式商用" type="" class="search_red ac_dcs_base" href="">5G正式商用</a>
                </li>
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_2_信用购机" type="" class="search_red ac_dcs_base" href="">信用购机</a>
                </li>
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_3_积分兑换" type="" class="search_red ac_dcs_base" href="">积分兑换</a>
                </li>
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_4_流量卡" type="" class="search_blue ac_dcs_base" href="">流量卡</a>
                </li>
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_5_飞享套餐" type="" class="search_blue ac_dcs_base" href="">飞享套餐</a>
                </li>
                <li>
                    <a target="_blank" dcs_id="MALL_RCSS_6_服务密码" type="" class="search_red ac_dcs_base" href="">服务密码</a>
                </li>
            </ul>

        </div>
    </div>

    <#include "../common/navigation.ftlh">

</div>


<div class="header_area_template" style="display:none;">
    <!-- <li style="height:24px;overflow:hidden;"><a href="javascript:void(0)" class="ac_city_choose" location="{province_id}_{city_id}" title="{city_name}">{city_name}</a></li> --> </div>

<style type="text/css">
    .leftbtmbox .ztitle {
        width: 170px;
        height: 25px;
        overflow: hidden;
        padding-left: 40px;
        text-decoration: none;
    }

    .leftbtmbox .fontcolor {
        color: #ED2668;
    }

    .leftbtmbox .gname {
        width: 110px;
        height: 15px;
        overflow: hidden;
    }
</style>
<div class="content clearfix">
    <div class="goodsNavBanner clearfix">
        <div class="Bigleftbox">
            <div class="leftBox idx_goodsnav">

                <style type="text/css">
                    .sname a.jine {
                        padding: 0 3px 0 0 !important;
                    }
                </style>
                <ul class="goodsNav clearfix withhover">

                    <#--<li class="">
                        <div class="sname iconNavPhone"><i class="bg"></i><i class="bdr"></i>
                            <a target="_blank" dcs_id="101" href="https://shop.10086.cn/list/101_771_771_0_0_0_0.html"
                               class="title  ac_dcstracker_homefirstscreen">买手机</a><br>
                            <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_1_0.html" target="_blank"
                               class="ac_dcs_base" dcs_id="nav_phone_0">信用购机</a>
                            <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_2_0.html" target="_blank"
                               class="ac_dcs_base" dcs_id="nav_phone_1">裸机</a>
                        </div>
                        <div class="smore">
                            <dl class="noBorderTop logo">
                                <dt>热门品牌</dt>
                                <dd class="">
                                    <a dcs_id="nav_phone_more_1_1" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_1_0_0_0_0.html"
                                       title="小米"><img src="${IMAGE_SERVER}cloud/static/store/images/tq7x33jnsg2ffv3eg.png"></a>
                                    <a dcs_id="nav_phone_more_1_2" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_2_0_0_0_0.html"
                                       title="苹果"><img src="${IMAGE_SERVER}cloud/static/store/images/t2usc33yjc7edrdm.png"></a>
                                    <a dcs_id="nav_phone_more_1_3" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_3_0_0_0_0.html"
                                       title="华为"><img src="${IMAGE_SERVER}cloud/static/store/images/tqhm5ge946f7r7pz.png"></a>
                                    <a dcs_id="nav_phone_more_1_4" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_4_0_0_0_0.html"
                                       title="OPPO"><img src="${IMAGE_SERVER}cloud/static/store/images/tme5qqjzptwkh4sk.png"></a>
                                    <a dcs_id="nav_phone_more_1_5" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_5_0_0_0_0.html"
                                       title="魅族"><img src="${IMAGE_SERVER}cloud/static/store/images/t2hqczrrcrgffv3tuh.png"></a>
                                    <a dcs_id="nav_phone_more_1_6" class="ac_dcs_base" target="_blank"
                                       href="https://shop.10086.cn/list/101_771_771_1_0_0_6_0_0_0_0.html"
                                       title="VIVO"><img src="${IMAGE_SERVER}cloud/static/store/images/tapf8evw962ttrexs.png"></a>
                                </dd>
                            </dl>
                            <dl class="noBorderTop">
                                <dt>价格区间</dt>
                                <dd class="">
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_1_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_1">0-299</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_2_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_2">300-699</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_3_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_3">700-999</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_4_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_4">1000-1999</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_5_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_5">2000-2999</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_6_0_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_2_6">3000以上</a>
                                </dd>
                            </dl>
                            <dl class="noBorderTop">
                                <dt>屏幕尺寸</dt>
                                <dd class="">
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_1_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_3_1">3.0英寸以下</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_2_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_3_2">3.0-4.0英寸</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_3_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_3_3">4.1-4.9英寸</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_4_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_3_4">5.0-5.6英寸</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_5_0_0.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_3_5">5.6英寸以上</a>
                                </dd>
                            </dl>
                            <dl class="noBorderTop">
                                <dt>特色标签</dt>
                                <dd class="">
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_1.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_1">旗舰机皇</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_2.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_2">热销爆款</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_3.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_3">超高性价比</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_4.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_4">清仓甩卖</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_5.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_5">拍照神器</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_6.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_6">超薄手机</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_7.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_7">双卡双待</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_8.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_8">超长待机</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_9.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_9">商务精英</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_10.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_10">时尚丽人</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_11.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_11">学生机</a>
                                    <a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_12.html"
                                       class="ac_dcs_base" dcs_id="nav_phone_more_4_12">老人机</a>
                                </dd>
                            </dl>
                        </div>
                    </li>-->

                    <#list cats as cat>
                        <#if cat?index < 6>
                        <li class="">
                            <div class="sname iconNavHuafei"><i class="bg"></i><i class="bdr"></i>
                                <a target="_blank" dcs_id="jiaohuafei"
                                   href="https://shop.10086.cn/i/service/recharge/item/itemcollect_771_771_.html"
                                   class="title  ac_dcstracker_homefirstscreen">${cat.catName}</a><br>
                                <a href="https://shop.10086.cn/i/service/recharge/item/itemcollect_771_771_.html"
                                   class="ac_dcs_base" dcs_id="nav_recharge_0" target="_blank">${cat.catName}</a>
                            </div>
                            <div class="smore">
                                <#list cat.children as cat2>
                                <dl class="noBorderTop">
                                    <dt>${cat2.catName}</dt>
                                    <dd class="clearfix">
                                        <#list cat2.children as cat3>
                                        <a dcs_id="nav_recharge_more_1_1" class="ac_dcs_base"
                                           <#--href="https://shop.10086.cn/i/service/recharge/item/itemcollect_771_771_30.html"-->
                                           href="./list?catId=${cat3.catId}"
                                           target="_blank">${cat3.catName}</a>
                                        </#list>
                                    </dd>
                                </dl>
                                </#list>
                            </div>
                        </li>
                        </#if>
                    <#else>
                    None
                    </#list>

                    <li id="personalCenter" class="">
                        <div class="sname iconNavUser"><i class="bg"></i><i class="bdr"></i>
                            <a target="_blank" dcs_id="home_firstscreen_grzx" href="https://shop.10086.cn/i/?f=home"
                               class="title ac_dcstracker_homefirstscreen">个人中心</a><br>
                            <a href="https://shop.10086.cn/i/?f=myorders" target="_blank" class="ac_dcs_base"
                               dcs_id="nav_personal_0">商品订单</a>
                            <a href="https://shop.10086.cn/i/?f=billqry" target="_blank" class="ac_dcs_base"
                               dcs_id="nav_personal_1">账单查询</a>
                        </div>
                        <div class="smore">

                            <dl class="noBorderTop">

                                <dt>我的账户</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=mycoupons" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_1_1">我的卡券</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=billqry" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_1_2">账单查询</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=billdetailqry"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_1_3">详单查询</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=packremainqry"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_1_4">套餐余量查询</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=recharhisqry"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_1_5">交费记录查询</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=pointqry" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_1_6">积分明细查询</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=busiqrydeal" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_1_7">业务查询退订</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=belongqry" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_1_8">归属地查询</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>我的信息</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=custinfoqry" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_2_1">个人信息</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=recaddrmag" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_2_2">收货地址</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=invoicemag" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_2_3">发票信息</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=passwordmg" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_2_4">安全设置</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=myinvoice" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_2_5">我的发票</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>我的订单</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=myorders" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_3_1">商品订单</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=mypreorders" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_3_2">预购订单</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=rechargerecord"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_3_3">充值订单</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=myfav" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_3_4">我的收藏</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>我的消息</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=advicearrival"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_4_1">消息订阅</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=mynews" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_4_2">消息查看</a>

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=msgremind" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_4_3">消息提醒设置</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>售后服务</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=returnorderqry"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_5_1">退货申请/查询</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>我的邮箱</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="https://shop.10086.cn/i/?f=remail" class="ac_dcs_base"
                                       dcs_id="nav_personal_more_6_1">139邮箱</a>

                                </dd>
                            </dl>

                            <dl class="noBorderTop">

                                <dt>省份专区</dt>
                                <dd class="clearfix">

                                    <a target="_blank" href="http://service.gx.10086.cn/operate/dzfpdz.jsp"
                                       class="ac_dcs_base" dcs_id="nav_personal_more_7_1">电子发票</a>

                                </dd>
                            </dl>

                        </div>
                    </li>
                </ul>


            </div>
            <div class="mainBox">
                <div id="focus" class="banner">
                    <ul class="clearfix">
                        <li cmkey="index_ads_main_0" style="display: block;"><a class="ac_dcstracker_homefirstscreen"
                                                                                dcs_id="home_firstscreen_ad_0"
                                                                                href="https://shop.10086.cn/goods/771_771_1058999_1044959.html?WT.ac=home_firstscreen_ad_0_771"
                                                                                target="_blank" title="月末流量包"><img
                                        src="${IMAGE_SERVER}cloud/static/store/images/t72kcuewryjttqa9p.png" alt="月末流量包">

                            </a></li>
                        <li cmkey="index_ads_main_1" style="display: none;"><a class="ac_dcstracker_homefirstscreen"
                                                                               dcs_id="home_firstscreen_ad_1"
                                                                               href="http://shop.10086.cn/i/?f=rechargegprs&amount=100&WT.ac=home_firstscreen_ad_1_771"
                                                                               target="_blank" title=""><img
                                        src="${IMAGE_SERVER}cloud/static/store/images/thdmfw5tf3bsttghsn.png" alt="">

                            </a></li>
                        <li cmkey="index_ads_main_2" style="display: none;"><a class="ac_dcstracker_homefirstscreen"
                                                                               dcs_id="home_firstscreen_ad_2"
                                                                               href="https://shop.10086.cn/goods/771_771_1079216_1061262.html?WT.ac=home_firstscreen_ad_2_771"
                                                                               target="_blank" title="新畅享套餐系列"><img
                                        src="${IMAGE_SERVER}cloud/static/store/images/thbyf8mte8dtt93g5.png" alt="新畅享套餐系列">

                            </a></li>
                    </ul>
                    <p class="btns"><span class="current">1</span><span class="">2</span><span class="">3</span></p>
                </div>


            </div>
            <div class="leftbtmbox">

                <div class="slide clearfix" id="bannerSlide">
                    <ul class="clearfix piclist mainlist" style="width: 1225px; left: 0px;">


                        <li><a class="ac_dcstracker_homefirstscreen" dcs_id="home_firstscreen_ad_banner_slide_4"
                               href="http://shop.10086.cn/i/?f=rechargegprs&amount=100&WT.ac=home_firstscreen_ad_banner_slide_4_771"
                               target="_blank" title=""><img src="${IMAGE_SERVER}cloud/static/store/images/thdmfzer86bttnfba.png" alt="">

                            </a></li>
                        <li><a class="ac_dcstracker_homefirstscreen" dcs_id="home_firstscreen_ad_banner_slide_0"
                               href="https://shop.10086.cn/goods/771_771_1058999_1044959.html?WT.ac=home_firstscreen_ad_banner_slide_0_771"
                               target="_blank" title="月末流量包"><img src="${IMAGE_SERVER}cloud/static/store/images/t72k4jkwvmcttqhaf.png" alt="月末流量包">

                            </a></li>
                        <li><a class="ac_dcstracker_homefirstscreen" dcs_id="home_firstscreen_ad_banner_slide_1"
                               href="https://shop.10086.cn/goods/771_771_1080870_1063691.html?WT.ac=home_firstscreen_ad_banner_slide_1_771"
                               target="_blank" title=""><img src="${IMAGE_SERVER}cloud/static/store/images/t6e76esttsgq7hfvc.png" alt="">

                            </a></li>
                        <li><a class="ac_dcstracker_homefirstscreen" dcs_id="home_firstscreen_ad_banner_slide_2"
                               href="http://shop.10086.cn/goods/771_771_1008657_1006023.html?WT.ac=home_firstscreen_ad_banner_slide_2_771"
                               target="_blank" title=""><img src="${IMAGE_SERVER}cloud/static/store/images/twqv9cj787rza38a.png" alt="">

                            </a></li>
                        <li><a class="ac_dcstracker_homefirstscreen" dcs_id="home_firstscreen_ad_banner_slide_3"
                               href="https://shop.10086.cn/goods/771_771_1079216_1061262.html?WT.ac=home_firstscreen_ad_banner_slide_3_771"
                               target="_blank" title="新畅享套餐系列"><img src="${IMAGE_SERVER}cloud/static/store/images/thgbdxbnct9ttmh66.png" alt="新畅享套餐系列">

                            </a></li>
                    </ul>
                    <span class="turn_left" style="display: inline; left: -28px;"></span>
                    <span class="turn_right" style="display: inline; right: -28px;"></span>
                </div>


            </div>
        </div>

        <div class="rightBox">
            <div class="quickbtn">
                <ul>
                    <li><a href="https://shop.10086.cn/i/?f=myorders" target="_blank" class="ac_dcs_base"
                           dcs_id="quickbtn_0"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfw32cnvmtpmact.png" width="60" height="60"><br>商品订单</a>
                    </li>

                    <li><a href="https://shop.10086.cn/list/140_771_771_0_0_0_0.html" target="_blank"
                           class="ac_dcs_base" dcs_id="quickbtn_1"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfwgdawkebze3zw.png" width="60"
                                                                        height="60"><br>套餐订购</a></li>

                    <li><a href="https://shop.10086.cn/list/146_771_771_0_0_0_0.html" target="_blank"
                           class="ac_dcs_base" dcs_id="quickbtn_2"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfw2fpaf5tpma4d.png" width="60"
                                                                        height="60"><br>业务办理</a></li>

                    <li><a href="https://shop.10086.cn/i/?f=billqry" target="_blank" class="ac_dcs_base"
                           dcs_id="quickbtn_3"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfwwkd639bze3qf.png" width="60" height="60"><br>账单查询</a>
                    </li>

                    <li><a href="https://shop.10086.cn/i/?f=billdetailqry" target="_blank" class="ac_dcs_base"
                           dcs_id="quickbtn_4"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfw6z3ayakh4tur.png" width="60" height="60"><br>详单查询</a>
                    </li>

                    <li><a href="https://shop.10086.cn/i/?f=packremainqry" target="_blank" class="ac_dcs_base"
                           dcs_id="quickbtn_5"><img src="${IMAGE_SERVER}cloud/static/store/images/twgfwaz5z7bbzeynt.png" width="60" height="60"><br>套餐余量</a>
                    </li>


                </ul>
            </div>
            <div class="recharge chongzhi">
                <div class="form clearfix charge_area">
                    <p class="title clearfix"><span class="name fontYaHei tt_hfcz cur">话费充值</span><span
                                class="name fontYaHei tt_llcz">流量充值</span></p>
                    <div class="con_hfcz cz" flag="1" style="display: block;">
                        <dl class="clearfix">
                            <dt>手机号：</dt>
                            <dd class="number">
                                <input type="text" class="txt i-prompt i-prompt-gray" name="phonenum" iprompt="请输入手机号码"
                                       style="color: rgb(204, 204, 204);">
                            </dd>
                        </dl>
                        <dl class="clearfix">
                            <dt>金　额：</dt>
                            <dd class="yuan">
                                <span class="yuan_show toggle">100 元</span>
                                <input type="hidden" name="amount" value="100">
                                <a href="javascript:void(0);" class="toggle"></a>
                                <div class="select_yuan">
                                    <a dcs_id="home_firstscreen_50"
                                       class="ac_index_chongzhi ac_dcstracker_homefirstscreen"
                                       href="javascript:void(0);">50 元</a>
                                    <a dcs_id="home_firstscreen_300"
                                       class="ac_index_chongzhi ac_dcstracker_homefirstscreen rightborder"
                                       href="javascript:void(0);">300 元</a>
                                    <a dcs_id="home_firstscreen_100"
                                       class="ac_index_chongzhi ac_dcstracker_homefirstscreen"
                                       href="javascript:void(0);">100 元</a>
                                    <a dcs_id="home_firstscreen_500"
                                       class="ac_index_chongzhi ac_dcstracker_homefirstscreen rightborder"
                                       href="javascript:void(0);">500 元</a>
                                    <div class="clear"></div>
                                </div>
                            </dd>
                        </dl>
                        <div class="num_tips"></div>
                        <dl class="clearfix btdd">
                            <dd class="">
                                <a dcs_id="home_firstscreen_hfcz"
                                   class="btn btnBlue nohand rechargeSubmit ac_dcstracker_homefirstscreen"
                                   url="https://shop.10086.cn/i/?f=rechargecredit" target="_blank"><i></i><b></b><em>立即充值</em></a>
                                <div class="czbt_area"><span class="zhekou"></span><br><a target="_blank"
                                                                                          href="https://shop.10086.cn/i/?f=rechargecredit"
                                                                                          class="floatright red marginRight15 ac_dcs_base"
                                                                                          dcs_id="Home_FirstScreen_HF_YOUHUI"
                                                                                          title="更多优惠">更多优惠<em
                                                class="fontSun">&gt;&gt;</em></a></div>
                            </dd>
                        </dl>
                    </div>
                    <div class="con_llcz cz" flag="2" style="display: none;">
                        <dl class="clearfix">
                            <dt>手机号：</dt>
                            <dd class="number">
                                <input type="text" class="txt i-prompt i-prompt-gray" name="phonenum" iprompt="请输入手机号码"
                                       style="color: rgb(204, 204, 204);">
                            </dd>
                        </dl>
                        <dl class="clearfix">
                            <dt>档　位：</dt>
                            <dd class="yuan">
                                <span class="yuan_show yuan_show1 toggle" traffic="100">100MB (10元）</span>
                                <input type="hidden" name="amount" value="100">
                                <a href="javascript:void(0);" class="toggle"></a>
                                <div class="select_yuan select_yuan1">
                                    <div class="m1">
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="10" traffic="100" discount="0"
                                           href="javascript:void(0);">100MB (10元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="20" traffic="300" discount="0"
                                           href="javascript:void(0);">300MB (20元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="30" traffic="1024"
                                           discount="0" href="javascript:void(0);">1G (30元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="50" traffic="2048"
                                           discount="0" href="javascript:void(0);">2G (50元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="70" traffic="3072"
                                           discount="0" href="javascript:void(0);">3G (70元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="100" traffic="5120"
                                           discount="0" href="javascript:void(0);">5G (100元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="150" traffic="10240"
                                           discount="0" href="javascript:void(0);">10G (150元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="200" traffic="15360"
                                           discount="0" href="javascript:void(0);">15G (200元)</a>
                                        <a class="ac_index_chongzhi dc_chongzhi" pay_num="300" traffic="30720"
                                           discount="0" href="javascript:void(0);">30G (300元)</a>
                                    </div>
                                    <div class="m2">
                                        <!-- <a class="ac_index_chongzhi" pay_num="{pay_num}" traffic="{traffic}" discount="{discount}" href="javascript:void(0);">{name}</a> -->
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </dd>
                        </dl>
                        <dl class="clearfix">
                            <dt style="width:200px;text-align:left;text-indent:11px;">支付金额：<label class="price"><span
                                            class="price_num">10</span>元</label></dt>
                        </dl>
                        <dl class="clearfix btdd">
                            <dd class="">
                                <a dcs_id="home_firstscreen_llcz"
                                   class="btn btnBlue nohand rechargeSubmit ac_dcstracker_homefirstscreen"
                                   url="https://shop.10086.cn/i/?f=rechargegprs"
                                   target="_blank"><i></i><b></b><em>立即充值</em></a>
                                <div class="czbt_area">
                                    <span class="discount_zhe"><span class="zhekou discoutsize"></span><span
                                                class="zhekou">折</span></span><br>
                                    <a traffic="30" target="_blank" href="https://shop.10086.cn/i/?f=rechargegprs"
                                       class="floatright red marginRight15 ac_dcs_base"
                                       dcs_id="Home_FirstScreen_LL_YOUHUI" title="更多优惠">更多优惠<em
                                                class="fontSun">&gt;&gt;</em></a>
                                </div>
                            </dd>
                        </dl>
                        <div class="num_tips"></div>
                    </div>
                </div>
            </div>


            <div class=" favMsg recharge">
                <p class="title clearfix"><span class="name fontYaHei tt_sckb cur"><a
                                href="https://shop.10086.cn/notice/list.php?province_id=771&city_id=771"
                                target="_blank">商城快报</a></span><span class="name fontYaHei  tt_scgg"><a
                                href="https://shop.10086.cn/notice/list.php?province_id=771&city_id=771"
                                target="_blank">商城公告</a></span></p>
                <ul class="hoverBlue con_sckb" style="display:block">
                    <li><a href="http://shop.10086.cn/i/?f=rechargecredit&amount=100" target="_blank"
                           class="ac_dcs_base" dcs_id="kb_0">

                            话费充值
                        </a></li>
                    <li><a href="https://shop.10086.cn/goods/771_771_1072626_1052012.html" target="_blank"
                           class="ac_dcs_base" dcs_id="kb_1">
                            流量月包优惠上线，可共... <span class="red bold">NEW</span>
                        </a></li>
                    <li><a href="http://shop.10086.cn/list/101_771_771_0_0_0_0.html" target="_blank" class="ac_dcs_base"
                           dcs_id="kb_2">

                            新机上线
                        </a></li>
                </ul>
                <ul class="hoverBlue con_scgg" style="display:none">
                    <li><a class="ac_dcs_base" dcs_id="gg_0"
                           href="https://shop.10086.cn/notice/detail.php?province_id=771&city_id=771&cm_id=341854&type=1"
                           target="_blank">

                            关于推行增值税电子普通发票...
                        </a></li>
                    <li><a class="ac_dcs_base" dcs_id="gg_1"
                           href="https://shop.10086.cn/notice/detail.php?province_id=771&city_id=771&cm_id=240188&type=1"
                           target="_blank">
                            2017年春节移动商城... <span class="red bold">NEW</span>
                        </a></li>
                </ul>
            </div>

        </div>
    </div>

    <div class="barTitle clearfix">
        <em class="icon"></em>
        <a dcs_id="PHONE" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/101_771_771_0_0_0_0.html"><span class="name">1F<em class="fontTahoma">/</em>买手机</span></a>
        <p class="menu clearfix">

            <a dcs_id="PHONE_MENU_0" class="ac_dcstracker_phone" target="_blank"
               href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_0.html">全部</a><i>|</i> <a
                    dcs_id="PHONE_MENU_1" class="ac_dcstracker_phone" target="_blank"
                    href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_2.html">热销爆款</a><i>|</i> <a
                    dcs_id="PHONE_MENU_2" class="ac_dcstracker_phone" target="_blank"
                    href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_3.html">超高性价比</a><i>|</i> <a
                    dcs_id="PHONE_MENU_3" class="ac_dcstracker_phone" target="_blank"
                    href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_7.html">双卡双待</a><i>|</i> <a
                    dcs_id="PHONE_MENU_4" class="ac_dcstracker_phone" target="_blank"
                    href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_1_0.html">信用购机</a></p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="PHONE_AD_0" class="ac_dcstracker_PHONE_AD"
                   href="https://shop.10086.cn/hd/2019iphone01/index.html?WT.ac_id=1909_PGXP_PC_O_MHJLD" target="_blank"
                   title=""><img src="${IMAGE_SERVER}cloud/static/store/images/tasgurcsnyftt2wmd.png"
                                 data-original="//img1.shop.10086.cn/file/tasgurcsnyftt2wmd.png" class="lazy big" alt=""
                                 style="display: block;"></a></li>
        </ul>

        <div class="modGoods">
            <ul class="clearfix phoneList withhover floatleft">
                <li>
                    <div class="body">
                        <p class="position pic">


                            <a dcs_id="PHONE_GOODS_PICURL_0" class="ac_dcstracker_phone" target="_blank"
                               href="https://shop.10086.cn/goods/100_100_1012520_1063364.html" title="iPhone 11"><img
                                        class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/taxxmj2dshsttrhp5.png"
                                        data-original="//img1.shop.10086.cn/file/taxxmj2dshsttrhp5.png" alt="iPhone 11"
                                        style="display: inline;"></a></p>
                        <p class="price red size20"><em class="fontYaHei size14">￥</em>4599.00</p>
                        <p class="name" title="iPhone 11"><a dcs_id="PHONE_GOODS_TITLEURL_0" class="ac_dcstracker_phone"
                                                             target="_blank"
                                                             href="https://shop.10086.cn/goods/100_100_1012520_1063364.html">iPhone
                                11<span class="red"></span></a></p>

                    </div>
                </li>
                <li>
                    <div class="body">
                        <p class="position pic">


                            <a dcs_id="PHONE_GOODS_PICURL_1" class="ac_dcstracker_phone" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1074873_1055345.html" title="华为P30 Pro"><img
                                        class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/tacw36nhcwwttmevg.png"
                                        data-original="//img1.shop.10086.cn/file/tacw36nhcwwttmevg.png" alt="华为P30 Pro"
                                        style="display: inline;"></a></p>
                        <p class="price red size20"><em class="fontYaHei size14">￥</em>3499.00</p>
                        <p class="name" title="华为P30 Pro"><a dcs_id="PHONE_GOODS_TITLEURL_1" class="ac_dcstracker_phone"
                                                             target="_blank"
                                                             href="https://shop.10086.cn/goods/771_771_1074873_1055345.html">华为P30
                                Pro<span class="red"></span></a></p>

                    </div>
                </li>
                <li>
                    <div class="body">
                        <p class="position pic">


                            <a dcs_id="PHONE_GOODS_PICURL_2" class="ac_dcstracker_phone" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1074461_1066936.html" title="iPhone8 Plus"><img
                                        class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/tha95k25ggcdzne3.png"
                                        data-original="//img1.shop.10086.cn/file/tha95k25ggcdzne3.png"
                                        alt="iPhone8 Plus" style="display: inline;"></a></p>
                        <p class="price red size20"><em class="fontYaHei size14">￥</em>3499.00</p>
                        <p class="name" title="iPhone8 Plus"><a dcs_id="PHONE_GOODS_TITLEURL_2"
                                                                class="ac_dcstracker_phone" target="_blank"
                                                                href="https://shop.10086.cn/goods/771_771_1074461_1066936.html">iPhone8
                                Plus<span class="red"></span></a></p>

                    </div>
                </li>
                <li class="">
                    <div class="body">
                        <p class="position pic">


                            <a dcs_id="PHONE_GOODS_PICURL_3" class="ac_dcstracker_phone" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1074475_1054645.html" title="魅族16s"><img
                                        class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th5s5mu8hnztt8dbe.png"
                                        data-original="//img1.shop.10086.cn/file/th5s5mu8hnztt8dbe.png" alt="魅族16s"
                                        style="display: inline;"></a></p>
                        <p class="price red size20"><em class="fontYaHei size14">￥</em>3198.00</p>
                        <p class="name" title="魅族16s"><a dcs_id="PHONE_GOODS_TITLEURL_3" class="ac_dcstracker_phone"
                                                         target="_blank"
                                                         href="https://shop.10086.cn/goods/771_771_1074475_1054645.html">魅族16s<span
                                        class="red"></span></a></p>

                    </div>
                </li>

            </ul>

            <div class="brands clearfix floatright w1khide">
                <ul>
                    <li>
                        <a dcs_id="PHONE_BRAND_0" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_1_0_0_0_0.html" title="小米"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tq7x33jnsg2ffv3eg.png" alt="小米"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_1" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_7_0_0_0_0.html" title="三星"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqhm59rjwfyedrsw.png" alt="三星"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_2" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_17_0_0_0_0.html" title="联想"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqhm5yatthhwf7rhej.png" alt="联想"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_3" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_3_0_0_0_0.html" title="华为"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqhm5ge946f7r7pz.png" alt="华为"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_4" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_15_0_0_0_0.html" title="酷派"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/t6tbk4eby3mbzej5c.png" alt="酷派"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_5" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_9_0_0_0_0.html" title="天语"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqhm56d4q8gf7rwhj.png" alt="天语"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_6" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_10_0_0_0_0.html" title="中兴"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqhm3v5xg4bfnvvvk.png" alt="中兴"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_7" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_45_0_0_0_0.html" title="HTC"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/tqz7vdungbzf7rw9z.png" alt="HTC"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_8" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_2_0_0_0_0.html" title="苹果"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/t2usc33yjc7edrdm.png" alt="苹果"></a>
                    </li>
                    <li>
                        <a dcs_id="PHONE_BRAND_9" class="ac_dcstracker_phone" target="_blank"
                           href="https://shop.10086.cn/list/101_771_771_1_0_0_5_0_0_0_0.html" title="魅族"><img
                                    src="${IMAGE_SERVER}cloud/static/store/images/t2hqczrrcrgffv3tuh.png" alt="魅族"></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="clearfix ad marginTop10">
        <a href="https://shop.10086.cn/goods/200_200_1006551_1064422.html" class="ac_dcs_base"
           dcs_id="ad_phone_https://shop.10086.cn/goods/200_200_1006551_1064422.html" target="_blank"><img
                    src="${IMAGE_SERVER}cloud/static/store/images/th72qskjvg8tt4vwb.png"></a>
    </div>


    <div class="barTitle clearfix">
        <em class="icon taocan"></em>
        <a dcs_id="EXPENSE" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/140_771_771_0_0_0_0.html"><span class="name">2F<em class="fontTahoma">/</em>办套餐</span></a>
        <p class="menu">
            <a dcs_id="EXPENSE_MENU_0" class="ac_dcstracker_expensemenu" target="_blank"
               href="https://shop.10086.cn/list/140_771_771_1_0_0_0_0.html">全部</a><i>|</i> <a dcs_id="EXPENSE_MENU_1"
                                                                                              class="ac_dcstracker_expensemenu"
                                                                                              target="_blank"
                                                                                              href="https://shop.10086.cn/list/140_771_771_1_0_0_0_1.html">资费套餐</a>
        </p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="EXPENSE_AD_0" class="ac_dcstracker_EXPENSE_AD"
                   href="http://shop.10086.cn/list/140_771_771_0_0_0_0.html" target="_blank" title=""><img
                            src="${IMAGE_SERVER}cloud/static/store/images/t29h27qtu3uuf7r6n7.png"
                            data-original="//img1.shop.10086.cn/file/t29h27qtu3uuf7r6n7.png" class="lazy " alt=""
                            style="display: block;"></a></li>
        </ul>

        <div class="modGoods">
            <ul class="taocanList clearfix">

                <li class="taocan_list0 ft" cmkey="taocan_list_0">
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="EXPENSE_GOODS_PICURL_0" class="ac_dcstracker_expenseexpense"
                               href="https://shop.10086.cn/goods/771_771_1081790_1065693.html" target="_blank"
                               title="新5G智享套餐（个人版）"><img class="lazy jz_img" src="${IMAGE_SERVER}cloud/static/store/images/th6dmzytuu7zwxeq_100x100.png"
                                                         data-original="//img1.shop.10086.cn/goods/th6dmzytuu7zwxeq_100x100.png"
                                                         alt="新5G智享套餐（个人版）" style="display: block;"></a>
                        </dt>
                        <dd class="name hoverBlue"><a dcs_id="EXPENSE_GOODS_TITLE_0"
                                                      class="ac_dcstracker_expenseexpense title_sy"
                                                      href="https://shop.10086.cn/goods/771_771_1081790_1065693.html"
                                                      target="_blank" title="新5G智享套餐（个人版）">新5G智享套餐（个人版）</a></dd>
                        <dd class="alt_tit" title=""><span class="alt_sy"></span>　<a dcs_id="EXPENSE_GOODS_SHOWMORE_0"
                                                                                     class="ac_dcstracker_expenseexpense"
                                                                                     target="_blank"
                                                                                     href="https://shop.10086.cn/goods/771_771_1081790_1065693.html">查看详情<em
                                        class="fontSun">&gt;&gt;</em></a></dd>
                        <dd><span class="red size16"><em class="fontTahoma">128</em> <em
                                        class="size12 jz_fy">元起</em></span></dd>
                    </dl>
                </li>

                <li class="taocan_list1 ft" cmkey="taocan_list_1">
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="EXPENSE_GOODS_PICURL_1" class="ac_dcstracker_expenseexpense"
                               href="https://shop.10086.cn/goods/771_771_1079216_1061262.html" target="_blank"
                               title="新畅享套餐系列"><img class="lazy jz_img" src="${IMAGE_SERVER}cloud/static/store/images/thfhert6agutt9cgt_100x100.png"
                                                    data-original="//img1.shop.10086.cn/goods/thfhert6agutt9cgt_100x100.png"
                                                    alt="新畅享套餐系列" style="display: block;"></a>
                        </dt>
                        <dd class="name hoverBlue"><a dcs_id="EXPENSE_GOODS_TITLE_1"
                                                      class="ac_dcstracker_expenseexpense title_sy"
                                                      href="https://shop.10086.cn/goods/771_771_1079216_1061262.html"
                                                      target="_blank" title="新畅享套餐系列">新畅享套餐系列</a></dd>
                        <dd class="alt_tit" title=""><span class="alt_sy"></span>　<a dcs_id="EXPENSE_GOODS_SHOWMORE_1"
                                                                                     class="ac_dcstracker_expenseexpense"
                                                                                     target="_blank"
                                                                                     href="https://shop.10086.cn/goods/771_771_1079216_1061262.html">查看详情<em
                                        class="fontSun">&gt;&gt;</em></a></dd>
                        <dd><span class="red size16"><em class="fontTahoma">48</em> <em
                                        class="size12 jz_fy">元/月起</em></span></dd>
                    </dl>
                </li>

                <li class="taocan_list2 " cmkey="taocan_list_2">
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="EXPENSE_GOODS_PICURL_2" class="ac_dcstracker_expenseexpense"
                               href="https://shop.10086.cn/goods/771_771_1045774_1044344.html" target="_blank"
                               title="飞享套餐"><img class="lazy jz_img" src="${IMAGE_SERVER}cloud/static/store/images/thn4rqvpcqcttw395_100x100.png"
                                                 data-original="//img1.shop.10086.cn/goods/thn4rqvpcqcttw395_100x100.png"
                                                 alt="飞享套餐" style="display: block;"></a>
                        </dt>
                        <dd class="name hoverBlue"><a dcs_id="EXPENSE_GOODS_TITLE_2"
                                                      class="ac_dcstracker_expenseexpense title_sy"
                                                      href="https://shop.10086.cn/goods/771_771_1045774_1044344.html"
                                                      target="_blank" title="飞享套餐">飞享套餐</a></dd>
                        <dd class="alt_tit" title=""><span class="alt_sy"></span>　<a dcs_id="EXPENSE_GOODS_SHOWMORE_2"
                                                                                     class="ac_dcstracker_expenseexpense"
                                                                                     target="_blank"
                                                                                     href="https://shop.10086.cn/goods/771_771_1045774_1044344.html">查看详情<em
                                        class="fontSun">&gt;&gt;</em></a></dd>
                        <dd><span class="red size16"><em class="fontTahoma">38</em> <em
                                        class="size12 jz_fy">元起</em></span></dd>
                    </dl>
                </li>
            </ul>

        </div>
    </div>


    <div class="barTitle clearfix">
        <em class="icon yewu"></em>
        <a dcs_id="VAS" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/146_771_771_0_0_0_0.html"><span class="name">3F<em class="fontTahoma">/</em>办业务</span></a>
        <p class="menu">
            <a dcs_id="VAS_MENU_0" class="ac_dcstracker_vasmenu" target="_blank"
               href="https://shop.10086.cn/list/146_771_771_1_0_0_0_0_0.html">全部</a><i>|</i> <a dcs_id="VAS_MENU_1"
                                                                                                class="ac_dcstracker_vasmenu"
                                                                                                target="_blank"
                                                                                                href="https://shop.10086.cn/list/146_771_771_1_0_0_0_0_1.html">流量业务</a><i>|</i>
            <a dcs_id="VAS_MENU_2" class="ac_dcstracker_vasmenu" target="_blank"
               href="https://shop.10086.cn/list/146_771_771_1_0_0_0_0_2.html">数据业务</a><i>|</i> <a dcs_id="VAS_MENU_3"
                                                                                                  class="ac_dcstracker_vasmenu"
                                                                                                  target="_blank"
                                                                                                  href="https://shop.10086.cn/list/146_771_771_1_0_0_0_0_3.html">优惠业务包</a>
        </p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="VAS_AD_0" class="ac_dcstracker_VAS_AD"
                   href="http://shop.10086.cn/list/146_771_771_0_0_0_0.html" target="_blank" title=""><img
                            src="${IMAGE_SERVER}cloud/static/store/images/t29hqzh9pz5ffv32p.png"
                            data-original="//img1.shop.10086.cn/file/t29hqzh9pz5ffv32p.png" class="lazy " alt=""
                            style="display: block;"></a></li>
        </ul>

        <div class="modGoods">
            <div class="yewuList clearfix">
                <ul class="clearfix withhover">
                    <li class="position clearfix">


                        <a title="流量小时包" dcs_id="VAS_GOODS_PICURL_0" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080857_1063668.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th5wfkkmjc3tt2uqt_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th5wfkkmjc3tt2uqt_100x100.png" alt="流量小时包"
                                    style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="流量日包" dcs_id="VAS_GOODS_PICURL_1" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080870_1063691.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th57bs66djdtt9dp8_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th57bs66djdtt9dp8_100x100.png" alt="流量日包"
                                    style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="流量季包" dcs_id="VAS_GOODS_PICURL_2" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080931_1064919.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th38ud4ng5zttqszc_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th38ud4ng5zttqszc_100x100.png" alt="流量季包"
                                    style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="流量半年包" dcs_id="VAS_GOODS_PICURL_3" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080932_1063810.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th38upjwa5att2u2j_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th38upjwa5att2u2j_100x100.png" alt="流量半年包"
                                    style="display: inline;"></a>
                    </li>
                    <li class="position clearfix w1khide">


                        <a title="流量年包" dcs_id="VAS_GOODS_PICURL_4" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080934_1063814.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th38tr4ay5rtt2t79_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th38tr4ay5rtt2t79_100x100.png" alt="流量年包"
                                    style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="流量夜间包10GB版" dcs_id="VAS_GOODS_PICURL_5" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080929_1063802.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th33mmjg4bnttry2q_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th33mmjg4bnttry2q_100x100.png"
                                    alt="流量夜间包10GB版" style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="月末流量包" dcs_id="VAS_GOODS_PICURL_6" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1058999_1044959.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th3cacdqauwtt2rtux_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th3cacdqauwtt2rtux_100x100.png"
                                    alt="月末流量包" style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="暖心流量7天包（5GB）" dcs_id="VAS_GOODS_PICURL_7" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1080166_1062836.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/th9baqzeh2ztty68s_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/th9baqzeh2ztty68s_100x100.png"
                                    alt="暖心流量7天包（5GB）" style="display: inline;"></a>
                    </li>
                    <li class="position clearfix">


                        <a title="5G特惠流量包" dcs_id="VAS_GOODS_PICURL_8" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1079702_1061940.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thvfx8txbpgtt2ysk_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/thvfx8txbpgtt2ysk_100x100.png"
                                    alt="5G特惠流量包" style="display: inline;"></a>
                    </li>
                    <li class="position clearfix w1khide">


                        <a title="全网追剧流量包" dcs_id="VAS_GOODS_PICURL_9" class="ac_dcstracker_vasphone"
                           href="https://shop.10086.cn/goods/771_771_1075804_1057533.html" target="_blank"><img
                                    class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/tas357nsyqrttgr4x_100x100.png"
                                    data-original="//img1.shop.10086.cn/goods/tas357nsyqrttgr4x_100x100.png"
                                    alt="全网追剧流量包" style="display: inline;"></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="barTitle clearfix">
        <em class="icon haoma"></em>
        <a dcs_id="NUMBER" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/134_771_771_0_0_0_0.html"><span class="name">4F<em class="fontTahoma">/</em>选号码</span></a>
        <p class="menu">
            <a dcs_id="NUMBER_MENU_0" class="ac_dcstracker_numbermenu" target="_blank"
               href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_0.html">全部</a><i>|</i> <a dcs_id="NUMBER_MENU_1"
                                                                                                class="ac_dcstracker_numbermenu"
                                                                                                target="_blank"
                                                                                                href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_1.html">幸运号</a><i>|</i>
            <a dcs_id="NUMBER_MENU_2" class="ac_dcstracker_numbermenu" target="_blank"
               href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_2.html">爱情号</a><i>|</i> <a dcs_id="NUMBER_MENU_3"
                                                                                                 class="ac_dcstracker_numbermenu"
                                                                                                 target="_blank"
                                                                                                 href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_3.html">年代号</a><i>|</i>
            <a dcs_id="NUMBER_MENU_4" class="ac_dcstracker_numbermenu" target="_blank"
               href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_4.html">生日号</a><i>|</i> <a dcs_id="NUMBER_MENU_5"
                                                                                                 class="ac_dcstracker_numbermenu"
                                                                                                 target="_blank"
                                                                                                 href="https://shop.10086.cn/list/134_771_771_1_0_0_0_0_5.html">星座号</a>
        </p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="NUMBER_AD_0" class="ac_dcstracker_NUMBER_AD"
                   href="https://shop.10086.cn/goods/771_771_numcard_1065430.html" target="_blank" title=""><img
                            src="${IMAGE_SERVER}cloud/static/store/images/thrrhkuaaspttrbwx.png"
                            data-original="//img1.shop.10086.cn/file/thrrhkuaaspttrbwx.png" class="lazy big" alt=""
                            style="display: block;"></a></li>
        </ul>

        <div class="modGoods position">
            <div class="numSearch clearfix">
                <div class="title">
                    <p>139</p>
                    <ul class="clearfix">
                        <li><a dcs_id="NUMBER_SEGMENT_1" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">134</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_2" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">135</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_3" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">136</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_4" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">137</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_5" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">138</a></li>
                        <li class="current"><a dcs_id="NUMBER_SEGMENT_6" class="ac_dcstracker_numberhd"
                                               href="javascript:void(0);">139</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_7" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">147</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_8" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">150</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_9" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">151</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_10" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">152</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_11" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">157</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_12" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">158</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_13" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">159</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_14" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">178</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_15" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">182</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_16" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">183</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_17" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">184</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_18" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">187</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_19" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">188</a></li>
                        <li><a dcs_id="NUMBER_SEGMENT_20" class="ac_dcstracker_numberhd"
                               href="javascript:void(0);">198</a></li>
                    </ul>
                </div>
                <div class="num clearfix">
                    <input dcs_id="NUMBER_INPUT_1" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_2" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_3" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_4" type="text" maxlength="1" class="hf">
                    <input dcs_id="NUMBER_INPUT_5" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_6" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_7" type="text" maxlength="1">
                    <input dcs_id="NUMBER_INPUT_8" type="text" maxlength="1">
                </div>
                <a href="javascript:void(0)" id="numBtn" dcs_id="NUMBER_SEARCH"
                   class="btn btnBig btnBlue floatright"><i></i><b></b><em>立即搜索</em></a>
            </div>
            <div class="numList">
                <ul class="clearfix" style="height:170px;" id="numListArea">
                    <li class="clearfix">
                        <span class="num">152 <em>7810</em> 6039</span>
                        <a dcs_id="NUMBER_GOODS_0" href="https://shop.10086.cn/goods/771_771_num_38889714.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">182 <em>6901</em> 3189</span>
                        <a dcs_id="NUMBER_GOODS_1" href="https://shop.10086.cn/goods/771_771_num_38889944.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 7902</span>
                        <a dcs_id="NUMBER_GOODS_2" href="https://shop.10086.cn/goods/771_771_num_38107696.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">152 <em>7706</em> 1956</span>
                        <a dcs_id="NUMBER_GOODS_3" href="https://shop.10086.cn/goods/771_771_num_38889642.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8673</span>
                        <a dcs_id="NUMBER_GOODS_4" href="https://shop.10086.cn/goods/771_771_num_38119562.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8676</span>
                        <a dcs_id="NUMBER_GOODS_5" href="https://shop.10086.cn/goods/771_771_num_38119566.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8702</span>
                        <a dcs_id="NUMBER_GOODS_6" href="https://shop.10086.cn/goods/771_771_num_38119570.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8703</span>
                        <a dcs_id="NUMBER_GOODS_7" href="https://shop.10086.cn/goods/771_771_num_38119574.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8706</span>
                        <a dcs_id="NUMBER_GOODS_8" href="https://shop.10086.cn/goods/771_771_num_38119578.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8707</span>
                        <a dcs_id="NUMBER_GOODS_9" href="https://shop.10086.cn/goods/771_771_num_38119582.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>

                    <li class="clearfix">
                        <span class="num">147 <em>9574</em> 8710</span>
                        <a dcs_id="NUMBER_GOODS_10" href="https://shop.10086.cn/goods/771_771_num_38119590.html"
                           target="_blank" class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
                    </li>
                </ul>
                <a dcs_id="NUMBER_MORE" class="showMore green ac_dcstracker_numbermore" target="_blank"
                   href="https://shop.10086.cn/list/134_771_771_0_0_0_0.html">查看更多号码<em class="famSun">&gt;&gt;</em></a>
            </div>
        </div>
    </div>
    <script type="text/html" id="numberTemplate">
        <li class="clearfix">
            <span class="num">{numstr}</span>
            <a dcs_id="NUMBER_GOODS_{index}" href="{jump_url}" target="_blank"
               class="buy ac_dcstracker_numberphone"><i></i><b></b>购买</a>
        </li>
    </script>


    <div class="barTitle clearfix">
        <em class="icon taocan"></em>
        <a dcs_id="BROADBAND" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/152_771_771_0_0_0_0.html"><span class="name">5F<em class="fontTahoma">/</em>办宽带</span></a>
        <p class="menu">
            <a dcs_id="BROADBAND_MENU_0" class="ac_dcstracker_broadbandmenu" target="_blank"
               href="https://shop.10086.cn/list/152_771_771_1_0_0_0_0_0_0.html">全部</a><i>|</i> <a
                    dcs_id="BROADBAND_MENU_1" class="ac_dcstracker_broadbandmenu" target="_blank"
                    href="https://shop.10086.cn/list/152_771_771_1_0_0_1_0_0_0.html">宽带新装</a></p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="BROADBAND_AD_0" class="ac_dcstracker_BROADBAND_AD"
                   href="https://shop.10086.cn/list/152_771_771_1_0_0_1_0_0.html" target="_blank" title=""><img
                            src="${IMAGE_SERVER}cloud/static/store/images/t7q99b3tt5n6tt32xs.png"
                            data-original="//img1.shop.10086.cn/file/t7q99b3tt5n6tt32xs.png" class="lazy big" alt=""
                            style="display: block;"></a></li>
        </ul>

        <div class="modGoods">
            <ul class="taocanList clearfix">
                <li>
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="BROADBAND_GOODS_PICURL_0" class="ac_dcstracker_broadband"
                               href="https://shop.10086.cn/goods/771_771_1078000_1060222.html" target="_blank"
                               title="5G智享宽带1000M"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/tapsug7tahcttdepj_100x100.png"
                                                        data-original="//img1.shop.10086.cn/goods/tapsug7tahcttdepj_100x100.png"
                                                        alt="5G智享宽带1000M" style="display: block;"></a>
                        </dt>

                        <dd class="name size16">0.00起</dd>
                        <dd><span class="red size12"><em class="fontTahoma" title=""></em></span></dd>
                        <dd class="size12" title="5G智享套餐（家庭版）869元档专享">5G智享套餐（家庭版）869元...</dd>
                        <dd class="size12">
                            <a dcs_id="BROADBAND_GOODS_BT_0" class="ac_dcstracker_broadband" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1078000_1060222.html">立即办理<em class="fontSun">&gt;&gt;</em></a>
                        </dd>

                    </dl>
                </li>
                <li>
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="BROADBAND_GOODS_PICURL_1" class="ac_dcstracker_broadband"
                               href="https://shop.10086.cn/goods/771_771_1077999_1060221.html" target="_blank"
                               title="5G家庭套餐569档宽带500M"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thrtrtdsu2httg8r9_100x100.png"
                                                             data-original="//img1.shop.10086.cn/goods/thrtrtdsu2httg8r9_100x100.png"
                                                             alt="5G家庭套餐569档宽带500M" style="display: block;"></a>
                        </dt>

                        <dd class="name size16">0.00起</dd>
                        <dd><span class="red size12"><em class="fontTahoma" title=""></em></span></dd>
                        <dd class="size12" title="享500M">享500M</dd>
                        <dd class="size12">
                            <a dcs_id="BROADBAND_GOODS_BT_1" class="ac_dcstracker_broadband" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1077999_1060221.html">立即办理<em class="fontSun">&gt;&gt;</em></a>
                        </dd>

                    </dl>
                </li>
                <li>
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="BROADBAND_GOODS_PICURL_2" class="ac_dcstracker_broadband"
                               href="https://shop.10086.cn/goods/771_771_1077997_1060220.html" target="_blank"
                               title="5G家庭套餐369档宽带300M"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thrtnxrvrqpttgdrs_100x100.png"
                                                             data-original="//img1.shop.10086.cn/goods/thrtnxrvrqpttgdrs_100x100.png"
                                                             alt="5G家庭套餐369档宽带300M" style="display: block;"></a>
                        </dt>

                        <dd class="name size16">0.00起</dd>
                        <dd><span class="red size12"><em class="fontTahoma" title=""></em></span></dd>
                        <dd class="size12" title="享300M">享300M</dd>
                        <dd class="size12">
                            <a dcs_id="BROADBAND_GOODS_BT_2" class="ac_dcstracker_broadband" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1077997_1060220.html">立即办理<em class="fontSun">&gt;&gt;</em></a>
                        </dd>

                    </dl>
                </li>
                <li>
                    <dl class="clearfix">
                        <dt class="position">


                            <a dcs_id="BROADBAND_GOODS_PICURL_3" class="ac_dcstracker_broadband"
                               href="https://shop.10086.cn/goods/771_771_1077991_1060215.html" target="_blank"
                               title="5G家庭套餐269档200M"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thrtn435b9ettgkjg_100x100.png"
                                                           data-original="//img1.shop.10086.cn/goods/thrtn435b9ettgkjg_100x100.png"
                                                           alt="5G家庭套餐269档200M" style="display: block;"></a>
                        </dt>

                        <dd class="name size16">0.00起</dd>
                        <dd><span class="red size12"><em class="fontTahoma" title=""></em></span></dd>
                        <dd class="size12" title="享200M">享200M</dd>
                        <dd class="size12">
                            <a dcs_id="BROADBAND_GOODS_BT_3" class="ac_dcstracker_broadband" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1077991_1060215.html">立即办理<em class="fontSun">&gt;&gt;</em></a>
                        </dd>

                    </dl>
                </li>
            </ul>
        </div>
    </div>


    <div class="barTitle clearfix">
        <em class="icon peijian"></em>
        <a dcs_id="ACCESSORY" class="ac_dcstracker_common" act="FLOOR_TITLE" target="_blank"
           href="https://shop.10086.cn/list/128_771_771_0_0_0_0.html"><span class="name">6F<em class="fontTahoma">/</em>挑配件</span></a>
        <p class="menu">
            <a dcs_id="ACCESSORY_MENU_0" class="ac_dcstracker_accessorymenu" target="_blank"
               href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_0.html">全部</a><i>|</i> <a
                    dcs_id="ACCESSORY_MENU_1" class="ac_dcstracker_accessorymenu" target="_blank"
                    href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_15.html">移动电源</a><i>|</i> <a
                    dcs_id="ACCESSORY_MENU_2" class="ac_dcstracker_accessorymenu" target="_blank"
                    href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_13.html">蓝牙耳机</a><i>|</i> <a
                    dcs_id="ACCESSORY_MENU_3" class="ac_dcstracker_accessorymenu" target="_blank"
                    href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_12.html">手机壳</a><i>|</i> <a
                    dcs_id="ACCESSORY_MENU_4" class="ac_dcstracker_accessorymenu" target="_blank"
                    href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_6.html">智能家居</a><i>|</i> <a
                    dcs_id="ACCESSORY_MENU_5" class="ac_dcstracker_accessorymenu" target="_blank"
                    href="https://shop.10086.cn/list/128_771_771_1_0_0_0_0_10.html">健康监测</a></p>
    </div>
    <div class="clearfix">
        <ul class="modCm clearfix">
            <li><a dcs_id="ACCESSORY_AD_0" class="ac_dcstracker_ACCESSORY_AD"
                   href="http://shop.10086.cn/list/128_771_771_0_0_0_0.html" target="_blank" title=""><img
                            src="${IMAGE_SERVER}cloud/static/store/images/t6hg6qbqhvmtt69nw.png"
                            data-original="//img1.shop.10086.cn/file/t6hg6qbqhvmtt69nw.png" class="lazy " alt=""
                            style="display: block;"></a></li>
        </ul>

        <div class="modGoods">
            <div class="pjList clearfix">
                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_GOODS_PICURL_0" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/200_200_1081088_1064143.html?WT.ac=res_search_042_200_4266d24cf7154e7aa5f529c6e87a0630_1081088"
                           target="_blank" title="Airpods Pro耳机"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thw5pg2vax7q29g5.png"
                                                                      data-original="//img1.shop.10086.cn/file/thw5pg2vax7q29g5.png"
                                                                      alt="Airpods Pro耳机" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_GOODS_TITLE_0" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/200_200_1081088_1064143.html?WT.ac=res_search_042_200_4266d24cf7154e7aa5f529c6e87a0630_1081088"
                                                  target="_blank">Airpods Pro耳机 阻隔噪音，倾耳听。</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>1618.00</dd>
                </dl>
                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_GOODS_PICURL_1" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/200_200_1073571_1061954.html" target="_blank"
                           title="小度在家 智能音箱"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thw5p5722rzqnrhf.png"
                                                  data-original="//img1.shop.10086.cn/file/thw5p5722rzqnrhf.png"
                                                  alt="小度在家 智能音箱" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_GOODS_TITLE_1" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/200_200_1073571_1061954.html"
                                                  target="_blank">小度在家 智能音箱 小度在家 陪伴在家</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>359.00</dd>
                </dl>
                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_GOODS_PICURL_2" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/200_200_1079933_1062472.html" target="_blank"
                           title="斯泰克多功能消毒护理盒"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/the3fs89h8gtt5tpq.png"
                                                    data-original="//img1.shop.10086.cn/file/the3fs89h8gtt5tpq.png"
                                                    alt="斯泰克多功能消毒护理盒" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_GOODS_TITLE_2" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/200_200_1079933_1062472.html"
                                                  target="_blank">斯泰克多功能消毒护理盒 防疫好物</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>168.00</dd>
                </dl>
                <dl class="clearfix w1khide">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_GOODS_PICURL_3" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/200_200_1082065_1066318.html?WT.ac=res_search_042_200_f062bd24464648169f830e434eafdc67_1082065"
                           target="_blank" title="华为路由器"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thw5x63rpteq3tdn.png"
                                                              data-original="//img1.shop.10086.cn/file/thw5x63rpteq3tdn.png"
                                                              alt="华为路由器" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_GOODS_TITLE_3" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/200_200_1082065_1066318.html?WT.ac=res_search_042_200_f062bd24464648169f830e434eafdc67_1082065"
                                                  target="_blank">华为路由器 凌霄双核</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>249.00</dd>
                </dl>

                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_ZNSB_PICURL_0" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/771_771_1044379_1039192.html" target="_blank"
                           title="有品智能体脂秤家用"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/t7arjsctufxrttq4q2.png"
                                                  data-original="//img1.shop.10086.cn/file/t7arjsctufxrttq4q2.png"
                                                  alt="有品智能体脂秤家用" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_ZNSB_TITLE_0" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/771_771_1044379_1039192.html"
                                                  target="_blank">有品智能体脂秤家用 测试身体29项数据</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>88.00</dd>
                </dl>
                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_ZNSB_PICURL_1" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/771_771_1081542_1065047.html" target="_blank"
                           title="中国移动和目智能可视门铃D1"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/thq7hkz4wfcttr7rg.png"
                                                       data-original="//img1.shop.10086.cn/file/thq7hkz4wfcttr7rg.png"
                                                       alt="中国移动和目智能可视门铃D1" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_ZNSB_TITLE_1" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/771_771_1081542_1065047.html"
                                                  target="_blank">中国移动和目智能可视门铃D1 和目智能可视门...</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>369.00</dd>
                </dl>
                <dl class="clearfix ">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_ZNSB_PICURL_2" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/771_771_1056674_1042893.html" target="_blank"
                           title="和目智能路由器双频"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/t7zp3utmjectt53de.png"
                                                  data-original="//img1.shop.10086.cn/file/t7zp3utmjectt53de.png"
                                                  alt="和目智能路由器双频" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_ZNSB_TITLE_2" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/771_771_1056674_1042893.html"
                                                  target="_blank">和目智能路由器双频 双频四天线 无惧穿墙</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>199.00</dd>
                </dl>
                <dl class="clearfix w1khide">
                    <dt class="position">


                        <a dcs_id="ACCESSORY_ZNSB_PICURL_3" class="ac_dcstracker_accessoryphone"
                           href="https://shop.10086.cn/goods/771_771_1070616_1050563.html" target="_blank"
                           title="和目高清智能摄像头C31"><img class="lazy" src="${IMAGE_SERVER}cloud/static/store/images/t7zp3k4jdt4tt58vj.png"
                                                     data-original="//img1.shop.10086.cn/file/t7zp3k4jdt4tt58vj.png"
                                                     alt="和目高清智能摄像头C31" style="display: block;"></a>
                    </dt>
                    <dd class="name hoverBlue"><a dcs_id="ACCESSORY_ZNSB_TITLE_3" class="ac_dcstracker_accessoryphone"
                                                  href="https://shop.10086.cn/goods/771_771_1070616_1050563.html"
                                                  target="_blank">和目高清智能摄像头C31 智慧随动 双重存储</a></dd>
                    <dd class="price red size20"><span class="fontYaHei size14">￥</span>299.00</dd>
                </dl>
            </div>
        </div>
    </div>


    <div class="clearfix ad marginTop10">
        <a href="https://shop.10086.cn/goods/100_100_1015876_1064683.html" class="ac_dcs_base"
           dcs_id="ad_accessory_https://shop.10086.cn/goods/100_100_1015876_1064683.html" target="_blank"><img
                    src="${IMAGE_SERVER}cloud/static/store/images/th723r4nc3ytffkh5.png"></a>
    </div>


</div>


<style type="text/css">
    .lowerIEtips {
        display: none;
        _display: block;
        _position: absolute;
    }
</style>
<#--<div class="globalMain margin10">
    <div class="footerService">
        <ul class="clearfix">
            <li>
                <dl class="clearfix gwzn">
                    <dt>购物指南</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_0" target="_blank" title="用户注册"
                           href="https://shop.10086.cn/help/771_771/14.html">用户注册</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_1" target="_blank" title="用户登录"
                           href="https://shop.10086.cn/help/771_771/18.html">用户登录</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_2" target="_blank" title="购物说明"
                           href="https://shop.10086.cn/help/771_771/7.html">购物说明</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix zffs">
                    <dt>付款方式</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_1_0" target="_blank" title="在线支付"
                           href="https://shop.10086.cn/help/771_771/27.html">在线支付</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_1_1" target="_blank" title="货到付款"
                           href="https://shop.10086.cn/help/771_771/29.html">货到付款</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix wlps">
                    <dt>物流配送</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_2_0" target="_blank" title="快递配送"
                           href="https://shop.10086.cn/help/771_771/30.html">快递配送</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_2_1" target="_blank" title="签收提示"
                           href="https://shop.10086.cn/help/771_771/19.html">签收提示</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix shfw">
                    <dt>售后服务</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_0" target="_blank" title="退换货原则"
                           href="https://shop.10086.cn/help/771_771/31.html">退换货原则</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_1" target="_blank" title="退款说明"
                           href="https://shop.10086.cn/help/771_771/12.html">退款说明</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_2" target="_blank" title="退货申请/查询"
                           href="https://shop.10086.cn/help/771_771/21.html">退货申请/查询</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix grzx">
                    <dt>个人中心</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_0" target="_blank" title="我的订单"
                           href="https://shop.10086.cn/help/771_771/28.html">我的订单</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_1" target="_blank" title="充值交费"
                           href="https://shop.10086.cn/help/771_771/20.html">充值交费</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_2" target="_blank" title="我的账户"
                           href="https://shop.10086.cn/help/771_771/16.html">我的账户</a>
                    </dd>
                </dl>
            </li>
        </ul>
    </div>
</div>-->
<#include "../common/footerNav.ftlh">
<#--<div id="footer">
    <p>
        <a href="http://www.10086.cn/aboutus/news/" target="_blank">新闻中心</a>
        | <a href="http://job.10086.cn/" target="_blank">诚聘英才</a>
        | <a href="http://b2b.10086.cn/" target="_blank">采购信息</a>
        | <a href="http://www.10086.cn/aboutus/hezuo/" target="_blank">企业合作</a>
        | <a href="http://www.10086.cn/web_notice/contact/" target="_blank">联系我们</a>
        | <a href="http://www.10086.cn/web_notice/navigation/" target="_blank">站点导航</a>
        | <a href="http://labs.chinamobile.com/" target="_blank">中国移动研究院</a>
        | <a href="http://www.cmdi.chinamobile.com/" target="_blank">中国移动设计院</a>
        | <a href="http://www.10086.cn/web_notice/links/" target="_blank">友情链接</a>
        | <a href="https://www.10086.cn/events/djcx/" class="red" style="color:#ed2668" target="_blank">打击传销</a>
    </p>
    <p>掌上营业厅：<a href="http://wap.10086.cn/" target="_blank">wap.10086.cn</a> 语音自助服务：10086 短信营业厅：10086 <a
                href="http://www.10086.cn/support/service/channel/entity/" target="_blank">自助终端</a> <a
                href="http://www.10086.cn/support/service/channel/entity/" target="_blank">营业厅</a> <a
                href="http://www.10086.cn/cmccclient/index.htm" target="_blank">手机营业厅下载</a></p>
    <p style="width:300px; margin:0 auto;" class="clearfix">
        <a target="_blank"
           href="https://ss.knet.cn/verifyseal.dll?sn=e130905110100423008ilb000000&ct=df&a=1&pa=0.3082310492237422"
           class="floatleft"><img src="${IMAGE_SERVER}cloud/static/store/images/cnnic.png__0.png" align="absmiddle" oncontextmenu="return false;"></a>
        <span class="floatleft alignleft" style="padding-left:20px;">
			<a href="http://beian.miit.gov.cn/" target="_blank"><img src="${IMAGE_SERVER}cloud/static/store/images/gov.gif__0.gif" align="absmiddle">京ICP备05002571号</a><br>　中国移动通信版权所有
		</span>
    </p>
</div>-->
<#include "../common/footer.ftlh">
<div class="mask" id="mask"></div>
<div class="lowerIEtips" style="position: fixed;_position: absolute;bottom:0px;display:none;_display:block;">
    <div class="tipcon"><span><img src="${IMAGE_SERVER}cloud/static/store/images/logo2.png__240.png" style="width: 160px; height: 29px;"></span>
        <p>您的浏览器版本过低，如果页面显示不正常，建议将浏览器升级到最新版本。</p><!-- <a class="close" id="closeTips"></a> --></div>
</div>

<div id="" class="rightfloatbox">
    <ul class="rightfloatnav" id="returntop" style="display: none;">
        <li><a dcs="fast_link_phone" target="_blank" href="https://shop.10086.cn/order/shoplist.php"
               class="ac_footer_sdc rfn_9 ac_cart1_count ac_dcs_base" dcs_id="NAV_RIGHTFLOAT_CART">购物车</a>
            <span class="cart-quan"><b></b><em>1</em><i></i></span></li>
        <li><a dcs="fast_link_phone" target="_blank" href="https://shop.10086.cn/list/101_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_1">购买手机</a></li>
        <li><a dcs="fast_link_package" target="_blank" href="https://shop.10086.cn/list/140_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_8">办理套餐</a></li>
        <li><a dcs="fast_link_service" target="_blank" href="https://shop.10086.cn/list/146_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_2">办理业务</a></li>
        <li><a dcs="fast_link_number" target="_blank" href="https://shop.10086.cn/list/134_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_3">选购号码</a></li>
        <li><a dcs="fast_link_accessory" target="_blank" href="https://shop.10086.cn/list/128_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_4">挑选配件</a></li>
        <li><a dcs="fast_link_home" target="_blank" href="https://shop.10086.cn/i/?f=home" class="ac_footer_sdc rfn_5">个人中心</a>
        </li>
        <li><a dcs="fast_link_zxkf" target="_blank"
               href="https://shop.10086.cn/ac/livechat-web-client/robertIndex?tenantId=1000078&code=BS&channelType=1011"
               class="ac_footer_sdc rfn_zxkf">在线客服</a></li>
        <li><a dcs="fast_link_top" href="https://shop.10086.cn/mall_771_771.html#" class="ac_footer_sdc rfn_7">返回顶部</a>
        </li>
    </ul>

    <div class="dorpdown-layer" style="display:none">


        <style type="text/css">
            .cart-layer .cart_list {
                width: 350px;
            }

            .height268 {
                height: 268px;
            }

            .cart-layer .loadingBlock {
                height: 75px;
            }
        </style>
        <div class="have_goods">
            <div class="cart-layer" style="border-bottom: 1px solid #ECECEC">
                <div class="loadingBlock"></div>
                <div class="cart_goodslist" style="display: none;">
                    <p class="smt top">最新加入的商品</p>
                    <p class="smt right">购物车</p>
                    <div id="content-1" class="cart_list mCustomScrollbar _mCS_2 mCS_no_scrollbar">
                        <div id="mCSB_2" class="mCustomScrollBox mCS-light mCSB_vertical mCSB_inside" tabindex="0"
                             style="max-height: 0px;">
                            <div id="mCSB_2_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y"
                                 style="position:relative; top:0; left:0;" dir="ltr">

                            </div>
                            <div id="mCSB_2_scrollbar_vertical"
                                 class="mCSB_scrollTools mCSB_2_scrollbar mCS-light mCSB_scrollTools_vertical"
                                 style="display: none;">
                                <div class="mCSB_draggerContainer">
                                    <div id="mCSB_2_dragger_vertical" class="mCSB_dragger"
                                         style="position: absolute; min-height: 30px; top: 0px;">
                                        <div class="mCSB_dragger_bar" style="line-height: 30px;"></div>
                                    </div>
                                    <div class="mCSB_draggerRail"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" btm black" style="display: none;">
                <p><span class="cartcount">共<b style="font-weight: normal">1</b>件商品</span> 共计：<span class="red">¥ <b
                                style="font-weight: normal"></b></span></p>
                <a href="https://shop.10086.cn/order/shoplist.php" class="btn btnGraySmall btnRed ac_dcs_base"
                   dcs_id="NAV_CART_GO">去购物车<em></em><i></i><b></b></a>
            </div>
        </div>
        <!--<img class="ajax_loading" style="margin-left: 155px;" src="//img0.shop.10086.cn/www/core/css/global/ajax_loading_max.gif__81.gif" />-->
        <div id="" class="nogoods btm black" style="display: none;">
            <p class="nogoods_p">购物车内暂时还没有商品</p>
            <p class="abate" style="display:none">您购物车里的商品均已失效</p>
            <a href="https://shop.10086.cn/order/shoplist.php"
               class="btn btnGraySmall btnRed">去购物车<em></em><i></i><b></b></a>
        </div>


        <b class="cart-mask	"></b>
    </div>
</div>


<script type="text/javascript" src="${IMAGE_SERVER}cloud/static/store/js/loader.js__357.js"></script>
<script src="${IMAGE_SERVER}cloud/static/store/js/sdc_mall.js__463.js"></script>
<script type="text/javascript">
    window.ENVOBJ = {
        "loc": {"province_id": 771, "city_id": 771},
        "loginurl": "https:\/\/login.10086.cn\/SSOCheck.action?channelID=12002&backUrl=https%3A%2F%2Fshop.10086.cn%2Fmall_771_771.html%3Fforcelogin%3D1"
    };
    LOADJS('//img0.shop.10086.cn/combo/__577/script/jquery-1.10.2.js__script/cookie/jquery.cookie.js__script/iprompt/jquery.iprompt.js__script/formater.js__script/pubsub/jquery.pubsub.js__script/interactive/jquery.interactive.js__script/jquery.lazyload.js__www/core/js/global.js__www/core/js/fav.js__www/core/js/dcs_tracker.js__www/mod/search/js/shop_jsonp_search.js__script/mousewheel/jquery.mousewheel.js__script/customscrollbar/jquery.mCustomScrollbar.js__www/index/js/index.js__www/core/js/countdown.js__www/index/js/recharge.js', function () {
//	$.domains = window.ENVOBJ.domains;


        $
            .sub('click_login_mini', __mini_login)
            .sub('login_mini', __mini_login)
            .sub('login_mini_msg', __mini_login_msg)
        ;
        var _options = null
        var _spritebox = null;

        function __mini_login(event, options) {
            _options = options;
            var miniframe = $('#login_box').html();
            if (miniframe) {
                _spritebox = $('#jquery-interactive-box2').hide();
                $('#jquery-interactive-mask').hide();
                var $box = $.alert(miniframe, {
                    onLoad: function ($box) {
                        $box.find('.interactive-content').css({
                            'background-color': '#ECECEC'
                        });
                    },
                    onClose: function () {
                        $.pub('login_mini_cancel');
                        _options = null;
                        _spritebox = null;
                        $.UI.hide();
                    },
                    liveTime: null,
                    noCloser: false
                });
                return false;
            } else {
                return true;
            }
        }

        function __mini_login_msg(event, r) {
            if (window.initUser) {
                window.initUser(r);
            }
            $.UI.hide('alert');
            if (r.code == 0) {
                if (_options && typeof _options == 'object') $.ajax(_options);
                _options = null;
                if (_spritebox && _spritebox.length) {
                    $('#jquery-interactive-mask').show();
                    _spritebox.show();
                }
                _spritebox = null;
            } else {
                $.UI.hide();
            }
        }


        ;
        $(function () {
            $(".cart_list").mCustomScrollbar();
        });


        ;
        $(function () {

            var timer = null;
            $('.cart').hover(function () {
                var is_cart = '';
                if (is_cart) return false;
                clearTimeout(timer);
                $(".rightMenu .dorpdown-layer").show();
                //__hover_get_cart();
                //$.pub("hover_get_cart");
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $(".rightMenu .dorpdown-layer").hide();
                }, 100);
            });
            $('.dorpdown-layer').hover(function () {
                list_lock = false;
                clearTimeout(timer);
                $('.cart').addClass('current');
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $('.rightMenu .dorpdown-layer').hide();
                }, 100);
            });


            $
                .sub('click_cartlist_delete', __cartlist_delete, false)
                .sub('cartlist_del', cartlist_del, false)
            ;

            function __cartlist_delete() {
                var $t = $(this);
                var cartcount = $t.closest('ul').attr('cartcount');
                $.getJSON('/ajax/cartshop/delete.json', {selected: $t.closest('li').attr('cartid')}, function (r) {
                    if (r.code) {
                        $.alert(r.msg);
                    } else {
                        $t.closest('li').remove();
                        $cart_list = $('.rightMenu .cart_list').find('li');
                        if ($cart_list.length > 5) {
                            $('.cart_list').addClass('height268');
                        } else {
                            $('.cart_list').removeClass('height268');
                        }
                        ;
                        $.pub('cartlist_del');
                    }
                    ;
                });
            }

            function cartlist_del() {
                var c_num = $('.cart .red').text();
                $('.have_goods .cartcount b,.rightMenu .cart .red,.rightfloatbox .cart-quan em').text(parseInt(c_num - 1));
                $('#returntop .cart-quan em').text(parseInt(c_num - 1));
                var total = 0;
                var $cart_list = $('.rightMenu .cart_list').find('li');
                $($cart_list).each(function () {
                    var $t = $(this);
                    total += parseInt($t.attr('num')) * parseInt($t.attr('price') * 100) || 0;
                });
                $('.have_goods .btm .red b').text((total / 100).toFixed(2));
                if (c_num && c_num - 1 != 0) {
                    $('.dorpdown-layer .nogoods').hide();
                    $('.dorpdown-layer .have_goods').show();
                } else {
                    $('.dorpdown-layer .nogoods').show();
                    $('.dorpdown-layer .have_goods').hide();
                }
                ;
            }
        });


        $(document).ready(function () {
            var timers = null;

            $(".cmccclient").hover(function () {
                clearTimeout(timers);
                var cmcc_left_1 = $('.cmccclient').position().left + 2;
                $('.ewm').css('left', cmcc_left_1);
                $('.ewm').show();
            }, function () {
                timers = setTimeout(function () {
                    $('.ewm').hide();
                }, 100);
            });
            $('.ewm').hover(function () {
                var cmcc_left_2 = $('.cmccclient').position().left + 2;
                clearTimeout(timers);
                $('.cmccclient').addClass('cmccclienthover');
                $(this).css('left', cmcc_left_2);
                $(this).show();
            }, function () {
                var $t = $(this);
                timers = setTimeout(function () {
                    $('.cmccclient').removeClass('cmccclienthover');
                    $t.hide();
                }, 100);
            });
        });


        window.initUser = function (r) {
            if (r.code == 0) {
                window.loginUser = r.data;
                var nickname = r.data.nick_name || r.data.user_name;
                var tmpnick = nickname.split('@')[0];
                var noread = (r.data.msg_remind || {}).noread || 0;
                var showeye = r.data.is_china_mobile ? '' : 'eye-hide'; // 互联网用户不显示眼睛
                var tmpstr =
                    '<span class="tel floatleft marginRight10" title="' + nickname + '">' + tmpnick + '</span><i class="floatleft marginRight10 icon_eye ' + showeye + ' ac_handle_mobile"></i>' +
                    '<span class="floatleft noticearea" >' +
                    ' <a href="https://shop.10086.cn/i/?f=mynews"  target="_blank" class="red floatleft">消息 ' + noread + '</a> </span>' +
                    '<a class="red bold" href="javascript:void(logout())" title="退出">[退 出]</a><em>|</em>';
                document.getElementById('userinfo').innerHTML = tmpstr;
                if ($.pub) {
                    $.pub('login_success', r.data);
                }
                // 当前登陆人插码 ,如果是手机号登录，写入手机号，否则清空
                if (_tag) {
                    if (r.data.is_china_mobile) {
                        _tag.setMobile(r.data.wtmobile);
                    } else {
                        _tag.setMobile();
                    }
                }
            } else if (r.code == 3) {
                $('#ssocheckframe').attr('src', r.data);
            } else {
                $.pub('user_not_login_after_query');
                $('.btnOnestepbuy').hide();
                // 当前登陆人插码 没登陆清空
                if (_tag) {
                    _tag.setMobile();
                }
            }
        }
        var userParam = {
            'province_id': '771',
            'city_id': '771'
        }
        userParam.update = 1;
        $.getJSON('/ajax/user/userinfo.json', userParam, initUser);


        ;
        $(function () {
            var provinceId = "771";	//省区编码
            var cityId = "771";	//市区编码
            var charset = "utf-8";

            $("#skeywords").search({
                type: 1,
                maxResult: 10,
                provinceId: provinceId,
                cityId: cityId,
                tabType: 1,
                tabName: '',
                showDefaultWord: 1,
                showHotSearchWord: 1,
                charset: charset
            }).change(function () {
                $(this).siblings('[name="from"]').val('10601');
            });
        });


        $(function () {
            $('.shopSearch .mainmenu').hover(function () {
                $(this).addClass('hover');
            }, function () {
                $(this).removeClass('hover');
            });
            var dcs_map = {
                '101': 'Home_FirstScreen_PHONE',
                '140': 'Home_FirstScreen_EXPENSE',
                '146': 'Home_FirstScreen_VAS',
                '134': 'Home_FirstScreen_NUMBER',
                '128': 'Home_FirstScreen_ACCESORY',
                'jiaohuafei': 'Home_FirstScreen_HUAFEI',
                'home_firstscreen_grzx': 'Home_FirstScreen_PERSONALCENTER',
                'home_firstscreen_ad_1': 'Home_FirstScreen_AD_1',
                'home_firstscreen_ad_2': 'Home_FirstScreen_AD_2',
                'home_firstscreen_ad_3': 'Home_FirstScreen_AD_3',
                'home_firstscreen_ad_4': 'Home_FirstScreen_AD_4',
                'home_firstscreen_ljcz': 'Home_FirstScreen_RECHARGE',
                'home_firstscreen_hfcz': 'Home_FirstScreen_HF_RECHARGE',
                'home_firstscreen_llcz': 'Home_FirstScreen_LL_RECHARGE',
                'home_firstscreen_30': 'Home_FirstScreen_30',
                'home_firstscreen_50': 'Home_FirstScreen_50',
                'home_firstscreen_100': 'Home_FirstScreen_100',
                'home_firstscreen_200': 'Home_FirstScreen_200',
                'home_firstscreen_500': 'Home_FirstScreen_500'
            };
            $.sub('click_dcstracker_homefirstscreen', __dcstracker_homefirstscreen);

            function __dcstracker_homefirstscreen() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'FirstScreen',
                    event: dcs_map[$t.attr('dcs_id')] || $t.attr('dcs_id')
                });
            }
        });


        $(document).ready(function () {
            var timer = null;
            $('#nav .title').hover(function () {
                clearTimeout(timer);
                $(".spnav .smore").css('display', 'none');
                $(".spnav .goodsNav").show();
            }, function () {
                $(".spnav .smore").css('display', 'none');
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
            $(".spnav .goodsNav").hover(function () {
                clearTimeout(timer);
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
        });


        // $('.ac_dcs_base').not('.first .ac_dcs_base').mouseenter(function() {
        // 	$(this).css('border-top-color', '#0085D0');
        // 	$(this).closest('li').siblings().find('.ac_dcs_base').not('.shop_ini').css('border-top-color', '#EAEAEA');
        // }).eq(0).mouseenter();
        // $('.ac_dcs_base').not('.shop_ini').mouseout(function() {
        // 	$(this).css('border-top-color', '#EAEAEA');
        // })


        ;
        $(function () {
            $
                .sub('click_show_areabar', __show_areabar)
                .sub('click_show_city', __show_city)
                .sub('click_city_choose', __gotocity)
            ;

            //清除浮层
            function __clear_areabar() {
                $('#header').find('.area ul').hide();
            }

            //展开浮层
            function __show_areabar() {
                __clear_areabar();
                var $this = $(this);
                $this.next().show();
                return false;
            }

            function __gotocity(loc) {
                if (typeof loc != "string") {
                    loc = $(this).attr('location');
                }
                var locarray = loc.split('_');
                var pid = locarray[0], cid = locarray[1];
                var url = location.href;
                if (url.indexOf('/list/') > 0 || url.indexOf('/tags/') > 0) {
                    url = url.replace(/_\d{3}_\d{3,4}/i, "_" + loc);
                    setTimeout(function () {
                        location.href = url;
                    });
                } else {
                    setTimeout(function () {
                        location.href = "/mall_{loc}.html".replace("{loc}", loc);
                    });
                }
            }

            function getCityByProvince(province_id) {
                if (!window.allcity[province_id]) {
                    $.ajax({
                        async: false,
                        url: "/ajax/region/singleregion.json",
                        data: {province_id: province_id},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg)
                            } else {
                                window.allcity[province_id] = r.data || [];
                            }
                        },
                        dataType: 'json'
                    });
                }
                return window.allcity[province_id];
            }

            var $province = $('#header .province'),
                $city = $('#header .city'),
                current_province_id = $province.find('span').attr('province_id'),
                city_id = '771',
                reg = new RegExp('<!--|-->', 'g'),
                template = new Formater($('.header_area_template').html().replace(reg, '') || '<li><a href="#" target="_blank">{city_name}</a></li>'),
                city_name = '南宁'
            ;

            //点击省下拉项展开市浮层
            function __show_city() {
                var $this = $(this),
                    province_id = $this.attr('province_id'),
                    tmp = ''
                ;
                if ($this.attr('iscity')) {
                    __gotocity(province_id + "_" + province_id);
                    return false;
                }
                var data = getCityByProvince(province_id);
                $city.find('span').text('请选择');
                //var cityAreaWidth = (data.length < 4) ? 40*(data.length + 1) + 5 : 245;//根据市的个数，判断外框宽度
                $.each(data, function (inx, item) {
                    tmp += template.exec(item);
                });
                __clear_areabar();
                $this.closest('ul').prev().attr('province_id', $this.attr('province_id')).text($this.text());
                $city.find('ul').html(tmp).show();
                return false;
            }

            //点击其他dom收起浮层
            $(document).bind('click.area', function (e) {
                if ($(e.target).closest('.area').length == 0) {
                    __clear_areabar();
                }
                if ($(e.target).closest('.fs_box').length === 0) {
                    $('.fs_box ul').hide();
                }
            });

        })
        ;


        ;
        $(function () {
            var _mobileFuzzy = mobileFuzzy();

            $
                .sub('login_success', _mobileFuzzy.loginSuccess)
                .sub('click_send_msgcode4eye', _mobileFuzzy.sendMsgCode, false)
                .sub('click_handle_mobile', _mobileFuzzy.handleMobile, false)
            ;

            mobileFuzzy.$sms_mobile = $('#smsContent');

            function mobileFuzzy() {
                var mobile = null, isLogin = false, isShow = 0;
                var time = 60;
                var timer;

                // 填写mobile，并切换小眼睛的显示与隐藏
                function _handleMobile() {
                    var $eye = $('.userinfo .icon_eye');
                    isLogin && $('.userinfo .tel').text(mobile).attr('title', mobile);
                    mobile && (isShow ? $eye.removeClass('eye-close') : $eye.addClass('eye-close'));
                }

                // 发送验证码倒计时
                function _timeCountDown() {
                    var $msg_code = $('.sms-content .msg-code');
                    if (time === 0) {
                        clearInterval(timer);
                        $msg_code.removeClass('btnGray').addClass('ac_send_msgcode4eye btnBlue').find('span').text("重发验证码");
                        time = 60;
                        return false;
                    }
                    $msg_code.removeClass('btnBlue ac_send_msgcode4eye').addClass('btnGray').find('span').text(time + "s后发送");
                    time--;
                }

                // 弹出短信验证框
                function _popSmsBox() {
                    $.confirm($('#smsContent').html(), {
                        direction: null,
                        align: null,
                        mask: true,
                        noCloser: false,
                        preButtons: true,
                        onLoad: function ($box) {
                            $box.find('.mobile').html(mobile)
                        },
                        onAccept: _submitCheck
                    });
                }

                // 校验短信验证码是否正确，并设置返回值中的mobile和小眼睛状态等
                function _submitCheck() {
                    var flag = false;
                    $.ajax({
                        url: '/ajax/shownumber/submitcheck.json',
                        data: {msg_verify: $('.sms-content input[name="msg_verify"]').val()},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else if (r.data) {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                                flag = true;
                            }
                        },
                        dataType: 'json',
                        async: false
                    });
                    return flag;
                }

                // 点击小眼睛，控制手机号是否模糊化
                function _queryStatus() {
                    if (!isLogin) return;
                    $.getJSON('/ajax/shownumber/shownumber.json', {is_show: isShow}, function (r) {
                        if (r.code) {
                            $.alert(r.msg);
                        } else if (r.data) {
                            if (r.data.need_frame) {  // 后台告诉是否需要弹出短验窗口，need_frame=1表示当前登录状态会话下已经短信未校验过
                                _popSmsBox();
                            } else {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                            }
                        }
                    });
                }

                return {
                    // 校验是否登录，并填写用户名
                    loginSuccess: function () {
                        var user = arguments[0] instanceof jQuery.Event ? arguments[1] : arguments[0];
                        var nickname = user.nick_name || user.user_name;
                        // 如果是手机号用户，则设置isShow
                        if (user.is_china_mobile) {
                            isShow = user.num_show;
                            mobile = nickname;
                            isLogin = true;
                            _handleMobile();
                        }
                    },
                    handleMobile: _queryStatus,
                    // 发送短信验证码
                    sendMsgCode: function () {
                        $.getJSON('/ajax/shownumber/msg_send.json', function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else {
                                timer = setInterval(_timeCountDown, 1000);
                            }
                        });
                    }
                }
            }
        });


        $(function () {
            $('.shopSearch .mainmenu').hover(function () {
                $(this).addClass('hover');
            }, function () {
                $(this).removeClass('hover');
            });
            var dcs_map = {
                '101': 'Home_FirstScreen_PHONE',
                '140': 'Home_FirstScreen_EXPENSE',
                '146': 'Home_FirstScreen_VAS',
                '134': 'Home_FirstScreen_NUMBER',
                '128': 'Home_FirstScreen_ACCESORY',
                'jiaohuafei': 'Home_FirstScreen_HUAFEI',
                'home_firstscreen_grzx': 'Home_FirstScreen_PERSONALCENTER',
                'home_firstscreen_ad_1': 'Home_FirstScreen_AD_1',
                'home_firstscreen_ad_2': 'Home_FirstScreen_AD_2',
                'home_firstscreen_ad_3': 'Home_FirstScreen_AD_3',
                'home_firstscreen_ad_4': 'Home_FirstScreen_AD_4',
                'home_firstscreen_ljcz': 'Home_FirstScreen_RECHARGE',
                'home_firstscreen_hfcz': 'Home_FirstScreen_HF_RECHARGE',
                'home_firstscreen_llcz': 'Home_FirstScreen_LL_RECHARGE',
                'home_firstscreen_30': 'Home_FirstScreen_30',
                'home_firstscreen_50': 'Home_FirstScreen_50',
                'home_firstscreen_100': 'Home_FirstScreen_100',
                'home_firstscreen_200': 'Home_FirstScreen_200',
                'home_firstscreen_500': 'Home_FirstScreen_500'
            };
            $.sub('click_dcstracker_homefirstscreen', __dcstracker_homefirstscreen);

            function __dcstracker_homefirstscreen() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'FirstScreen',
                    event: dcs_map[$t.attr('dcs_id')] || $t.attr('dcs_id')
                });
            }
        });


        $(function () {

            //banner部分
            var $banner = $('#focus'),
                $bannerLi = $banner.find('li'),
                $liWidth = $bannerLi.eq(0).width(),
                $btnsHtml = '<p class="btns">',
                bannerCurrent = 0,
                timeBanner = 0;
            //计算ul宽度
            //$banner.find('ul').width($liWidth*$bannerLi.length);
            $bannerLi.each(function (i, item) {
                if (i == 0) {
                    $btnsHtml += '<span class="current">1</span>';
                } else {
                    $btnsHtml += '<span>' + (i + 1) + '</span>';
                }
            });
            $btnsHtml += '</p>';
            $banner.append($btnsHtml);
            $banner.find('.btns span').click(function () {
                var $this = $(this);
                clickIndex = $banner.find('.btns span').index($this);
                if (clickIndex != bannerCurrent) {
                    $bannerLi.eq(bannerCurrent).fadeOut(800);
                    $bannerLi.eq(clickIndex).fadeIn(800);
                    bannerCurrent = clickIndex;
                    $this.addClass('current').siblings('span').removeClass('current');
                }
            });

            function bannerNext() {
                clearTimeout(timeBanner);
                if (bannerCurrent >= $bannerLi.length - 1) {
                    $banner.find('.btns span').eq(0).triggerHandler('click');
                } else {
                    $banner.find('.btns span').eq(bannerCurrent + 1).triggerHandler('click');
                }
                timeBanner = setTimeout(bannerNext, 3000);
            }

            timeBanner = setTimeout(bannerNext, 6000);
            $banner.hover(function () {
                clearTimeout(timeBanner);
            }, function () {
                timeBanner = setTimeout(bannerNext, 3000);
            });


        });


        $(function () {


            //banner下方图片
            var $slideBox = $('#bannerSlide'),
                $slideLi = $slideBox.find('li'),
                liWidth = $slideLi.eq(0).outerWidth(),
                timeSlide = 0;
            $slideBox.find('ul').width($slideLi.length * liWidth);
            if ($slideLi.length > 3) {
                $slideBox.find('.turn_left, .turn_right').show();
            }
            $slideBox.find('.turn_left, .turn_right').click(function () {
                if (!$slideBox.find('ul').is(':animated') && $slideLi.length > 3) {
                    var $this = $(this);
                    var clickIndex = ($this.hasClass('turn_left')) ? -1 : 1;
                    if (clickIndex == -1) {
                        $slideBox.find('ul').css('left', -liWidth).find('li:last').prependTo($slideBox.find('ul')).end().end().animate({
                            'left': 0
                        });
                    } else if (clickIndex == 1) {
                        $slideBox.find('ul').animate({
                            'left': -liWidth
                        }, function () {
                            $slideBox.find('li:first').appendTo($slideBox.find('ul'));
                            $slideBox.find('ul').css('left', 0);
                        });
                    }
                }
            });

            function autoSlide() {
                clearTimeout(timeSlide);
                $slideBox.find('.turn_right').triggerHandler('click');
                timeSlide = setTimeout(autoSlide, 3000);
            }

            timeSlide = setTimeout(autoSlide, 4000);
            $slideBox.hover(function () {
                $slideBox.find('.turn_left').stop().animate({
                    left: 0
                });
                $slideBox.find('.turn_right').stop().animate({
                    right: 0
                });
                clearTimeout(timeSlide);
            }, function () {
                $slideBox.find('.turn_left').stop().animate({
                    left: '-28px'
                });
                $slideBox.find('.turn_right').stop().animate({
                    right: '-28px'
                });
                timeSlide = setTimeout(autoSlide, 3000);
            });
        });


        ;$(function () {
            $
                .sub('click_dcstracker_PHONE_AD', __dcstracker_phonead)
                .sub('click_dcstracker_phone', __dcstracker_phone)
            ;

            function __dcstracker_phonead() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'PHONE',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_phone() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'PHONE',
                    event: $t.attr('dcs_id')
                });
            }

            $.getJSON('/ajax/goods/get1freconmmendinfo.json', {province_id: 771, city_id: 771}, function (r) {
                if (r.data) {
                    $(".phoneList").replaceWith(r.data);
                    $('img.lazy', $('.modGoods')).lazyload({effect: 'fadeIn'});
                }
            });
        });


        ;$(function () {
            $
                .sub('click_dcstracker_EXPENSE_AD', __dcstracker_expensead)
                .sub('click_dcstracker_expensemenu', __dcstracker_expensemenu)
                .sub('click_dcstracker_expenseexpense', __dcstracker_expenseexpense)
            ;

            function __dcstracker_expensead() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'EXPENSE',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_expensemenu() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'EXPENSE',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_expenseexpense() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'EXPENSE',
                    event: $t.attr('dcs_id')
                });
            }

            $.getJSON('/ajax/goods/get3freconmmendinfo.json', {province_id: 771, city_id: 771}, function (r) {
                if (r.data) {
                    $(".taocanList").replaceWith(r.data);
                    $('img.lazy', $('.modGoods')).lazyload({effect: 'fadeIn'});
                }
            });
        });


        ;$(function () {
            $
                .sub('click_dcstracker_VAS_AD', __dcstracker_vasad)
                .sub('click_dcstracker_vasmenu', __dcstracker_vasmenu)
                .sub('click_dcstracker_vasphone', __dcstracker_vasphone)
            ;

            function __dcstracker_vasad() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'VAS',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_vasmenu() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'VAS',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_vasphone() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'VAS',
                    event: $t.attr('dcs_id')
                });
            }
        });


        $(function () {
            //号码左右滚动
            var $numSlideBox = $('.modGoods .numList');
            $numSlideBox.find('.turnLeft, .turnRight').click(function () {
                var $this = $(this);
                if ($this.hasClass('turnLeft')) {
                    $numSlideBox.find('li:last').prependTo($numSlideBox.find('ul'));
                } else {
                    $numSlideBox.find('li:first').appendTo($numSlideBox.find('ul'));
                }
            });
            //号码组换一组操作
            var p = 0;
            var param = {
                rows: 11,
                province_id: "771",
                city_id: "771"
            };
            var number_total = 0;
            var template = new Formater($('#numberTemplate').html());

            function getNextNums() {
                $.getJSON('/ajax/number/get4flist.json', param, function (r) {
                    if (r.code) {
                        $.alert(r.msg);
                    } else {
                        number_total = r.data.goods_total;
                        p = Math.floor(Math.random() * Math.ceil(number_total / 6) + 1);
                        param.p = p;
                        var r_html = '';
                        $(r.data.goods_list).each(function (i, item) {
                            item.index = i;
                            item.numstr = item.number_name.substring(0, 3) + ' <em>' + item.number_name.substring(3, 7) + '</em> ' + item.number_name.substring(7, 11);
                            r_html += template.exec(item);
                        });
                        $('#numListArea').html(r_html);
                    }
                });
            }

            getNextNums();
            $('.numRight .btnBlue').click(function () {
                getNextNums();
            });
            $('.numSearch ul li').click(function () {
                $('.numSearch .title p').text($(this).text());
                $(this).addClass('current').siblings().removeClass('current');
            });
            var $numInputs = $('.numSearch input');
            $numInputs.keyup(function () {
                if (this.value.length == 1) {
                    var $t = $(this);
                    $.dcstracker({
                        category: 'Home',
                        action: 'NUMBER',
                        event: $t.attr('dcs_id')
                    });
                    $t.next().focus();
                }
            });
            $('#numBtn').click(function () {
                var $t = $(this), str = $.trim($('.numSearch .title p').text()), isjump = true;
                $numInputs.each(function () {
                    //号码只准写数字
                    var re = new RegExp('^[0-9]+$|^$', 'g');
                    if (!re.test($.trim($(this).val()))) {
                        $(this).notice("请输入数字").focus();
                        isjump = false;
                        return false
                    }
                    str += $.trim($(this).val()) || '*';
                });
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
                if (isjump) {
                    setTimeout(function () {
                        location.href = "/list/134_771_771_0_0_0_0.html?key=" + str;
                    }, 500);
                }
            });
            //.numSearch .title 点击其他document下拉框收起
            $(document).bind('click.numselect', function (e) {
                if ($(e.target).closest('.numSearch .title').length == 0) {
                    $('.numSearch .title').removeClass('current');
                }
            });

            $
                .sub('click_dcstracker_NUMBER_AD', __dcstracker_numberad)
                .sub('click_dcstracker_numbermenu', __dcstracker_numbermenu)
                .sub('click_dcstracker_numberphone', __dcstracker_numberphone)
                .sub('click_dcstracker_numberhd', __dcstracker_numberhd)
                .sub('click_dcstracker_numbermore', __dcstracker_numbermore)
            ;

            function __dcstracker_numberad() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_numbermenu() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_numberphone() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_numberhd() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_numbermore() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'NUMBER',
                    event: $t.attr('dcs_id')
                });
            }
        });


        $(function () {
            $.sub('click_dcstracker_BROADBAND_AD', __dcstracker_broadband_ad)
                .sub('click_dcstracker_broadbandmenu', __dcstracker_broadbandmenu)
                .sub('click_dcstracker_broadband', __dcstracker_broadband);

            function __dcstracker_broadband_ad() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'BROADBAND',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_broadbandmenu() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'BROADBAND',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_broadband() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'BROADBAND',
                    event: $t.attr('dcs_id')
                });
            }
        });


        ;$(function () {
            $.sub('click_dcstracker_ACCESSORY_AD', __dcstracker_accessoryad)
                .sub('click_dcstracker_accessorymenu', __dcstracker_accessorymenu)
                .sub('click_dcstracker_accessoryphone', __dcstracker_accessoryphone);

            function __dcstracker_accessoryad() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'ACCESSORY',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_accessorymenu() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'ACCESSORY',
                    event: $t.attr('dcs_id')
                });
            }

            function __dcstracker_accessoryphone() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'ACCESSORY',
                    event: $t.attr('dcs_id')
                });
            }
        });


        $(function () {
            $.sub('click_dcstracker_common', __dcstracker_common).sub('click_dcs_acid', __dcs_acid);

            function __dcstracker_common() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: $t.attr('act'),
                    event: $t.attr('dcs_id')
                });
            }

            function __dcs_acid() {
                var $t = $(this);
                $.dcstracker({
                    ac_id: $t.attr('ac_id')
                });
            }

            function draw(arr, arrs) {
                var $area = $('.countdown');
                var $em = $area.find('em'), len = $em.length, data = arr, arr_a = [];
                if (len == 8) {
                    day = ('0' + arr[0]).slice(-2);
                    var daya = day.substring(0, 1), dayb = day.substring(1);
                    arr_a.push(daya, dayb);
                    $.each(arrs, function (index, item) {
                        arr_a.push(item);
                    });
                    data = arr_a;
                }
                $em.each(function (index, item) {
                    $(item).text(data[index]);
                });
            }

            window.drawCountdown = draw;
        });

        $(document).ready(function () {
            $(".favMsg p span").hover(function () {
                $(".favMsg p span").removeClass("cur");
                $(this).addClass("cur");
            });
            $(".tt_sckb").hover(function () {
                $(".con_scgg").hide();
                $(".con_sckb").show();
            });
            $(".tt_scgg").hover(function () {
                $(".con_sckb").hide();
                $(".con_scgg").show();
            });
            //精准营销
            var userParam = {
                'province_id': '771',
                'city_id': '771'
            };
            $.sub('login_success', checkUserInfo, true);
            var contype = ["index_ads_main_2", "taocan_list_0", "taocan_list_1", "taocan_list_2", "taocan_list_3"];
            var iopkeylist = [];
            for (var i in contype) {
                var $cmitem = $('[cmkey="' + contype[i] + '"]');
                if ($cmitem) {
                    iopkeylist.push(contype[i])
                }
            }
            var json = {
                "province_id": userParam.province_id,
                "city_id": userParam.city_id,
                "iop_key_list": iopkeylist
            };

            function checkUserInfo(event, userinfo) {
                if (userinfo) {
                    if (userinfo.province == userParam.province_id) {
                        $.ajax({
                            type: "POST",
                            url: "/ajax/promotion/getprecisionmarketing.json",
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            dataType: "json",
                            success: function (r) {
                                if (r.code == 0) {
                                    for (var i in r.data) {
                                        var da = r.data;
                                        if (da.length > 0) {
                                            $.dcstracker({'event': 'HOMEPC_JZSJ_CG'});
                                        } else {
                                            $.dcstracker({'event': 'HOMEPC_JZSJ_SB'});
                                        }
                                        var $cmitem = $('[cmkey="' + i + '"]');
                                        var jzdcsid = $cmitem.find('a').attr('dcs_id');
                                        $cmitem.find('a').attr('dcs_id', 'JZYX_' + jzdcsid);
                                        var link = r.data[i].link;
                                        var reg = /^\?WT.ac_id\=/;
                                        if (link.indexOf("?")) {
                                            if (!reg.test(link)) {
                                                link += '&WT.ac_id=' + r.data[i].ac_id;
                                            }
                                        } else {
                                            link += '?WT.ac_id=' + r.data[i].ac_id;
                                        }
                                        $cmitem.find('a').attr('href', link);
                                        $cmitem.find('a').attr('ac_id', r.data[i].ac_id);
                                        $cmitem.find('a').addClass('ac_dcs_acid');
                                        $cmitem.find('img').attr('src', r.data[i].imgsrc);
                                        $cmitem.find('.jz_img').attr('data-original', r.data[i].imgsrc);
                                        $cmitem.find('.jz_img').attr('alt', r.data[i].picname);
                                        if (r.data[i].price) {
                                            $cmitem.find('.fontTahoma').html(r.data[i].price);
                                            $cmitem.find('.jz_fy').html('元');
                                        } else {
                                            $cmitem.find('.fontTahoma').hide();
                                            $cmitem.find('.jz_fy').hide();
                                        }
                                        $cmitem.find('.title_sy').html(r.data[i].title).css({
                                            "overflow": "hidden",
                                            "white-space": "nowrap",
                                            "text-overflow": "ellipsis",
                                            "width": "200px",
                                            "display": "block"
                                        });
                                        $cmitem.find('.title_sy').attr('title', r.data[i].title);
                                        $cmitem.find('.alt_sy').html(r.data[i].alt).css({
                                            "overflow": "hidden",
                                            "white-space": "nowrap",
                                            "text-overflow": "ellipsis",
                                            "width": "200px",
                                            "display": "block"
                                        });
                                        $cmitem.find('.alt_tit').attr('title', r.data[i].alt);
                                    }
                                } else {
                                    $.dcstracker({'event': 'HOMEPC_JZSJ_SB'});
                                }
                            }
                        })
                    }
                }
            }

        });


        ;
        $(function () {

            $(window).scroll(function () {
                if (sTop >= 0) {
                    if (isIE6()) {
                        var wheight = $(window).height;
                        var sTop = $(window).scrollTop();
                        var h = parseInt(wheight + sTop);
                        $('.lowerIEtips').stop().animate({marginTop: h}, 1).show();
                    }
                }
            }).scroll();

        });


        ;
        $(function () {
            $(".cart_list").mCustomScrollbar();
        });


        $(document).ready(function () {
            var timer = null;
            $('.rfn_9').hover(function () {
                clearTimeout(timer);
                $(".rightfloatbox .dorpdown-layer").show();
                // __hover_get_cart();
                //$.pub("hover_get_cart");
            }, function () {
                timer = setTimeout(function () {
                    $('.rfn_9').removeClass('hover');
                    $(".rightfloatbox .dorpdown-layer").hide();
                }, 100);
            });
            $('.rightfloatbox .dorpdown-layer').hover(function () {
                clearTimeout(timer);
                $('.rfn_9').addClass('hover');
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    $('.rfn_9').removeClass('hover');
                    $(".rightfloatbox .dorpdown-layer").hide();
                }, 100);
            });

            $
                .sub('click_footer_sdc', __footer_sdc)
            ;

            function __footer_sdc() {
                var $t = $(this);
                $.dcstracker({
                    action: 'footer_fast_link',
                    event: $t.attr('dcs')
                });
            };
        });


    }, 'utf-8');
</script>


<div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
    <div class="xl-chrome-ext-bar__logo"></div>

    <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
    <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
</div>
</body>
</html>