<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0113)https://pay.shop.10086.cn/paygwsharding/415984075962525703-1598407597059-7e290fe083ce808439a80aa046e0d36a-11.html -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="WT.cg_n" content="Pay">
    <meta name="WT.tx_i" content="415984075962525703">

    <link rel="stylesheet" type="text/css" href="${IMAGE_SERVER}cloud/static/submit_order/css/style.css">
    <link rel="shortcut icon" type="image/x-icon"
          href="https://pay.shop.10086.cn/paygwsharding/resources/images/favicon.ico">
    <style type="text/css">
        .bankList li input {
            margin-top: -9px;
            left: 8px;
        }

        .bankList li img {
            margin-left: 28px;
        }

        .i {
            background-color: #fefaf1;
        }

        .description {
            border-top: 1px dashed #999;
            padding: 20px 0 10px 3px;
            margin-top: 20px;
        }

        .description h2 {
            font-weight: bold;
            line-height: 24px;
        }

        .description .title_box {
            position: relative;;
        }

        .description .title_box h2 {
            width: 300px;
        }

        .description .title_box .right {
            position: absolute;
            right: 310px;
            top: 5px;
        }

        .description .paymethod {
            padding-bottom: 15px;
        }

        .description .paymethod a.blue, .orderbox a.blue {
            color: #0085d0;
        }

        .description table {
            border: 1px solid #e3e3e3;
        }

        .description table th, .description table td {
            border: 1px solid #e3e3e3;
            text-align: center;
            line-height: 26px;
        }

        .description table th {
            font-weight: bold;
            line-height: 30px;
            background-color: #f5f5f5;
        }

        .hebaotips {
            margin: 10px;
            color: #0085d0;
            font-weight: bold
        }

        .tips {
            position: absolute;
            left: 0px;
            top: 0px;
            color: #dc292d;
            background-color: #fff9f1;
            border: 1px solid #fcf5e2;
            line-height: 24px;
            padding: 0 10px;
        }

        .weixin_new {
            display: block;
            width: 40px;
            height: 25px;
            z-index: 9999;
            position: absolute;
            top: -12px;
            right: -10px;
            _right: -4px;
            right: 0 \9;
            background: url(/paygwsharding/resources/images/weixin_pay.png) no-repeat center top;
        }

        .orderSuccess {
            padding: 17px 90px 40px 45px;
        }

        .wx_sao {
            float: right;
        }

        .tabsChange ul li {
            _z-index: 8
        }

        .tabsChange ul li {
            _width: 120px;
        }

        .tabsChange ul li a {
            _width: 120px;
            _text-align: center;
            _padding-left: 0;
            _padding-right: 0;
        }

        .more_box {
            display: none;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: url(/paygwsharding/resources/images/meng_bg.png) repeat;
            z-index: 99999;
        }

        .myhlist {
            overflow-y: scroll;
            height: 200px;
            position: relative;
        }

        .more_yh {
            width: 700px;
            height: 300px;
            position: absolute;
            top: 50%;
            left: 50%;
            margin-top: -170px;
            margin-left: -380px;
            background: #fff;
            padding: 20px 30px;
        }

        .more_yh h1 {
            font-size: 16px;
            font-weight: normal;
            padding-bottom: 10px;
            border-bottom: 2px solid #B3B3B3;
            margin-bottom: 10px;
            color: #919191;
        }

        .more_yh h1 a {
            float: right;
            width: 30px;
            text-align: right;
            cursor: pointer;
        }

        .more_yh p {
            display: inline-block;
            float: right;
            margin-top: 20px;
        }

        .more_yh p input {
            height: 30px;
            padding: 0 20px;
            border: 1px solid #ccc;
            border-radius: 3px;
            color: #fff;
            background: #A4A4A4;
            cursor: pointer;
            border: none \9;
            outline: none \9;
            outline: medium;
        }

        .more_yh p input[type="submit"] {
            background: #FF7D01;
        }

        .more_yh ul {
            clear: both;
            position: absolute;
            top: 0;
            left: 0;
            overflow: hidden;
        }

        .Bank_xx li {
            width: 33%;
        }

        .bluePageTitle li a {
            padding-left: 35px \9;
            padding-right: 33px \9;
        }

        .bluePageTitle {
            clear: both \9;
        }

        .load_jz {
            position: relative;
            width: 100%;
            height: auto;
            background: #fff;
            padding: 10px 0;
        }

        .load_jz img {
            display: block;
            margin: 0 auto;
        }

        .alignright {
            margin-top: 60px;
        }

        .moreBank {
            background: none;
        }

        .orderbox {
            border: none;
        }

        .orderSuccess {
            border-left: 1px solid #dadada;
            border-right: 1px solid #dadada;
        }

        .orderM {
            border: 1px solid #dadada;
            border-top: none;
        }

        .moreIndent {
            padding: 17px 90px 40px 45px;
            border: 1px solid #dadada;
            background: #fff;
            line-height: 30px;
            position: relative;
            top: -1px;
            margin-bottom: 20px;
        }

        .moreIndent .odsuc {
            position: absolute;
            left: 0;
            top: 3px;
            display: inline-block;;
            width: 30px;
            height: 20px;
            background: url(/paygwsharding/resources/images/du_t1.png) no-repeat center;
            background-size: 100%;
        }

        .moreIndent .odY {
            margin-left: 36px;
        }

        .moreIndent .green {
            color: #008000;
        }

        .moreIndent .red {
            color: #f00;
        }

        .moreIndent .gray {
            color: #666;
        }

        .moreIndent .sizeY {
            font-size: 16px;
        }

        .moreIndent .moreWb {
            border: 1px solid #dadada;
            width: 720px;
            padding: 0 16px;
            margin: 16px 0 10px;
            color: #333;
        }


        .moreIndent .qrcode {
            width: 120px;
            position: absolute;
            right: 20px;
            top: 26px;
        }

        .moreIndent .qr-img {
            width: 120px;
            height: 120px;
        }

        .moreIndent .qrcode img {
            width: 120px;
            display: block;
            position: absolute;
            right: 0;
            top: 0;
        }

        .moreIndent .qrcode .wx_sa {
            text-align: center;
            line-height: 20px;
            width: 100%;
        }

        .morePaytype {
            display: block;
            width: 150px;
            height: 39px;
            line-height: 38px;
            text-align: center;
            color: #0a78c7;
            cursor: pointer;
            margin-left: 20px;
            border: 1px dashed #cfcfcf;
            font-size: 14px;
            background: none;
            clear: both;
        }
    </style>
    <title>中国移动-移动商城-支付</title>
    <!--[if lt IE 9]>
    <script r='m'>document.createElement("section")</script><![endif]--></head>
<body style="">


<div class="globalMain minHeader clearfix">
    <div id="top_close" class="top_info" style="display: none">
        <a onclick="$(&#39;#top_close&#39;).hide()" title="关闭提示" class="info_close" href="javascript:void(0)">关闭&nbsp;
            <img src="${IMAGE_SERVER}cloud/static/submit_order/images/bg_close.jpg" width="12"
                 height="12">
        </a>
        <p id="topinfo">尊敬的客户：目前建设银行、招商银行、交通银行暂不支持信用卡支付。</p>
    </div>
    <a href="http://www.10086.cn/" class="logo floatleft">
        <img src="${IMAGE_SERVER}cloud/static/submit_order/images/logo.png">
    </a>

</div>

<div class="content">

    <ul class="payStep clearfix totalfour">
        <li class="current">1.商品选择<i class="first"></i></li>
        <li class="current">2.填写核对订单信息<i></i></li>
        <li class="current">3.提交订单<i></i></li>
        <li>4.支付结果信息<i></i></li>
    </ul>

    <div class="orderbox">

        <div class="orderSuccess">
            <p class="position size14">
                <i class="odsuc"></i>
                <span class="green bold">订单已于</span>
                <span class="red bold">${orderTimeStr}</span>
                <span class="green bold">提交成功，请您尽快付款！</span>
                <span>订单号：${order.orderNum}</span>&nbsp;&nbsp;|&nbsp;&nbsp;应付金额：
                <span class="bold red fontYaHei">￥${order.orderSum}</span> 元
            </p>

            <p class="gray">
                请您在提交订单后<span class="orange">24小时</span>内完成支付，否则订单会自动取消。
            </p>
            <p class="gray">
                <a href="https://pay.shop.10086.cn/paygwsharding/bank.jsp" class="blue" target="_blank">点击查看银行支付限额</a>
            </p>
        </div>

        <div class="bluePageTitle noBorderTop clearfix tabsChange">
            <ul class="clearfix">
                <li class="current">
                    <a name="AccountPay" href="javascript:void(0)" onclick="return accountPay()">平台支付</a>
                    <span class="weixin_new" style="z-index: 9;"></span>
                </li>
                <li><a name="BankPay" href="javascript:void(0)" onclick="return bankPay()">银行支付</a></li>
            </ul>
        </div>

        <form id="payment" action="https://pay.shop.10086.cn/paygwsharding/mobileAndBankPay" method="post"
              target="_blank">
            <div class="orderMain tabsItem" style="display: block;">
                <ul class="bankList clearfix pay-list">
                    <li class="list-item hbzf" style="display: list-item;">
                        <label>
                            <input type="radio" name="bankAbbr" value="MBP">
                            <img src="${IMAGE_SERVER}cloud/static/submit_order/images/sj.gif">
                        </label>
                    </li>
                    <li class="list-item ylzf" style="display: list-item;">
                        <label>
                            <input type="radio" name="bankAbbr" value="UNIPAY">
                            <img src="${IMAGE_SERVER}cloud/static/submit_order/images/unionpay.gif">
                        </label>
                    </li>
                    <li class="list-item zfbzf" style="display: list-item;">
                        <label>
                            <input type="radio" name="bankAbbr" value="ALIPAY">
                            <img src="${IMAGE_SERVER}cloud/static/submit_order/images/alipay.jpg">
                        </label>
                    </li>
                    <li class="list-item wxzf" style="display: list-item;">
                        <label>
                            <input type="radio" name="bankAbbr" value="WXPAY">
                            <img src="${IMAGE_SERVER}cloud/static/submit_order/images/WXPAY.png">
                        </label>
                    </li>
                </ul>
                <input type="hidden" name="orderId" value="415984075962525703">
                <input type="hidden" name="type" value="S">
                <input type="hidden" name="ipAddress" value="123.172.72.244">
                <input type="hidden" name="ts" value="1598407597059">
                <input type="hidden" name="hmac" value="74bca4c50f177d95f9c28fcfaf260ff0">
                <input type="hidden" name="channelId" value="11">
                <p class="alignright margin20" style="margin-right: 20px; margin-bottom: 20px;">
                    <input type="image" name="ConfirmPay" src="${IMAGE_SERVER}cloud/static/submit_order/images/b_pay.png"
                           onclick="return Regular(this)">
                </p>
            </div>
        </form>
        <!--pay shouji over-->
        <form id="payment" action="https://pay.shop.10086.cn/paygwsharding/mobileAndBankPay" method="post"
              target="_blank">
            <div class="orderMain tabsItem" style="display: none;">
                <div class="load_jz" style="display: none;">
                    <img src="${IMAGE_SERVER}cloud/static/submit_order/images/loading2.gif">
                </div>
                <ul class="bankList bankBorder clearfix" id="historybank" style="display: none">
                </ul>
                <ul class="bankList bankGroup clearfix" id="bigbank">
                </ul>
                <ul class="bankList bankGroup clearfix" id="districtbank">
                    <li class="morePay"><span name="MorePay" class="moreBank" style="display: none">更多银行</span></li>
                </ul>

                <input type="hidden" name="orderId" value="415984075962525703">
                <input type="hidden" name="type" value="S"> <input type="hidden" name="ipAddress"
                                                                   value="123.172.72.244"> <input type="hidden"
                                                                                                  name="ts"
                                                                                                  value="1598407597059">
                <input type="hidden" name="hmac" value="74bca4c50f177d95f9c28fcfaf260ff0"> <input type="hidden"
                                                                                                  name="channelId"
                                                                                                  value="11">
                <p class="alignright margin20" style="margin-right: 20px; margin-bottom: 20px;">
                    <input type="image" name="ConfirmPay"
                           src="${IMAGE_SERVER}cloud/static/submit_order/images/b_pay.png"
                           onclick="return Regular(this)">
                </p>
            </div>
        </form>
        <form id="payment" action="https://pay.shop.10086.cn/paygwsharding/mobileAndBankPay" method="post"
              target="_blank">
            <div class="more_box">
                <div class="more_yh">
                    <h1>
                        <a class="s_gb">×</a>请选择银行
                    </h1>
                    <div class="myhlist">
                        <ul class="bankList bankGroup clearfix Bank_xx" id="morebank">
                        </ul>
                    </div>
                    <input type="hidden" name="orderId" value="415984075962525703">
                    <input type="hidden" name="type" value="S"> <input type="hidden" name="ipAddress"
                                                                       value="123.172.72.244"> <input type="hidden"
                                                                                                      name="ts"
                                                                                                      value="1598407597059">
                    <input type="hidden" name="hmac" value="74bca4c50f177d95f9c28fcfaf260ff0"> <input type="hidden"
                                                                                                      name="channelId"
                                                                                                      value="11">
                    <p class="alignright margin20">
                        <input type="button" name="cxz" value="返回" class="s_gb"> <input type="submit" name="ConfirmPay"
                                                                                        onclick="return Regular(this)"
                                                                                        value="确认支付">
                    </p>
                </div>
            </div>
        </form>


        <form id="payment" action="https://pay.shop.10086.cn/paygwsharding/mobileAndBankPay" method="post"
              target="_blank">
            <div class="orderMain tabsItem creditcard">
                <div class="tips" style="display: none;"></div>
                <ul class="bankList clearfix creditcard_list">


                    <div></div>

                    <li><label> <input type="radio" value="CCB" name="bankAbbr" class="show_desc"
                                       url="/paygwsharding/jsp/queryRates.jsp?bankAbbr=CCB">

                        </label> <img src="${IMAGE_SERVER}cloud/static/submit_order/images/CCB.gif">
                    </li>


                    <div></div>

                    <li><label> <input type="radio" value="ICBC" name="bankAbbr" class="show_desc"
                                       url="/paygwsharding/jsp/queryRates.jsp?bankAbbr=ICBC">

                        </label> <img src="${IMAGE_SERVER}cloud/static/submit_order/images/ICBC.gif">
                    </li>


                    <div></div>

                    <li><label> <input type="radio" value="CMB" name="bankAbbr" class="show_desc"
                                       url="/paygwsharding/jsp/queryRates.jsp?bankAbbr=CMB">

                        </label> <img src="${IMAGE_SERVER}cloud/static/submit_order/images/CMB.gif">
                    </li>


                    <div></div>

                    <li><label> <input type="radio" value="CEBB" name="bankAbbr" class="show_desc"
                                       url="/paygwsharding/jsp/queryRates.jsp?bankAbbr=CEBB">

                        </label> <img src="${IMAGE_SERVER}cloud/static/submit_order/images/CEBB.gif">
                    </li>


                    <div></div>

                    <li><label> <input type="radio" value="CMBC" name="bankAbbr" class="show_desc"
                                       url="/paygwsharding/jsp/queryRates.jsp?bankAbbr=CMBC">

                        </label> <img src="${IMAGE_SERVER}cloud/static/submit_order/images/CMBC.gif">
                    </li>


                </ul>
                <div class="description_box">

                </div>
                <input type="hidden" name="orderId" value="415984075962525703">
                <input type="hidden" name="type" value="S"> <input type="hidden" name="ipAddress"
                                                                   value="123.172.72.244"> <input type="hidden"
                                                                                                  name="ts"
                                                                                                  value="1598407597059">
                <input type="hidden" name="hmac" value="74bca4c50f177d95f9c28fcfaf260ff0"> <input type="hidden"
                                                                                                  name="channelId"
                                                                                                  value="11"> <input
                        type="hidden" name="isInstallment" value="1">
                <p class="alignright margin20" style="margin-right: 20px; margin-bottom: 20px;">
                    <input type="image" name="ConfirmPay"
                           src="${IMAGE_SERVER}cloud/static/submit_order/images/b_pay.png"
                           onclick="return Regular(this)">
                </p>
            </div>
        </form>

    </div>

    <#include "../common/footer.ftlh">

    <div class="popbox"
         style="width: 440px; margin-left: -220px; left: 50%; top: 50%; margin-top: -100px; display: none;" id="popPay">
        <div class="popTitle clearfix">
            <span>支付</span><a class="iconClose popClose" href="javascript:void(0)" onclick="return flshpage()">关闭</a>
        </div>
        <div class="popMain">
            <p class="aligncenter">请在新打开的网银页面进行支付，支付完成前不要关闭该窗口哦</p>
            <br>
            <p class="aligncenter">
                <a href="https://pay.shop.10086.cn/paygwsharding/fnpay/415984075962525703-11.html"
                   class="ywczf margin20"></a>&nbsp;&nbsp;&nbsp;
                <a href="javascript:void(0);" class="cxxzyh margin20" onclick="return flshpage()"></a>
            </p>
        </div>
    </div>
    <div class="mask" id="mask" style="z-index: 99;"></div>
    <div class="qrcodearea" id="wxArea">
        <a id="wxAreaCloser" href="javascript:void(0)" class="close">关闭</a>
        <dt></dt>
        <dd></dd>
    </div>
    <div class="popbox" id="wxDisableArea"
         style="width: 440px; margin-left: -220px; left: 50%; top: 50%; margin-top: -100px; display: none;">
        <div class="popTitle clearfix">
            <span>温馨提示</span>
            <a class="iconClose popClose" href="javascript:void(0)" onclick="return flshpage()">关闭</a>
        </div>
        <div class="popMain">
            <p class="aligncenter" style="padding: 20px;line-height:150%;font-size:20px">微信支付仅限登录用户使用
                <br>如需微信支付请登录后 <a href="https://shop.10086.cn/i/?f=rechargecredit&c=00&e=99"
                                  class="blue">重新下单</a></p>
        </div>
    </div>
</div>
<script src="${IMAGE_SERVER}cloud/static/submit_order/js/jquery.js"></script>
<script src="${IMAGE_SERVER}cloud/static/submit_order/js/sdc_mall.js"></script>
<script type="text/javascript">


    var sdcaction = {
        'Account': 'AccountPay',
        'Bank': 'BankPay',
        'ConfirmPay': 'CheckInfo_ConfirmPay',
        'BankPay': 'PayInfo_BankPay',
        'AccountPay': 'PayInfo_AccountPay'
    };


    $(function () {
        $('.tabsChange li').click(function () {
            var $this = $(this);
            var clickIndex = $('.tabsChange li').index($this);
            $this.addClass('current').siblings('li').removeClass('current');
            $('.tabsItem').hide().eq(clickIndex).show();
        });

        if ($('.bankGroup li').length > +2) {
            $('.morePay').show();
        }

        $('.moreBank').bind('click', function () {
            var his = $(document.body).height();
            $(".more_box").css("height", his);
            $('.more_box').show();
            if (window._tag) {
                _tag.dcsMultiTrack('WT.event', 'MorePay', 'dcsuri', '/nopv.gif');
            }
        });
        $('.morePaytype').bind('click', function () {
            $(this).closest('li').hide();
            $(this).closest('li').prev().show();
        });
        $('.s_gb').click(function () {
            $('.more_box').hide();
        });

        $('.popClose, .ywczf, .cxxzyh').click(function () {
            $('#popPay').hide();
            $('#mask').hide();
        });

        $('.bankList').on('click', 'li img', function () {
            $('input[type="radio"]', this.parentNode).click();
        });
        $('.creditcard_list input[name=bankAbbr]:disabled').closest('li').hover(function () {
            var $t = $(this);
            var position = $t.offset(),
                top = position.top,
                left = position.left;
            $t.closest('ul').prev().html('<img src="/paygwsharding/resources/images/icon_banktips.jpg" align="absmiddle">&nbsp;&nbsp;' + $t.find('.tips_text').text()).css({
                'top': (top + 40),
                'left': (left + 28)
            }).show();
        }, function () {
            var $t = $(this);
            $t.closest('ul').prev().html('').css({'top': '0', 'left': '0'}).hide();
        });
        $('.creditcard_list').on('click', '.show_desc', function () {
            //http://pay.shop.staff.139.com/paygw/jsp/queryRates.jsp?bankAbbr=

            //$('.creditcard_list').children('li').bind('click','.show_desc',function(){
            var url = $(this).attr('url');

            $.post(url, function (resq) {
                $('.creditcard .description_box').html(resq);
                //   		var r = {code: resq.substr(0,1),msg: resq.substr(2)};
                //   		if(r.code){alert(r.msg)}else{
                //   			$('.creditcard .description_box').html(r.msg);
                //   		}
            });
        });

    });

    function Regular(btn) {
        var $v = $(btn.form).find('[name="bankAbbr"]:checked');
        var tag = false;
        var bank = null;

        if ($v.length > 0) {
            tag = true;
            bank = $v.eq(0).val();
        }

        if (!tag) {
            alert("请选择支付方式");
            return false;
        }
        $('#popPay').show();
        $('.more_box').hide();
        $('#mask').height($(document).height() > $(window).height() ? $(document).height() : $(window).height()).show();

        if (typeof (_tag) != "undefined") {
            _tag.dcsMultiTrack('WT.category', 415984075962525703 + "_" + 11, 'WT.event', 'CheckInfo_ConfirmPay', 'DCS.dcsuri', '/nopv.gif');
        }
        if ('WXPAY' == bank) {
            showWxQrcode(btn);
            return false;
        } else {
            return tag;
        }
    }

    function flshpage() {
        window.location.reload();
    }

    //储蓄卡+信用卡
    var ajaxstatus;

    function bankPay() {
        if (window._tag) {
            _tag.dcsMultiTrack('WT.event', sdcaction.Bank, 'dcsuri', '/nopv.gif');
        }
        if (typeof (_tag) != "undefined") {
            _tag.dcsMultiTrack('WT.category', "415984075962525703_11", 'WT.event', sdcaction.BankPay, 'DCS.dcsuri', '/nopv.gif');
            var userId = '1255491269' + "";
            var phoneNum = '13504410153' + "";
            if ($('#districtbank').find('li').length == 1 && ($('#morebank').find('li').length == 0)) {
                $('.load_jz').show();
                if (ajaxstatus != null && ajaxstatus != "") {
                    if (ajaxstatus.state() === 'pending') {
                        return false;
                    }
                } else {
                    ajaxstatus = $.ajax({
                        type: "POST",
                        url: "/paygwsharding/getRecommendPayBankAjax",
                        dataType: "JSON",
                        data: {
                            "userId": userId,
                            "phoneNum": phoneNum,
                            "timestamp": new Date().getTime()
                        },
                        success: function (data) {
                            $('.load_jz').hide();
                            if (data == null) {
                                alert("查询失败，请重试");
                            } else {
                                var historyli = "";
                                for (var key in data.historybank) {
                                    historyli = historyli + "<li><label> <input type='radio' name='bankAbbr' value=" + key + " /> <img src='/paygwsharding/resources/images/bank/" + key + ".gif' /></label></li>";
                                    $('#historybank').css("display", "block");
                                }
                                if (historyli != "") {
                                    $('#historybank').append(historyli);
                                }

                                var bigli = "";
                                for (var key in data.bigbank) {
                                    bigli = bigli + "<li><label> <input type='radio' name='bankAbbr' value=" + key + " /> <img src='/paygwsharding/resources/images/bank/" + key + ".gif' /></label></li>";
                                }
                                $('#bigbank').append(bigli);

                                var districtli = "";
                                for (var key in data.districtbank) {
                                    districtli = districtli + "<li><label> <input type='radio' name='bankAbbr' value=" + key + " /> <img src='/paygwsharding/resources/images/bank/" + key + ".gif' /></label></li>";
                                }
                                $('#districtbank').prepend(districtli);

                                var moreli = "";
                                //$('#morebank li').remove();
                                for (var key in data.morebank) {
                                    moreli = moreli + "<li><label> <input type='radio' name='bankAbbr' value=" + key + " /> <img src='/paygwsharding/resources/images/bank/" + key + ".gif' /></label></li>";
                                }
                                $('#morebank').append(moreli);

                                $('.moreBank').css("display", "block");
                            }
                        },
                        error: function (data) {
                            alert('查询失败，请重试');
                        }
                    });
                }
            }
        }
    }

    function creditcardPay() {
        if (window._tag) {
            _tag.dcsMultiTrack('WT.event', sdcaction.Bank, 'dcsuri', '/nopv.gif');
        }
        if (typeof (_tag) != "undefined") {
            _tag.dcsMultiTrack('WT.category', "415984075962525703_11", 'WT.event', sdcaction.BankPay, 'DCS.dcsuri', '/nopv.gif');
        }
    }

    //和包帐户
    function accountPay() {
        if (window._tag) {
            _tag.dcsMultiTrack('WT.event', sdcaction.Account, 'dcsuri', '/nopv.gif');
        }
        if (typeof (_tag) != "undefined") {
            _tag.dcsMultiTrack('WT.category', "415984075962525703_11", 'WT.event', sdcaction.AccountPay, 'DCS.dcsuri', '/nopv.gif');
        }
    }

    //微信支付
    function showWxQrcode(btn) {
        var $form = $(btn.form);
        $.ajax({
            url: '/paygwsharding/mobileAndBankPayAjax',
            async: false,
            data: $form.serialize(),
            success: function (r) {
                if (r.code) {
                    alert(r.msg)
                } else {
                    if (r.type == 'qrcode') {
                        $('#wxArea').show();
                        $('#wxArea dt').html('<img src="' + r.url + '" />');
                        timeJs(r.url);
                    } else if (r.type == 'redirect') {
                        location.href = r.url;
                    }
                }
            },
            dataType: 'json',
            error: function (r) {
                alert('支付失败，请重试');
                //$('#wxArea').show();
                //$('#wxArea dt').html('<img src="'+$('.orderSuccess .qrcode').attr('src')+'" />');
            }
        });
    }

    function showWXDisable() {
        $('#wxDisableArea').show();
        $('#mask').show();
    }

    function timeJs(imgurl) {
        setTimeout(function () {
            $('#wxArea dt').html('<img src="/paygwsharding/resources/images/qrcodeexpire.jpg" />').find('img').click(function () {
                $('#wxArea dt').html('<img src="' + imgurl + '&_=' + Math.random() + '" />');
                timeJs(imgurl);
            });
        }, 90 * 1000);
    }

    var wxTimer = setInterval(function () {
        $.ajax({
            url: "/paygwsharding/WXafterpayeBack?orderId=415984075962525703",
            success: function (r) {
                if (r) {
                    location.href = r;
                }
            },
            cache: false
        });
    }, 10 * 1000);


    $('#wxAreaCloser').click(function () {
        $('#wxArea').hide();
    });

    function isIE6() {
        return ("undefined" == typeof (document.body.style.maxHeight))
    };
    if (isIE6()) {
        var s_width = window.screen.width;
        $('.mask').css('width', s_width);
    }
    ;
    $(function () {
        //var config = "YYYY";
        //var config = $("PAYCONF-PC").val();
        var config = 'YYYY';
        if (config.charAt(0) == "Y") {
            $('.pay-list .hbzf').css("display", "list-item");
        }
        if (config.charAt(1) == "Y") {
            $('.pay-list .ylzf').css("display", "list-item");
        }
        if (config.charAt(2) == "Y") {
            $('.pay-list .zfbzf').css("display", "list-item");
        }
        if (config.charAt(3) == "Y") {
            $('.pay-list .wxzf').css("display", "list-item");
        }
    });
</script>
    <img src="${IMAGE_SERVER}cloud/static/submit_order/images/dcs.gif">
    <div class="clear"></div>

    <div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
        <div class="xl-chrome-ext-bar__logo"></div>
        <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
        <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
    </div>
    <img src="${IMAGE_SERVER}cloud/static/submit_order/images/dcs(1).gif">
</body>
</html>