<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0085)https://shop.10086.cn/order/checkorder.php?cart_code=565dc78d1fd497a2c5c237063103a94a -->
<html xmlns="http://www.w3.org/1999/xhtml" class="">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/x-icon" href="https://img0.shop.10086.cn/favicon.ico__0.ico">
    <meta name="WT.location" content="431">
    <meta name="WT.uid" content="94506241b4c84b5ba3a6b6857e7e9f2b">
    <meta name="WT.category" content="checkorder_0">
    <meta name="WT.goodslist" content="70000_1012520_1067526_0">
    <title>【中国移动】完善订单_移动商城</title>
    <link href="${IMAGE_SERVER}cloud/static/create_order/css/quan_list.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script r='m'>document.createElement("section")</script><![endif]-->
    <script charset="utf-8" src="${IMAGE_SERVER}cloud/static/create_order/js/checkorder.v2.js"></script>
    <meta name="WT.mobile" content="58384-29011-5018-20545">
</head>
<body style="">

<#include "../common/script_screenResize.ftlh">

<#include "../common/topNav.ftlh">

<iframe src="${IMAGE_SERVER}cloud/static/create_order/【中国移动】完善订单_移动商城_files/saved_resource.html"
        id="ssocheckframe" style="display:none"></iframe>
<#include "../common/script_allcity.ftlh">

<div class="globalMain clearfix" id="header">

    <div class="search_mlogo clearfix">

        <#include "../common/logoWhere.ftlh">

        <!--[if IE]>
        <style>
            /*#header .search .txt{padding-top:6px;}*/
        </style>
        <![endif]-->
        <div class="search">
            <form class="clearfix" action="https://search.10086.cn/shop/list" autocomplete="off" method="get"
                  target="_blank">
                <input id="skeywords" type="text" name="key" autocomplete="off" disableautocomplete="" class="txt"
                       onfocus=" this.style.color = '#333333'" onblur=" this.style.color ='#ccc'">
                <ul id="searchKeyWord1598406464228" class="search_toplist" style="display: none;"></ul>
                <ul id="searchHistory1598406464228" class="search_toplist" style="display: none;"></ul>
                <input type="submit" class="b" value="">
                <input type="hidden" class="txt" name="province_id" value="431">
                <input type="hidden" class="txt" name="city_id" value="431">
                <input type="hidden" class="txt" name="from" value="10603">
                <script type="text/javascript">window.searchDomain = "https://search.10086.cn/";</script>
            </form>
            <ul id="hotsearch" class="floatleft search_hotlist clearfix">
                <li><a target="_blank" dcs_id="MALL_RCSS_1_5G正式商用" type="" class="search_red ac_dcs_base"
                       href="http://www.10086.cn/5Gplus/?WT.ac=hot_search_010_1_5G%E6%AD%A3%E5%BC%8F%E5%95%86%E7%94%A8">5G正式商用</a>
                </li>
                <li><a target="_blank" dcs_id="MALL_RCSS_2_信用购机" type="" class="search_red ac_dcs_base"
                       href="https://shop.10086.cn/list/101_431_431_1_0_0_0_0_0_1_0.html?WT.ac=hot_search_010_2_%E4%BF%A1%E7%94%A8%E8%B4%AD%E6%9C%BA">信用购机</a>
                </li>
                <li><a target="_blank" dcs_id="MALL_RCSS_3_积分兑换" type="" class="search_red ac_dcs_base"
                       href="https://search.10086.cn/shop/list?key=%E7%A7%AF%E5%88%86%E5%85%91%E6%8D%A2&provinceId=431&cityId=431&WT.ac=hot_search_010_3_%E7%A7%AF%E5%88%86%E5%85%91%E6%8D%A2&from=10602">积分兑换</a>
                </li>
                <li><a target="_blank" dcs_id="MALL_RCSS_4_华为P30" type="" class="search_red ac_dcs_base"
                       href="https://search.10086.cn/shop/list?key=%E5%8D%8E%E4%B8%BAP30&provinceId=431&cityId=431&WT.ac=hot_search_010_4_%E5%8D%8E%E4%B8%BAP30&from=10602">华为P30</a>
                </li>
                <li><a target="_blank" dcs_id="MALL_RCSS_5_4G流量卡" type="" class="search_blue ac_dcs_base"
                       href="https://search.10086.cn/shop/list?key=4G%E6%B5%81%E9%87%8F%E5%8D%A1&provinceId=431&cityId=431&WT.ac=hot_search_010_5_4G%E6%B5%81%E9%87%8F%E5%8D%A1&from=10602">4G流量卡</a>
                </li>
                <li><a target="_blank" dcs_id="MALL_RCSS_6_服务密码" type="" class="search_red ac_dcs_base"
                       href="https://search.10086.cn/shop/list?key=%E6%9C%8D%E5%8A%A1%E5%AF%86%E7%A0%81&provinceId=431&cityId=431&WT.ac=hot_search_010_6_%E6%9C%8D%E5%8A%A1%E5%AF%86%E7%A0%81&from=10602">服务密码</a>
                </li>
            </ul>

        </div>
    </div>

    <#assign topMenuNav="shop">
    <#include "../common/topMenuNav.ftlh">

</div>
<div class="globalMain clearfix">
    <ul class="payStep clearfix totalfour broad_no">
        <li class="current">1.商品选择<i class="first"></i></li>
        <li class="current">2.填写核对订单信息<i></i></li>
        <li>3.提交订单<i></i></li>
        <li>4.支付结果信息<i></i></li>
    </ul>
</div>

<div class="globalMain clearfix broad" style="display:none">
    <ul class="payStep clearfix totalfour">
        <li class="current">1.宽带信息填写<i class="first"></i></li>
        <li class="current">2.订单信息核对<i></i></li>
        <li>3.订单提交支付<i></i></li>
        <li>4.支付结果信息<i></i></li>
    </ul>
</div>


<div class="header_area_template" style="display:none;">
    <!-- <li style="height:24px;overflow:hidden;"><a href="javascript:void(0)" class="ac_city_choose" location="{province_id}_{city_id}" title="{city_name}">{city_name}</a></li> --> </div>

<div class="content">

    <div class="globalGrayBorder noBorderTop">
        <div class="clearfix grayTitle">
            <span class="marginR20">收货人信息 </span>
            <a href="javascript:void(0)" class="btn btnSmall btnGreen ac_address_add_new" style="display: none;"
               srv="/ajax/order/addrform.json">+ 新增地址<i></i><b></b></a>
        </div>
        <#--收货地址表单-->
        <div class="globalForm orderMain address" id="address_list">
            <ul class="btnChoose withhover">

                <#list shipAddrList as addr>
                    <li address_id="${addr.shipAddrId}" name="addrli"
                        <#if addr.defaultAddr == 1>
                        class="position current default"
                        </#if>
                        shipName="${addr.shipName}" province="${addr.province}" city="${addr.city}" district="${addr.district}"
                        zipCode="${addr.zipCode}" addr="${addr.addr}" phone="${addr.phone}"
                    >
                        <span class="default_address">默认地址</span>
                        <a href="javascript:void(0)" class="selectblue floatleft name selectShipAddr" title="${addr.shipName}">${addr.shipName}</a>
                        <span class="location floatleft position ellipsis street" title="${addr.addr}">${addr.addr}</span>
                        <label class="phone">
                            <span>${addr.phone}</span>
                        </label>
                        <span class="address_operation floatright">
                            <a href="javascript:void(0)" class="blue marginR20 default_action">设为默认地址</a>
                            <a href="javascript:void(0)" class="blue marginR20 editAddr">编辑</a>
                            <a href="javascript:void(0)" class="blue marginR20 deleteAddr">删除</a>
					    </span>
                    </li>
                </#list>

                <script type="text/javascript">
                    // 地址点击选择
                    $('.selectShipAddr').click(function () {
                        $(this).parent().parent().find('li').removeClass('current');
                        $(this).parent().addClass('current');
                        let $li = $(this).parent();
                        $('input[name=addressId]').val($li.attr('addressId'));
                        $('input[name=shipName]').val($li.attr('shipName'));
                        $('input[name=province]').val($li.attr('province'));
                        $('input[name=city]').val($li.attr('city'));
                        $('input[name=district]').val($li.attr('district'));
                        $('input[name=zipCode]').val($li.attr('zipCode'));
                        $('input[name=addr]').val($li.attr('addr'));
                        $('input[name=phone]').val($li.attr('phone'));
                        $('.summary_area p[class=address] span').text($li.attr('addr'));
                        $('.summary_area p[class=user] span').text($li.attr('shipName'));
                    });
                    // 设置默认
                    $('.default_action').click(function () {
                        let $this = $(this).parent().parent();
                        let shipAddrId = $this.attr('address_id');
                        layer.confirm('设为默认收货地址?', {icon: 3}, function(index) {
                            request('member/ship-addr/default/' + shipAddrId, {}, 'post').then(res => {
                                $.alert("成功");
                                // 默认样式
                                $this.parent().find('li span[class=default_address]').hide();
                                $this.find('span[class=default_address]').show();
                                // 激活
                                $this.parent().find('li').removeClass('current', 'position', 'default');
                                $this.addClass('current', 'position', 'default');
                                layer.close(index);
                            }).catch(err => {
                                $.alert(err.msg)
                            })
                        });
                    });
                    // 删除
                    $('.deleteAddr').click(function () {
                        let $this = $(this).parent().parent();
                        let shipAddrId = $this.attr('address_id');
                        layer.confirm('确认删除?', {icon: 3}, function(index) {
                            request('member/ship-addr/' + shipAddrId, {}, 'delete').then(res => {
                                $.alert("成功删除");
                                $this.unbind('click');
                                $this.remove();
                                layer.close(index);
                            }).catch(err => {
                                $.alert(err.msg)
                            })
                        });
                    });
                    // 编辑
                    $('.editAddr').click(function () {
                        let shipAddrId = $(this).parent().parent().attr('address_id');
                        request('member/ship-addr/' + shipAddrId, {}, 'get').then(res => {
                            let field = res.data;
                            showEditShipAddrForm(field);
                        }).catch(err => {
                            $.alert(err.msg);
                        })
                    });

                    // 显示
                    function showEditShipAddrForm(field) {
                        if (field) {
                            $('#address_content_form input[name=shipAddrId]').val(field.shipAddrId);
                            $('#address_content_form input[name=shipName]').val(field.shipName);
                            $('#address_content_form input[name=procince]').val(field.procince);
                            $('#address_content_form input[name=city]').val(field.city);
                            $('#address_content_form input[name=district]').val(field.district);
                            $('#address_content_form input[name=zipCode]').val(field.zipCode);
                            $('#address_content_form input[name=addr]').val(field.addr);
                            $('#address_content_form input[name=phone]').val(field.phone);
                            $('#address_content_form input[name=defaultAddr]').prop({checked: field.defaultAddr == 1});
                            $('#address_content_form input[name=fixedPhone]').val(field.fixedPhone);
                        }
                        $('#address_content_form').show();
                    }
                    // 关闭
                    function closeEditShipAddrForm() {
                        $('#address_content_form').hide();
                    }

                </script>
                <!--
                <form method="post" action="https://shop.10086.cn/ajax/order/addaddr.json"
                      class="addressform address_add" onsubmit="return false" style="width:100%;display: none;">
                    <input type="hidden" name="cart_code" value="565dc78d1fd497a2c5c237063103a94a">
                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;收货人：</dt>
                        <dd><input type="text" maxlength="50" class="txt-normal" name="rename" value=""
                                   placeholder="请输入收货人姓名">&nbsp;&nbsp;<span class="red rename_tips"></span></dd>
                    </dl>

                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;所在地：</dt>
                        <dd class="sheng position">
                            <span class="sheng_show ac_location_show">请选择省/市/区</span>
                            <a href="javascript:void(0);" class="toggle  ac_location_show"></a>
                            <div class="select_sheng noBorderTop" style="display:none">
                                <input type="hidden" name="province" value="">
                                <input type="hidden" name="city" value="">
                                <input type="hidden" name="town" value="">
                                <div class="sheng_tag">
                                    <a href="javascript:;" class="current ac_location_tag" depth="0">省份</a>
                                    <a href="javascript:;" class="ac_location_tag" depth="1">城市</a>
                                    <a href="javascript:;" class="noBorderRight ac_location_tag" depth="2">区县</a>
                                    <div class="clear"></div>
                                </div>
                                <div class="sheng_con clearfix">
                                    <div class="region_list" depth="0">
                                        <div class="clearfix">
                                            <div class="sort">A-G</div>
                                            <div class="sort_list">
                                                <a region_id="100" class="ac_location_region" href="javascript:void(0)">北京</a>
                                                <a region_id="551" class="ac_location_region" href="javascript:void(0)">安徽</a>
                                                <a region_id="230" class="ac_location_region" href="javascript:void(0)">重庆</a>
                                                <a region_id="591" class="ac_location_region" href="javascript:void(0)">福建</a>
                                                <a region_id="200" class="ac_location_region" href="javascript:void(0)">广东</a>
                                                <a region_id="771" class="ac_location_region" href="javascript:void(0)">广西</a>
                                                <a region_id="931" class="ac_location_region" href="javascript:void(0)">甘肃</a>
                                                <a region_id="851" class="ac_location_region" href="javascript:void(0)">贵州</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">H-J</div>
                                            <div class="sort_list">
                                                <a region_id="311" class="ac_location_region" href="javascript:void(0)">河北</a>
                                                <a region_id="371" class="ac_location_region" href="javascript:void(0)">河南</a>
                                                <a region_id="898" class="ac_location_region" href="javascript:void(0)">海南</a>
                                                <a region_id="270" class="ac_location_region" href="javascript:void(0)">湖北</a>
                                                <a region_id="731" class="ac_location_region" href="javascript:void(0)">湖南</a>
                                                <a region_id="451" class="ac_location_region" href="javascript:void(0)">黑龙江</a>
                                                <a region_id="431" class="ac_location_region" href="javascript:void(0)">吉林</a>
                                                <a region_id="250" class="ac_location_region" href="javascript:void(0)">江苏</a>
                                                <a region_id="791" class="ac_location_region" href="javascript:void(0)">江西</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">L-S</div>
                                            <div class="sort_list">
                                                <a region_id="240" class="ac_location_region" href="javascript:void(0)">辽宁</a>
                                                <a region_id="471" class="ac_location_region" href="javascript:void(0)">内蒙古</a>
                                                <a region_id="951" class="ac_location_region" href="javascript:void(0)">宁夏</a>
                                                <a region_id="971" class="ac_location_region" href="javascript:void(0)">青海</a>
                                                <a region_id="210" class="ac_location_region" href="javascript:void(0)">上海</a>
                                                <a region_id="280" class="ac_location_region" href="javascript:void(0)">四川</a>
                                                <a region_id="531" class="ac_location_region" href="javascript:void(0)">山东</a>
                                                <a region_id="351" class="ac_location_region" href="javascript:void(0)">山西</a>
                                                <a region_id="290" class="ac_location_region" href="javascript:void(0)">陕西</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">T-Z</div>
                                            <div class="sort_list">
                                                <a region_id="220" class="ac_location_region" href="javascript:void(0)">天津</a>
                                                <a region_id="991" class="ac_location_region" href="javascript:void(0)">新疆</a>
                                                <a region_id="891" class="ac_location_region" href="javascript:void(0)">西藏</a>
                                                <a region_id="871" class="ac_location_region" href="javascript:void(0)">云南</a>
                                                <a region_id="571" class="ac_location_region" href="javascript:void(0)">浙江</a>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="region_list" depth="1">
                                    </div>
                                    <div class="region_list" depth="2">
                                    </div>
                                </div>
                            </div>
                        </dd>
                    </dl>

                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;详细地址：</dt>
                        <dd><input type="text" class="txt-normal xxlarge" maxlength="150" name="addr" value=""
                                   placeholder="请填写详细地址">&nbsp;&nbsp;<span class="red addr_tips"></span></dd>
                    </dl>
                    <dl class="clearfix">
                        <dt><i class="red bold"></i>邮政编码：</dt>
                        <dd><input type="text" class="txt-normal" name="postcode" value=""></dd>
                    </dl>
                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;手机号：</dt>
                        <dd><input type="text" class="txt-normal txt-small" name="mobile"
                                   value="">&nbsp;&nbsp;或固定电话：<input type="text" class="txt-normal  txt-small"
                                                                     name="tel" value="" placeholder="例如:010-12345678">&nbsp;&nbsp;<span
                                    class="red num_tips"></span></dd>
                    </dl>
                    <dl class="clearfix">
                        <dt>&nbsp;</dt>
                        <dd><label><input class="checkbox" type="checkbox" name="default_address" value="1">
                                设为默认地址</label></dd>
                    </dl>
                    <input id="res" name="res" type="reset" style="display:none;">
                    <button class="btn b-default ac_submit_addr" type="submit" style="margin-left: 255px;">
                        <span>确定</span></button>
                    <button class="btn b-default ac_submit_cancel" type="reset" style="margin-left: 70px;">
                        <span>取消</span></button>
                </form>
                -->

            </ul>
            <p class="address_morearea margin10" style="display:none">
                <a href="javascript:void(0)" class="blue addressmore ac_address_more">更多地址</a>
                <a href="javascript:void(0)" srv="/ajax/order/viewaddr.json" class="blue addressup ac_address_less"
                   style="display:none">收起地址</a>
            </p>
        </div>
        <div class="globalForm orderMain address_add_content" style="display: none;" id="address_content_form">
            <ul class="btnChoose withhover">

                <form method="post" action="ajax/order/addaddr.json"
                      class="addressform address_add" onsubmit="return false" style="width:100%;">
                    <input type="hidden" name="shipAddrId" value="">
                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;收货人：</dt>
                        <dd>
                            <input type="text" maxlength="50" class="txt-normal" name="shipName" value=""
                                   placeholder="请输入收货人姓名">&nbsp;&nbsp;<span class="red rename_tips"></span></dd>
                    </dl>

                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;所在地：</dt>
                        <dd class="sheng position">
                            <span class="sheng_show ac_location_show">请选择省/市/区</span>
                            <a href="javascript:void(0);" class="toggle  ac_location_show"></a>
                            <div class="select_sheng noBorderTop" style="display:none">
                                <input type="hidden" name="province" value="">
                                <input type="hidden" name="city" value="">
                                <input type="hidden" name="town" value="">
                                <div class="sheng_tag">
                                    <a href="javascript:;" class="current ac_location_tag" depth="0">省份</a>
                                    <a href="javascript:;" class="ac_location_tag" depth="1">城市</a>
                                    <a href="javascript:;" class="noBorderRight ac_location_tag" depth="2">区县</a>
                                    <div class="clear"></div>
                                </div>
                                <div class="sheng_con clearfix">
                                    <div class="region_list" depth="0">
                                        <div class="clearfix">
                                            <div class="sort">A-G</div>
                                            <div class="sort_list">
                                                <a region_id="100" class="ac_location_region" href="javascript:void(0)">北京</a>
                                                <a region_id="551" class="ac_location_region" href="javascript:void(0)">安徽</a>
                                                <a region_id="230" class="ac_location_region" href="javascript:void(0)">重庆</a>
                                                <a region_id="591" class="ac_location_region" href="javascript:void(0)">福建</a>
                                                <a region_id="200" class="ac_location_region" href="javascript:void(0)">广东</a>
                                                <a region_id="771" class="ac_location_region" href="javascript:void(0)">广西</a>
                                                <a region_id="931" class="ac_location_region" href="javascript:void(0)">甘肃</a>
                                                <a region_id="851" class="ac_location_region" href="javascript:void(0)">贵州</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">H-J</div>
                                            <div class="sort_list">
                                                <a region_id="311" class="ac_location_region" href="javascript:void(0)">河北</a>
                                                <a region_id="371" class="ac_location_region" href="javascript:void(0)">河南</a>
                                                <a region_id="898" class="ac_location_region" href="javascript:void(0)">海南</a>
                                                <a region_id="270" class="ac_location_region" href="javascript:void(0)">湖北</a>
                                                <a region_id="731" class="ac_location_region" href="javascript:void(0)">湖南</a>
                                                <a region_id="451" class="ac_location_region" href="javascript:void(0)">黑龙江</a>
                                                <a region_id="431" class="ac_location_region" href="javascript:void(0)">吉林</a>
                                                <a region_id="250" class="ac_location_region" href="javascript:void(0)">江苏</a>
                                                <a region_id="791" class="ac_location_region" href="javascript:void(0)">江西</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">L-S</div>
                                            <div class="sort_list">
                                                <a region_id="240" class="ac_location_region" href="javascript:void(0)">辽宁</a>
                                                <a region_id="471" class="ac_location_region" href="javascript:void(0)">内蒙古</a>
                                                <a region_id="951" class="ac_location_region" href="javascript:void(0)">宁夏</a>
                                                <a region_id="971" class="ac_location_region" href="javascript:void(0)">青海</a>
                                                <a region_id="210" class="ac_location_region" href="javascript:void(0)">上海</a>
                                                <a region_id="280" class="ac_location_region" href="javascript:void(0)">四川</a>
                                                <a region_id="531" class="ac_location_region" href="javascript:void(0)">山东</a>
                                                <a region_id="351" class="ac_location_region" href="javascript:void(0)">山西</a>
                                                <a region_id="290" class="ac_location_region" href="javascript:void(0)">陕西</a>
                                            </div>
                                        </div>
                                        <div class="clearfix">
                                            <div class="sort">T-Z</div>
                                            <div class="sort_list">
                                                <a region_id="220" class="ac_location_region" href="javascript:void(0)">天津</a>
                                                <a region_id="991" class="ac_location_region" href="javascript:void(0)">新疆</a>
                                                <a region_id="891" class="ac_location_region" href="javascript:void(0)">西藏</a>
                                                <a region_id="871" class="ac_location_region" href="javascript:void(0)">云南</a>
                                                <a region_id="571" class="ac_location_region" href="javascript:void(0)">浙江</a>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="region_list" depth="1">
                                    </div>
                                    <div class="region_list" depth="2">
                                    </div>
                                </div>
                            </div>
                        </dd>
                    </dl>

                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;详细地址：</dt>
                        <dd>
                            <input type="text" class="txt-normal xxlarge" maxlength="150" name="addr" value="" placeholder="请填写详细地址">&nbsp;&nbsp;
                            <span class="red addr_tips"></span>
                        </dd>
                    </dl>
                    <dl class="clearfix">
                        <dt><i class="red bold"></i>邮政编码：</dt>
                        <dd><input type="text" class="txt-normal" name="zipCode" value=""></dd>
                    </dl>
                    <dl class="clearfix">
                        <dt><i class="red bold">*</i>&nbsp;&nbsp;手机号：</dt>
                        <dd>
                            <input type="text" class="txt-normal txt-small" name="phone" value="">&nbsp;&nbsp;
                            或固定电话：<input type="text" class="txt-normal  txt-small" name="fixedPhone" value="" placeholder="例如:010-12345678">&nbsp;&nbsp;
                            <span class="red num_tips"></span>
                        </dd>
                    </dl>
                    <dl class="clearfix">
                        <dt>&nbsp;</dt>
                        <dd>
                            <label>
                                <input class="checkbox" type="checkbox" name="defaultAddr" value="1">设为默认地址
                            </label>
                        </dd>
                    </dl>
                    <input id="res" name="res" type="reset" style="display:none;">
                    <button class="btn b-default _submit_addr" type="submit" style="margin-left: 255px;">
                        <span>确定</span></button>
                    <button class="btn b-default" type="reset" onclick="closeEditShipAddrForm()" style="margin-left: 70px;">
                        <span>取消</span></button>
                </form>
            </ul>
        </div>
        <div class="globalForm orderMain">
            <p class="red margin15">
                注：该商品支持全国（港澳台地区除外）配送 </p>
        </div>
        <div class="grayTitle">付款方式</div>
        <div class="globalForm orderMain payment">
            <p class="margin20">
                <label class="marginRight20 current inlineblock">
                    <a href="javascript:;" pay_type="1" class="selectblue ac_pay_type">在线支付</a>
                </label>
            </p>
        </div>
        <div class="grayTitle">配送说明</div>
        <div class="globalForm orderMain">
            <p class="margin20 black">我们会尽快为您安排发货，请您收到货品后务必验货后再签收！</p>
            <p class="margin10 red"><em class="red">*</em> 如遇特殊天气、交通等各类因素影响时，订单有可能有延误现象，请您谅解！</p>
        </div>
        <div class="grayTitle">
            <span class="marginR20">发票 </span>
            <a href="javascript:void(0)" class="btn btnSmall btnGreen ac_invoice_add_new"
               srv="/ajax/order/receiptform.json">+ 新增单位发票<i></i><b></b></a>
            <span class="red">开单位抬头发票需填写纳税人识别号，以免影响报销</span></div>
        <div class="globalForm orderMain invoice position">
            <!-- 			<a href="javascript:;" class="invoicemore ac_address_more">更多发票</a>
			<a href="javascript:;" srv="/ajax/order/viewreceipt.json" class="invoicemore invoiceup ac_address_less " style="display:none">收起发票</a>
			 -->
            <!-- <ul class="withhover">
				<li invoice_id="personal" class="floatleft marginR20 position gs_invoice current">
	<a href="javascript:void(0)" srv="/ajax/order/selectreceipt.json" class="ac_invoice_select selectblue selectbluegs" title="个人">个人</a>
	</li>

<li class="floatleft marginR20 ">
	<a href="javascript:void(0)" class="ac_invoice_add inlineblock aligncenter"><em class="size14 fontSun" >+</em>&nbsp;新增单位发票</a>
</li>

			</ul>
			<script type="text/html" id="invoice_tmpl">
			<li class="edit_invoice position">
				<input type="text" name="invoice_content" value="{invoice_content}" invoice_id="{invoice_id}"/>
				<a href="javascript:void(0)" class="btn btnSmall btnBlue ac_invoice_save" srv="/ajax/order/{action}receipt.json">保存<b></b><i></i></a>
				<a href="javascript:void(0)" class="btn btnSmall btnGray ac_invoice_cancel">取消<b></b><i></i></a>
			</li>
			</script> -->
            <div style="clear:both"></div>
            <div class="globalForm address invoice">

                <p class="margin20">电子发票/纸质普通发票（具体商户可支持发票类型请参见个人中心订单详情页面）</p>
                <ul class="btnChoose withhover">
                    <li invoice_id="personal" invoice_type="1" tax_payer_id="" invoice_content="个人"
                        class="position current">
                        <span class="default_invoice">默认发票</span>
                        <a href="javascript:void(0)" srv="/ajax/order/selectreceipt.json"
                           class="ac_invoice_select_new selectblue floatleft name" title="个人">个人</a>
                    </li>


                </ul>
                <p class="invoice_morearea margin10" style="display:none">
                    <a href="javascript:void(0)" class="blue invoice_more ac_invoice_more_new">更多发票</a>
                    <a href="javascript:void(0)" srv="/ajax/order/viewreceipt.json"
                       class="blue invoiceup ac_invoice_less_new" style="display:none">收起发票</a>
                </p>

            </div>
            <div class="globalForm invoice_add_content" id="invoice_content_form" style="display: none;">
                <ul class="btnChoose withhover">
                </ul>
            </div>
            <p class="margin20">
                <span class="red">根据税务局文件，电子发票是税务局认可的有效购买凭证，具有售后维权的法律效力，也可以作为企业报销凭证。在客户完成收货七天后，客户可登录后自行下载打印。</span><br>
                温馨提示：发票开立的金额为实际支付金额（订单总金额扣除账户余额、购物卡、抵用券、优惠券、积分抵扣、返利等支付后的余额）。
            </p>

        </div>
        <div class="grayTitle">商品清单</div>

        <div class="cart-warp">

            <div class="cart-thead clearfix">
                <dl>
                    <dd class="t-goods  ">商品信息</dd>
                    <dd class="t-props">&nbsp;</dd>
                    <dd class="t-quantity">&nbsp;</dd>
                    <dd class="t-price">单价</dd>
                    <dd class="t-quantity">数量</dd>
                    <dd class="t-sum">小计</dd>
                </dl>
            </div>
            <div class="cart-main">
                <div class="cart-list ">
                    <div class="shop"><span>商家：终端公司</span><span>客服电话：400-1088-188</span></div>
                    <div class="cart-item-list globalGrayBorder ">
                        <#list cartList as cartItem>
                        <div class="item-list single ">
                            <div class="item-item">
                                <dl>
                                    <dd class="p-goods">
                                        <a href="./detail?skuId=${cartItem.skuId}" target="_blank" class="blue">
                                            <img src="${IMAGE_SERVER}${cartItem.skuImg}" class="floatleft imgBorder" width="50" height="50">
                                            【优惠购机】 ${cartItem.skuName} <span class="red"></span>
                                            <br>
                                            <span class="gray">绿色  64G</span>
                                        </a>
                                    </dd>
                                    <dd class="p-stocks">&nbsp;</dd>
                                    <#--单价-->
                                    <dd class="p-price ">¥ ${cartItem.price}</dd>
                                    <#--数量-->
                                    <dd class="p-quantity aligncenter">x${cartItem.quantity}</dd>
                                    <#--小计-->
                                    <dd class="p-sum bold">¥ ${cartItem.totalPrice}</dd>
                                </dl>
                            </div>
                        </div>
                        </#list>

                        <div class="item-footer">
                            <dl>
                                <dd class="f-txt">
                                    <em>订单备注：</em>
                                    <input type="text" name="notes" value="" class="txt-normal xxlarge" form="orderform" maxlength="400">
                                    注：选填，最多输入400个字符
                                </dd>
                            </dl>
                        </div>

                    </div>

                </div>
            </div>
        </div>


        <div class="quan_thead clearfix">
            <dl>
                <dt>优惠：</dt>
                <span id="quantips" style="width:200px;display:none">货到付款暂不支持使用优惠</span>
                <dd class="tag tag1 current">可用优惠 <span class="red">（0）</span></dd>
                <dd class="tag tag2">不可用优惠<span class="">（0）</span></dd>
            </dl>
        </div>
        <div class="quan_main clearfix">
            <ul class="con con1">
                <div style="max-height: 155px;overflow-y: scroll;">
                    <li>暂无可用优惠</li>
                </div>
            </ul>
            <ul class="con con2" style="display:none">
                <div style="max-height: 155px;overflow-y: scroll;">
                    <li>暂无不可用优惠</li>
                </div>
            </ul>
        </div>


    </div>
    <div class="globalMain  globalGrayBorder summary_cart alignright clearfix">
        <p>
            <span class=""><em class="red">${skuTotalQuantity}</em>件商品</span>
            <span class="s-name">总商品金额：</span>
            <span class="s-price total_price">¥ ${skuTotalPrice}</span>
        </p>
        <p><span class="s-name">优惠金额：</span><span class="s-price youhui_price">- ¥ 0.00</span></p>
        <p><span class="s-name">运费：</span><span class="s-price">¥ 0.00</span></p>
        <p><span class="s-name">应付：</span><span class="s-price real_price">¥ ${skuTotalPrice}</span></p>
    </div>

    <input type="hidden" name="if_address" value="0">
    <input type="hidden" name="if_invoice" value="1">
    <input type="hidden" name="if_delivery" value="">
    <form method="post" action="./submit_order" id="orderform">
        <#--收货地址id-->
        <input type="hidden" name="addressId" value="${defaultShipAddr.shipAddrId}">
        <input type="hidden" name="shipName" value="${defaultShipAddr.shipName}">
        <input type="hidden" name="province" value="${defaultShipAddr.province}">
        <input type="hidden" name="city" value="${defaultShipAddr.city}">
        <input type="hidden" name="district" value="${defaultShipAddr.district}">
        <input type="hidden" name="zipCode" value="${defaultShipAddr.zipCode}">
        <input type="hidden" name="addr" value="${defaultShipAddr.addr}">
        <input type="hidden" name="phone" value="${defaultShipAddr.phone}">

        <input type="hidden" name="invoice_id" value="personal">
        <#--支付方式-->
        <input type="hidden" name="pay_type" value="1">
        <input type="hidden" name="coupon_type" value="">
        <input type="hidden" name="ticket_no" value="">
        <input type="hidden" name="eticket_number_mall" value="">
        <#--购物车-->
        <input type="hidden" name="cartIdStr" value="${cartIds}">
        <br>
        <div class="summary_area">
            <p class="totalprice size14">应付金额：
                <span class="red size22 bold real_price"><em class="fontYaHei">¥ </em>${skuTotalPrice}</span>
            </p>
            <p></p>
            <p class="address">收货地址：&nbsp;<span>${defaultShipAddr.addr}</span></p>
            <p class="user">收件人：&nbsp;<span>${defaultShipAddr.shipName}</span></p>
        </div>
        <div class="alignright margin15">
            <a class="btn btnBig btnRed" id="submitOrder"><em>提交订单</em><b></b><i></i></a>
        </div>

    </form>
</div>

<style type="text/css">
    .lowerIEtips {
        display: none;
        _display: block;
        _position: absolute;
    }
</style>

<#include "../common/footerNav.ftlh">
<#include "../common/footer.ftlh">
<div class="mask" id="mask"></div>
<div class="lowerIEtips" style="position: fixed;_position: absolute;bottom:0px;display:none;_display:block;">
    <div class="tipcon"><span><img src="${IMAGE_SERVER}cloud/static/create_order/images/logo2.png__240.png"
                                   style="width: 160px; height: 29px;"></span>
        <p>您的浏览器版本过低，如果页面显示不正常，建议将浏览器升级到最新版本。</p><!-- <a class="close" id="closeTips"></a> --></div>
</div>

<script type="text/javascript">
    $('#submitOrder').click(function () {
        document.getElementById("orderform").submit();
    })
</script>

<script type="text/javascript" src="${IMAGE_SERVER}cloud/static/create_order/js/loader.js__357.js"></script>
<script src="${IMAGE_SERVER}cloud/static/create_order/js/sdc_mall.js__463.js"></script>
<script type="text/javascript">
    window.ENVOBJ = {
        "loc": {"province_id": 431, "city_id": 431},
        "loginurl": "https:\/\/login.10086.cn\/SSOCheck.action?channelID=12002&backUrl=https%3A%2F%2Fshop.10086.cn%2Forder%2Fcheckorder.php%3Fcart_code%3D565dc78d1fd497a2c5c237063103a94a%26forcelogin%3D1",
        "shipping_region": {"province": [-1], "city": [-1]},
        "cart_code": "565dc78d1fd497a2c5c237063103a94a"
    };
    LOADJS('//img0.shop.10086.cn/combo/__583/script/jquery-1.10.2.js__script/cookie/jquery.cookie.js__script/iprompt/jquery.iprompt.js__script/formater.js__script/pubsub/jquery.pubsub.js__script/interactive/jquery.interactive.js__script/jquery.lazyload.js__www/core/js/global.js__www/core/js/fav.js__www/core/js/dcs_tracker.js__www/mod/search/js/shop_jsonp_search.js__script/mousewheel/jquery.mousewheel.js__script/customscrollbar/jquery.mCustomScrollbar.js__script/form/jquery.form.v318.js__script/city/jquery.city.v1.js__script/validate/jquery.validate.js__script/placeholder/jquery.placeholder.js', function () {
//	$.domains = window.ENVOBJ.domains;


        ;
        $(function () {
            $(".cart_list").mCustomScrollbar();
        });


        ;
        $(function () {

            var timer = null;
            $('.cart').hover(function () {
                var is_cart = '';
                if (is_cart) return false;
                clearTimeout(timer);
                $(".rightMenu .dorpdown-layer").show();
                //__hover_get_cart();
                //$.pub("hover_get_cart");
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $(".rightMenu .dorpdown-layer").hide();
                }, 100);
            });
            $('.dorpdown-layer').hover(function () {
                list_lock = false;
                clearTimeout(timer);
                $('.cart').addClass('current');
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $('.rightMenu .dorpdown-layer').hide();
                }, 100);
            });


            $
                .sub('click_cartlist_delete', __cartlist_delete, false)
                .sub('cartlist_del', cartlist_del, false)
            ;

            function __cartlist_delete() {
                var $t = $(this);
                var cartcount = $t.closest('ul').attr('cartcount');
                $.getJSON('/ajax/cartshop/delete.json', {selected: $t.closest('li').attr('cartid')}, function (r) {
                    if (r.code) {
                        $.alert(r.msg);
                    } else {
                        $t.closest('li').remove();
                        $cart_list = $('.rightMenu .cart_list').find('li');
                        if ($cart_list.length > 5) {
                            $('.cart_list').addClass('height268');
                        } else {
                            $('.cart_list').removeClass('height268');
                        }
                        ;
                        $.pub('cartlist_del');
                    }
                    ;
                });
            }

            function cartlist_del() {
                var c_num = $('.cart .red').text();
                $('.have_goods .cartcount b,.rightMenu .cart .red,.rightfloatbox .cart-quan em').text(parseInt(c_num - 1));
                $('#returntop .cart-quan em').text(parseInt(c_num - 1));
                var total = 0;
                var $cart_list = $('.rightMenu .cart_list').find('li');
                $($cart_list).each(function () {
                    var $t = $(this);
                    total += parseInt($t.attr('num')) * parseInt($t.attr('price') * 100) || 0;
                });
                $('.have_goods .btm .red b').text((total / 100).toFixed(2));
                if (c_num && c_num - 1 != 0) {
                    $('.dorpdown-layer .nogoods').hide();
                    $('.dorpdown-layer .have_goods').show();
                } else {
                    $('.dorpdown-layer .nogoods').show();
                    $('.dorpdown-layer .have_goods').hide();
                }
                ;
            }
        });


        $(document).ready(function () {
            var timers = null;

            $(".cmccclient").hover(function () {
                clearTimeout(timers);
                var cmcc_left_1 = $('.cmccclient').position().left + 2;
                $('.ewm').css('left', cmcc_left_1);
                $('.ewm').show();
            }, function () {
                timers = setTimeout(function () {
                    $('.ewm').hide();
                }, 100);
            });
            $('.ewm').hover(function () {
                var cmcc_left_2 = $('.cmccclient').position().left + 2;
                clearTimeout(timers);
                $('.cmccclient').addClass('cmccclienthover');
                $(this).css('left', cmcc_left_2);
                $(this).show();
            }, function () {
                var $t = $(this);
                timers = setTimeout(function () {
                    $('.cmccclient').removeClass('cmccclienthover');
                    $t.hide();
                }, 100);
            });
        });


        window.initUser = function (r) {
            if (r.code == 0) {
                window.loginUser = r.data;
                var nickname = r.data.nick_name || r.data.user_name;
                var tmpnick = nickname.split('@')[0];
                var noread = (r.data.msg_remind || {}).noread || 0;
                var showeye = r.data.is_china_mobile ? '' : 'eye-hide'; // 互联网用户不显示眼睛
                var tmpstr =
                    '<span class="tel floatleft marginRight10" title="' + nickname + '">' + tmpnick + '</span><i class="floatleft marginRight10 icon_eye ' + showeye + ' ac_handle_mobile"></i>' +
                    '<span class="floatleft noticearea" >' +
                    ' <a href="https://shop.10086.cn/i/?f=mynews"  target="_blank" class="red floatleft">消息 ' + noread + '</a> </span>' +
                    '<a class="red bold" href="javascript:void(logout())" title="退出">[退 出]</a><em>|</em>';
                document.getElementById('userinfo').innerHTML = tmpstr;
                if ($.pub) {
                    $.pub('login_success', r.data);
                }
                // 当前登陆人插码 ,如果是手机号登录，写入手机号，否则清空
                if (_tag) {
                    if (r.data.is_china_mobile) {
                        _tag.setMobile(r.data.wtmobile);
                    } else {
                        _tag.setMobile();
                    }
                }
            } else if (r.code == 3) {
                $('#ssocheckframe').attr('src', r.data);
            } else {
                $.pub('user_not_login_after_query');
                $('.btnOnestepbuy').hide();
                // 当前登陆人插码 没登陆清空
                if (_tag) {
                    _tag.setMobile();
                }
            }
        }
        var userParam = {
            'province_id': '431',
            'city_id': '431'
        }
        $.getJSON('/ajax/user/userinfo.json', userParam, initUser);


        ;
        $(function () {
            var provinceId = "431";	//省区编码
            var cityId = "431";	//市区编码
            var charset = "utf-8";

            $("#skeywords").search({
                type: 1,
                maxResult: 10,
                provinceId: provinceId,
                cityId: cityId,
                tabType: 1,
                tabName: '',
                showDefaultWord: 1,
                showHotSearchWord: 1,
                charset: charset
            }).change(function () {
                $(this).siblings('[name="from"]').val('10601');
            });
        });


        $(function () {
            $('.shopSearch .mainmenu').hover(function () {
                $(this).addClass('hover');
            }, function () {
                $(this).removeClass('hover');
            });
            var dcs_map = {
                '101': 'Home_FirstScreen_PHONE',
                '140': 'Home_FirstScreen_EXPENSE',
                '146': 'Home_FirstScreen_VAS',
                '134': 'Home_FirstScreen_NUMBER',
                '128': 'Home_FirstScreen_ACCESORY',
                'jiaohuafei': 'Home_FirstScreen_HUAFEI',
                'home_firstscreen_grzx': 'Home_FirstScreen_PERSONALCENTER',
                'home_firstscreen_ad_1': 'Home_FirstScreen_AD_1',
                'home_firstscreen_ad_2': 'Home_FirstScreen_AD_2',
                'home_firstscreen_ad_3': 'Home_FirstScreen_AD_3',
                'home_firstscreen_ad_4': 'Home_FirstScreen_AD_4',
                'home_firstscreen_ljcz': 'Home_FirstScreen_RECHARGE',
                'home_firstscreen_hfcz': 'Home_FirstScreen_HF_RECHARGE',
                'home_firstscreen_llcz': 'Home_FirstScreen_LL_RECHARGE',
                'home_firstscreen_30': 'Home_FirstScreen_30',
                'home_firstscreen_50': 'Home_FirstScreen_50',
                'home_firstscreen_100': 'Home_FirstScreen_100',
                'home_firstscreen_200': 'Home_FirstScreen_200',
                'home_firstscreen_500': 'Home_FirstScreen_500'
            };
            $.sub('click_dcstracker_homefirstscreen', __dcstracker_homefirstscreen);

            function __dcstracker_homefirstscreen() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'FirstScreen',
                    event: dcs_map[$t.attr('dcs_id')] || $t.attr('dcs_id')
                });
            }
        });


        $(document).ready(function () {
            var timer = null;
            $('#nav .title').hover(function () {
                clearTimeout(timer);
                $(".spnav .smore").css('display', 'none');
                $(".spnav .goodsNav").show();
            }, function () {
                $(".spnav .smore").css('display', 'none');
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
            $(".spnav .goodsNav").hover(function () {
                clearTimeout(timer);
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
        });


        // $('.ac_dcs_base').not('.first .ac_dcs_base').mouseenter(function() {
        // 	$(this).css('border-top-color', '#0085D0');
        // 	$(this).closest('li').siblings().find('.ac_dcs_base').not('.shop_ini').css('border-top-color', '#EAEAEA');
        // }).eq(0).mouseenter();
        // $('.ac_dcs_base').not('.shop_ini').mouseout(function() {
        // 	$(this).css('border-top-color', '#EAEAEA');
        // })


        ;
        $(function () {
            $
                .sub('click_show_areabar', __show_areabar)
                .sub('click_show_city', __show_city)
                .sub('click_city_choose', __gotocity)
            ;

            //清除浮层
            function __clear_areabar() {
                $('#header').find('.area ul').hide();
            }

            //展开浮层
            function __show_areabar() {
                __clear_areabar();
                var $this = $(this);
                $this.next().show();
                return false;
            }

            function __gotocity(loc) {
                if (typeof loc != "string") {
                    loc = $(this).attr('location');
                }
                var locarray = loc.split('_');
                var pid = locarray[0], cid = locarray[1];
                var url = location.href;
                if (url.indexOf('/list/') > 0 || url.indexOf('/tags/') > 0) {
                    url = url.replace(/_\d{3}_\d{3,4}/i, "_" + loc);
                    setTimeout(function () {
                        location.href = url;
                    });
                } else {
                    setTimeout(function () {
                        location.href = "/mall_{loc}.html".replace("{loc}", loc);
                    });
                }
            }

            function getCityByProvince(province_id) {
                if (!window.allcity[province_id]) {
                    $.ajax({
                        async: false,
                        url: "/ajax/region/singleregion.json",
                        data: {province_id: province_id},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg)
                            } else {
                                window.allcity[province_id] = r.data || [];
                            }
                        },
                        dataType: 'json'
                    });
                }
                return window.allcity[province_id];
            }

            var $province = $('#header .province'),
                $city = $('#header .city'),
                current_province_id = $province.find('span').attr('province_id'),
                city_id = '431',
                reg = new RegExp('<!--|-->', 'g'),
                template = new Formater($('.header_area_template').html().replace(reg, '') || '<li><a href="#" target="_blank">{city_name}</a></li>'),
                city_name = '长春'
            ;

            //点击省下拉项展开市浮层
            function __show_city() {
                var $this = $(this),
                    province_id = $this.attr('province_id'),
                    tmp = ''
                ;
                if ($this.attr('iscity')) {
                    __gotocity(province_id + "_" + province_id);
                    return false;
                }
                var data = getCityByProvince(province_id);
                $city.find('span').text('请选择');
                //var cityAreaWidth = (data.length < 4) ? 40*(data.length + 1) + 5 : 245;//根据市的个数，判断外框宽度
                $.each(data, function (inx, item) {
                    tmp += template.exec(item);
                });
                __clear_areabar();
                $this.closest('ul').prev().attr('province_id', $this.attr('province_id')).text($this.text());
                $city.find('ul').html(tmp).show();
                return false;
            }

            //点击其他dom收起浮层
            $(document).bind('click.area', function (e) {
                if ($(e.target).closest('.area').length == 0) {
                    __clear_areabar();
                }
                if ($(e.target).closest('.fs_box').length === 0) {
                    $('.fs_box ul').hide();
                }
            });

        })
        ;


        ;
        $(function () {
            var _mobileFuzzy = mobileFuzzy();

            $
                .sub('login_success', _mobileFuzzy.loginSuccess)
                .sub('click_send_msgcode4eye', _mobileFuzzy.sendMsgCode, false)
                .sub('click_handle_mobile', _mobileFuzzy.handleMobile, false)
            ;

            mobileFuzzy.$sms_mobile = $('#smsContent');

            function mobileFuzzy() {
                var mobile = null, isLogin = false, isShow = 0;
                var time = 60;
                var timer;

                // 填写mobile，并切换小眼睛的显示与隐藏
                function _handleMobile() {
                    var $eye = $('.userinfo .icon_eye');
                    isLogin && $('.userinfo .tel').text(mobile).attr('title', mobile);
                    mobile && (isShow ? $eye.removeClass('eye-close') : $eye.addClass('eye-close'));
                }

                // 发送验证码倒计时
                function _timeCountDown() {
                    var $msg_code = $('.sms-content .msg-code');
                    if (time === 0) {
                        clearInterval(timer);
                        $msg_code.removeClass('btnGray').addClass('ac_send_msgcode4eye btnBlue').find('span').text("重发验证码");
                        time = 60;
                        return false;
                    }
                    $msg_code.removeClass('btnBlue ac_send_msgcode4eye').addClass('btnGray').find('span').text(time + "s后发送");
                    time--;
                }

                // 弹出短信验证框
                function _popSmsBox() {
                    $.confirm($('#smsContent').html(), {
                        direction: null,
                        align: null,
                        mask: true,
                        noCloser: false,
                        preButtons: true,
                        onLoad: function ($box) {
                            $box.find('.mobile').html(mobile)
                        },
                        onAccept: _submitCheck
                    });
                }

                // 校验短信验证码是否正确，并设置返回值中的mobile和小眼睛状态等
                function _submitCheck() {
                    var flag = false;
                    $.ajax({
                        url: '/ajax/shownumber/submitcheck.json',
                        data: {msg_verify: $('.sms-content input[name="msg_verify"]').val()},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else if (r.data) {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                                flag = true;
                            }
                        },
                        dataType: 'json',
                        async: false
                    });
                    return flag;
                }

                // 点击小眼睛，控制手机号是否模糊化
                function _queryStatus() {
                    if (!isLogin) return;
                    $.getJSON('/ajax/shownumber/shownumber.json', {is_show: isShow}, function (r) {
                        if (r.code) {
                            $.alert(r.msg);
                        } else if (r.data) {
                            if (r.data.need_frame) {  // 后台告诉是否需要弹出短验窗口，need_frame=1表示当前登录状态会话下已经短信未校验过
                                _popSmsBox();
                            } else {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                            }
                        }
                    });
                }

                return {
                    // 校验是否登录，并填写用户名
                    loginSuccess: function () {
                        var user = arguments[0] instanceof jQuery.Event ? arguments[1] : arguments[0];
                        var nickname = user.nick_name || user.user_name;
                        // 如果是手机号用户，则设置isShow
                        if (user.is_china_mobile) {
                            isShow = user.num_show;
                            mobile = nickname;
                            isLogin = true;
                            _handleMobile();
                        }
                    },
                    handleMobile: _queryStatus,
                    // 发送短信验证码
                    sendMsgCode: function () {
                        $.getJSON('/ajax/shownumber/msg_send.json', function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else {
                                timer = setInterval(_timeCountDown, 1000);
                            }
                        });
                    }
                }
            }
        });


        ;$(function () {
            $(".quan_thead .tag").click(function () {
                $(".quan_thead .tag").removeClass("current");
                $(this).addClass("current");
            });
            $(".quan_thead .tag1").click(function () {
                $(".quan_main .con1").show();
                $(".quan_main .con2").hide();

            });
            $(".quan_thead .tag2").click(function () {
                $(".quan_main .con2").show();
                $(".quan_main .con1").hide();

            });

            $
                .sub('click_use_coupon', __use_coupon, true)
                .sub('click_pay_type', __check_coupon_paytype, false)
            ;

            $('.ac_use_coupon').attr('checked', false);

            function __use_coupon() {
                var $t = $(this), ticket_no = $t.val(), cart_code = ENVOBJ.cart_code;
                var checked_status = $t.attr('checked');
                $t.attr('checked', 'checked').closest('li').siblings().find('.ac_use_coupon').attr('checked', false);
                if (checked_status == 'checked') {
                    $t.attr('checked', false);
                    ticket_no = '';
                } else {
                    ticket_no = $t.val();
                }
                ;
                $.post('/ajax/coupon/batchdetail.json', {ticket_no: ticket_no, cart_code: cart_code}, function (r) {
                    if (r.code && r.code == 16) {
                        $.alert(r.msg);
                        window.location.href = window.location.href;
                    } else if (r.code) {
                        $.alert(r.msg);
                    } else {
                        if ($("#orderform").length) {
                            $('#orderform input[name=ticket_no]').val(ticket_no);
                            $('.summary_cart .total_price').text('¥ ' + (r.data.sum / 100).toFixed(2));
                            $('.summary_cart .youhui_price').text('- ¥ ' + (r.data.reduce_price / 100).toFixed(2));
                            $('.summary_cart .real_price, .summary_area .real_price').text('¥ ' + (r.data.pay_price / 100).toFixed(2));
                        }
                    }
                    ;
                }, 'JSON');

            }

            function __check_coupon_paytype() {
                var flag = ($(this).attr('pay_type') == "1");
                $('input[name=ticket_no]:checked').click();
                $('input[name=ticket_no]:checked').attr('checked', false);
                $('.quan_main .con1 .ac_use_coupon , #orderform input[name=ticket_no]').prop('disabled', !flag);
                if (flag == false) {
                    $('.quan_thead dd').hide();
                    $('.quan_thead #quantips').show();
                    $('.quan_main').hide();
                } else {
                    $('.quan_thead dd').show();
                    $('.quan_thead #quantips').hide();
                    $('.quan_main').show();
                }
            }

            $('.ac_pay_type').eq(0).click();

            // function __check_coupon_paytype(){
            //        var flag = ($(this).attr('pay_type') == "1");
            //        $('.quan_main .con1 .ac_use_coupon , #orderform input[name=ticket_no]').prop('disabled' ,!flag);
            //        if(flag == false){
            //            $('input[name=ticket_no]:checked').click();
            //            $('input[name=ticket_no]:checked').attr('checked', false);
            //            $('.summary_cart .youhui_price').text('- ¥ 0.00');
            //            $('.summary_cart .real_price, .summary_area .real_price').text('¥ 4499.00');
            //            $('.quan_thead dd').hide();
            //            $('.quan_thead #quantips').show();
            //            $('.quan_main').hide();
            //        }else{
            //            $('.ac_use_coupon').eq(0).click();
            //            $('.quan_thead dd').show();
            //            $('.quan_thead #quantips').hide();
            //            $('.quan_main').show();
            //        }
            //    }


            // if(null) {
            //     $('.ac_use_coupon').eq(0).click();
            // }
        });


        ;$(function () {

            $.sub('order_address_selected', __osb_notice_show, false);

            function __osb_notice_show() {
                $('.osp_tip_div .tip_false').hide();//一键购地址提示语隐藏
                $('.osp_tip_div .tip_true').show();//一键购地址提示语展示
            }

            (function () {
                var maizen = $(".isMaiZen");
                maizen.each(function () {
                    var $this = $(this);
                    var maizen_item = $this.find(".ac_maizeng").not(':disabled').eq(0).click();
                })
            })();

        });


        ;
        $(function () {

            $(window).scroll(function () {
                if (sTop >= 0) {
                    if (isIE6()) {
                        var wheight = $(window).height;
                        var sTop = $(window).scrollTop();
                        var h = parseInt(wheight + sTop);
                        $('.lowerIEtips').stop().animate({marginTop: h}, 1).show();
                    }
                }
            }).scroll();

        });


    }, 'utf-8');
</script>


<div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
    <div class="xl-chrome-ext-bar__logo"></div>

    <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
    <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
</div>
</body>
</html>