<div id="footer">
    <p>
        <a href="http://www.10086.cn/aboutus/news/" target="_blank">新闻中心</a>
        | <a href="http://job.10086.cn/" target="_blank">诚聘英才</a>
        | <a href="http://b2b.10086.cn/" target="_blank">采购信息</a>
        | <a href="http://www.10086.cn/aboutus/hezuo/" target="_blank">企业合作</a>
        | <a href="http://www.10086.cn/web_notice/contact/" target="_blank">联系我们</a>
        | <a href="http://www.10086.cn/web_notice/navigation/" target="_blank">站点导航</a>
        | <a href="http://labs.chinamobile.com/" target="_blank">中国移动研究院</a>
        | <a href="http://www.cmdi.chinamobile.com/" target="_blank">中国移动设计院</a>
        | <a href="http://www.10086.cn/web_notice/links/" target="_blank">友情链接</a>
        | <a href="https://www.10086.cn/events/djcx/" class="red" style="color:#ed2668" target="_blank">打击传销</a>
    </p>
    <p>掌上营业厅：
        <a href="http://wap.10086.cn/" target="_blank">wap.10086.cn</a> 语音自助服务：10086 短信营业厅：10086
        <a href="http://www.10086.cn/support/service/channel/entity/" target="_blank">自助终端</a>
        <a href="http://www.10086.cn/support/service/channel/entity/" target="_blank">营业厅</a>
        <a href="http://www.10086.cn/cmccclient/index.htm" target="_blank">手机营业厅下载</a>
    </p>
    <p style="width:300px; margin:0 auto;" class="clearfix">
        <a target="_blank" class="floatleft" href="https://ss.knet.cn/verifyseal.dll">
            <img src="${IMAGE_SERVER}cloud/static/store/images/cnnic.png__0.png" align="absmiddle" oncontextmenu="return false;">
        </a>
        <span class="floatleft alignleft" style="padding-left:20px;">
			<a href="http://beian.miit.gov.cn/" target="_blank">
                <img src="${IMAGE_SERVER}cloud/static/store/images/gov.gif__0.gif" align="absmiddle">京ICP备05002571号
            </a>
            <br>　中国移动通信版权所有
		</span>
    </p>
</div>