<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0059)https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_0.html -->
<html xmlns="http://www.w3.org/1999/xhtml" class="">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/x-icon" href="https://img0.shop.10086.cn/favicon.ico__0.ico">
    <meta name="WT.location" content="771">
    <meta name="WT.category" content="101">
    <meta name="keywords" content="中国移动网上商城,手机,值得买,可靠,质量好,移动合约机,买手机送话费,4G手机,手机最新报价,苹果,华为,魅族">
    <meta name="description" content="中国移动网上商城,提供最新最全的移动合约机、4G手机,买手机送话费,安全可靠,100%正品保证,让您足不出户,享受便捷移动服务！">
    <title>买手机中国移动网上商城最可靠,合约机,买手机送话费,100%正品！_广西南宁_移动商城</title>
    <link href="${IMAGE_SERVER}cloud/static/list/px.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script r='m'>document.createElement("section")</script><![endif]-->
    <script charset="utf-8" src="${IMAGE_SERVER}cloud/static/list/jquery.placeholder.js"></script>
    <meta name="WT.mobile" content="">
</head>
<body style="">

<#include "../common/script_screenResize.ftlh">

<!--
<style>
.search{display:none}
</style>
-->
<script type="text/html" id="login_box">
    <div class="minloginbox loadingBlock clearfix" style="width:350px;">
        <iframe src="https://login.10086.cn/SSOCheck.action?channelID=12002&backUrl=https%3A%2F%2Fshop.10086.cn%2Fsso%2Fminilogincallback.php%3Faction%3Dforcelogin"
                width="350" height="400" allowTransparency="true" frameborder="0" scrolling="no"></iframe>
    </div>
</script>

<#include "../common/topNav.ftlh">

<iframe src="${IMAGE_SERVER}cloud/static/list/saved_resource.html" id="ssocheckframe"
        style="display:none" __idm_frm__="309"></iframe>
<#include "../common/script_allcity.ftlh">

<div class="globalMain clearfix" id="header">

    <div class="search_mlogo clearfix">

        <#include "../common/logoWhere.ftlh">

        <#include "../common/search.ftlh">
    </div>

    <#assign topMenuNav="shop">
    <#include "../common/topMenuNav.ftlh">

</div>


<div class="pageSite clearfix">

    <a id="0" href="https://shop.10086.cn/mall_771_771.html">移动商城 </a>
    <em>&gt;</em>
    买手机
</div>


<div class="header_area_template" style="display:none;">
    <!-- <li style="height:24px;overflow:hidden;"><a href="javascript:void(0)" class="ac_city_choose" location="{province_id}_{city_id}" title="{city_name}">{city_name}</a></li> --> </div>


<script type="text/html" id="smsContent">
    <div class="sms-content alignleft">
        <p class="margin10">请输入<span class="mobile"></span>收到的验证码</p>
        <p class="margin10"><input type="text" name="msg_verify" autocomplete="off" placeholder="请输入短信验证码"
                                   maxlength="11" class="txt-normal marginR10"/><a
                class="ac_send_msgcode4eye msg-code btn btnBlue btnSmall"><span>发送验证码</span><b></b><i></i></a></p>

        <p class="marginTop10 gray">温馨提示：为了您的账户安全，请在办理业务前进行身份认证。</p>
    </div>
</script>


<style type="text/css">
    body {
        position: relative;
    }

    .mask {
        position: absolute;
        z-index: 9999999999
    }

    .mask .bg {
        width: 1200px;
        margin: 0 auto;
        position: relative;
    }

    .w1k .mask .bg {
        width: 1000px;
        margin: 0 auto;
    }

    .mask .bg img.g {
        position: absolute;
        top: 562px;
        right: 74px;
        top: 566px \9;
    }

    .mask .bg a.bt {
        display: block;
        width: 108px;
        height: 45px;
        position: absolute;
        top: 847px;
        right: 537px;
        background: url(//img0.shop.10086.cn/www/iphone/iphone6s/yuyue/blank.png__147.png) 0 0 repeat;
    }

    .w1k .mask .bg img.g {
        top: 592px;
        left: 556px;
    }

    .w1k .mask .bg a.bt {
        top: 874px;
        right: 337px;
        background: url(//img0.shop.10086.cn/www/iphone/iphone6s/yuyue/blank.png__147.png) 0 0 repeat;
    }

    .banner {
        display: block;
        width: 100%;
        height: 200px;
        background: url(//img0.shop.10086.cn/www/list/css/lianghao-banner.jpg__594.jpg) 0 0 no-repeat;
    }

    .w1k .banner {
        background: url(//img0.shop.10086.cn/www/list/css/lianghao-banner-1k.jpg__594.jpg) 0 0 no-repeat;
    }
</style>
<div class="content clearfix position">

    <div class="sidebar floatleft">

        <div class="globalBorder sideItem marginBottom10">
            <h2 class="clearfix"><span class="name">热销产品</span></h2>
            <div class="sideGoods">
                <dl class="clearfix first">
                    <dt class="position">
                        <a title="新5G智享套餐（个人版）" dcs_id="phone_List_Hot_1" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1081790_1065693.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/th6dmzytuu7zwxeq_170x170.png"
                                alt="新5G智享套餐（个人版）"></a>
                    </dt>
                    <dd><a title="新5G智享套餐（个人版）" dcs_id="phone_List_Hot_1" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1081790_1065693.html">

                        <p>新5G智享套餐（个人版）</p>

                    </a></dd>
                    <dd class="size14 red">128元</dd>
                </dl>
                <dl class="clearfix">
                    <dt class="position">
                        <a title="新畅享套餐系列" dcs_id="phone_List_Hot_2" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1079216_1061262.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/thfhert6agutt9cgt_170x170.png"
                                alt="新畅享套餐系列"></a>
                    </dt>
                    <dd><a title="新畅享套餐系列" dcs_id="phone_List_Hot_2" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1079216_1061262.html">

                        <p>新畅享套餐系列</p>

                    </a></dd>
                    <dd class="size14 red">48元/月</dd>
                </dl>
                <dl class="clearfix">
                    <dt class="position">
                        <a title="流量日包" dcs_id="phone_List_Hot_3" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080870_1063691.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/th57bs66djdtt9dp8_170x170.png"
                                alt="流量日包"></a>
                    </dt>
                    <dd><a title="流量日包" dcs_id="phone_List_Hot_3" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080870_1063691.html">

                        <p>流量日包</p>

                    </a></dd>
                    <dd class="size14 red">3元</dd>
                </dl>
                <dl class="clearfix">
                    <dt class="position">
                        <a title="流量月包" dcs_id="phone_List_Hot_4" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1072626_1052012.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/tse5qsxpg7s4bh6p_170x170.png"
                                alt="流量月包"></a>
                    </dt>
                    <dd><a title="流量月包" dcs_id="phone_List_Hot_4" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1072626_1052012.html">

                        <p>流量月包</p>

                    </a></dd>
                    <dd class="size14 red">10元</dd>
                </dl>
                <dl class="clearfix">
                    <dt class="position">
                        <a title="流量季包" dcs_id="phone_List_Hot_5" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080931_1064919.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/th38ud4ng5zttqszc_170x170.png"
                                alt="流量季包"></a>
                    </dt>
                    <dd><a title="流量季包" dcs_id="phone_List_Hot_5" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080931_1064919.html">

                        <p>流量季包</p>

                    </a></dd>
                    <dd class="size14 red">30元/季度</dd>
                </dl>
                <dl class="clearfix">
                    <dt class="position">
                        <a title="流量小时包" dcs_id="phone_List_Hot_6" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080857_1063668.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/th5wfkkmjc3tt2uqt_170x170.png"
                                alt="流量小时包"></a>
                    </dt>
                    <dd><a title="流量小时包" dcs_id="phone_List_Hot_6" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1080857_1063668.html">

                        <p>流量小时包</p>

                    </a></dd>
                    <dd class="size14 red">2元</dd>
                </dl>
            </div>
        </div>

        <div class="marginBottom10">
            <a dcs_id="phone_List_AD_1" class="ac_dcstracker" target="_blank"
               href="http://shop.10086.cn/list/146_771_771_0_0_0_0.html" title=""><img
                    src="${IMAGE_SERVER}cloud/static/list/t6gbdtwedef3mmcd.png" style="width:220px;"
                    alt=""></a>
        </div>

    </div>


    <div class="maincolumn floatright">


        <div class="boutique globalBorder globalMargin noMarginTop">
            <h2 class="clearfix"><span class="name">精品推荐</span></h2>
            <ul class="clearfix ">
                <li>
                    <div class="position img">
                        <a title="【新品超值购】iPhone 12 64/128/256G" dcs_id="phone_List_JPTJ_1" class="ac_dcstracker"
                           target="_blank" href="https://shop.10086.cn/goods/771_771_1082982_1071935.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/ts7x7sdtttvpe9xdf_90x90.png"
                                alt="【新品超值购】iPhone 12 64/128/256G"></a>
                    </div>
                    <div class="body">
                        <div class="about">

                            <p><a title="【新品超值购】iPhone 12 64/128/256G" dcs_id="phone_List_JPTJ_1" class="ac_dcstracker"
                                  target="_blank" href="https://shop.10086.cn/goods/771_771_1082982_1071935.html">【新品超值购】iPhone
                                12 ...</a></p>
                            <p class="price red"><span class="fontYaHei">￥</span>5299</p>
                        </div>
                        <p class="btnBox">
                            <a dcs_id="phone_List_JPTJ_1" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1082982_1071935.html"
                               class="btn btnRed ac_dcstracker"><i></i><b></b><em>查看详情</em></a>
                        </p>
                    </div>
                </li>
                <li>
                    <div class="position img">
                        <a title="iPhone 12 Pro" dcs_id="phone_List_JPTJ_2" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1082983_1071896.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/tsaucdfyz7pfdaxa_90x90.png"
                                alt="iPhone 12 Pro"></a>
                    </div>
                    <div class="body">
                        <div class="about">

                            <p><a title="iPhone 12 Pro" dcs_id="phone_List_JPTJ_2" class="ac_dcstracker" target="_blank"
                                  href="https://shop.10086.cn/goods/771_771_1082983_1071896.html">iPhone 12 Pro</a></p>
                            <p class="price red"><span class="fontYaHei">￥</span>7999</p>
                        </div>
                        <p class="btnBox">
                            <a dcs_id="phone_List_JPTJ_2" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1082983_1071896.html"
                               class="btn btnRed ac_dcstracker"><i></i><b></b><em>查看详情</em></a>
                        </p>
                    </div>
                </li>
                <li>
                    <div class="position img">
                        <a title="Redmi Note10 Pro" dcs_id="phone_List_JPTJ_3" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1085184_1073255.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/tswr64pnu2r5xetus_90x90.png"
                                alt="Redmi Note10 Pro"></a>
                    </div>
                    <div class="body">
                        <div class="about">

                            <p><a title="Redmi Note10 Pro" dcs_id="phone_List_JPTJ_3" class="ac_dcstracker"
                                  target="_blank" href="https://shop.10086.cn/goods/771_771_1085184_1073255.html">Redmi
                                Note10 Pro</a></p>
                            <p class="price red"><span class="fontYaHei">￥</span>1749</p>
                        </div>
                        <p class="btnBox">
                            <a dcs_id="phone_List_JPTJ_3" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1085184_1073255.html"
                               class="btn btnRed ac_dcstracker"><i></i><b></b><em>查看详情</em></a>
                        </p>
                    </div>
                </li>
                <li class="w1khide">
                    <div class="position img">
                        <a title="OPPO Reno6" dcs_id="phone_List_JPTJ_4" class="ac_dcstracker" target="_blank"
                           href="https://shop.10086.cn/goods/771_771_1085241_1073389.html"><img
                                src="${IMAGE_SERVER}cloud/static/list/ts6wdnpvuaacnjqu_90x90.png"
                                alt="OPPO Reno6"></a>
                    </div>
                    <div class="body">
                        <div class="about">

                            <p><a title="OPPO Reno6" dcs_id="phone_List_JPTJ_4" class="ac_dcstracker" target="_blank"
                                  href="https://shop.10086.cn/goods/771_771_1085241_1073389.html">OPPO Reno6</a></p>
                            <p class="price red"><span class="fontYaHei">￥</span>2599</p>
                        </div>
                        <p class="btnBox">
                            <a dcs_id="phone_List_JPTJ_4" target="_blank"
                               href="https://shop.10086.cn/goods/771_771_1085241_1073389.html"
                               class="btn btnRed ac_dcstracker"><i></i><b></b><em>查看详情</em></a>
                        </p>
                    </div>
                </li>
            </ul>
        </div>


        <div class="globalBorder selectFilter marginBottom10">
            <h2 class="clearfix"><span class="name">商品筛选</span> <a
                    href="https://shop.10086.cn/list/101_771_771_0_0_0.html" class="floatright">重置筛选条件</a></h2>


            <dl class="clearfix noBorderTop" type="brand">
                <dt class="phone">热门品牌：
                    <span class="current">
                        <a class="ac_listsort_dcs" href="javascript:void(0);">全部</a
                    </span>
                </dt>
                <dd class="phone">
                    <ul cellpadding="0" cellspacing="0" class="pp pp_ht">
                        <#--品牌循环-->
                        <#list brandList as brand>
                        <li class="" index="${brand?index}">
                            <div>
                                <a title="${brand.brandName}" class="pic  ac_listsort_dcs" brandid="${brand.brandId?c}" href="javascript:void(0)">
                                    <img src="${IMAGE_SERVER}${brand.imgs}" alt="${brand.brandName}">${brand.brandName}
                                </a>
                            </div>
                        </li>
                        </#list>
                        <#--品牌循环-->
                        <li class="nopic hide w1khide" index="999">
                            <div>
                                <a title="" class="pic  ac_listsort_dcs" href="javascript:void(0)">brandName</a>
                            </div>
                        </li>
                    </ul>
                    <div class="button">
                        <a href="javascript:void(0)" class="more ac_more" style="display: inline;">更多 <img
                                src="${IMAGE_SERVER}cloud/static/list/icon_down.jpg__136.jpg"></a>
                        <a href="javascript:void(0)" class="up ac_up" style="display: none;">收起 <img
                                src="${IMAGE_SERVER}cloud/static/list/icon_up.jpg__136.jpg"></a>
                    </div>
                </dd>
            </dl>

            <#--价格-->
            <dl class="clearfix" type="price">
                <dt class="phone">价格区间：
                    <span class="current">
                        <a class="ac_listsort_dcs" href="javascript:void(0);">全部</a>
                    </span>
                </dt>
                <dd>
                    <ul class="clearfix">
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">0-299</a></li>
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">300-699</a></li>
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">700-999</a></li>
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">1000-1999</a></li>
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">2000-2999</a></li>
                        <li><a href="javascript:void(0);" class="ac_listsort_dcs">3000以上</a></li>
                    </ul>
                </dd>
            </dl>
            <#--价格-->

            <#--属性循环-->
            <#list featureList as feature>
            <dl class="clearfix" type="feature" featureId="${feature.featureId?c}">
                <dt class="phone">${feature.featureName}：
                    <span class="current">
                        <a class="ac_listsort_dcs" href="javascript:void(0)" featureid="${feature.featureId?c}" sv="">全部</a>
                    </span>
                </dt>
                <dd>
                    <ul class="clearfix">
                        <#list feature.selectValueList as sv>
                        <li>
                            <a href="javascript:void(0)" class="ac_listsort_dcs" featureid="${feature.featureId?c}" sv="${sv}">${sv}</a>
                        </li>
                        </#list>
                    </ul>
                </dd>
            </dl>
            </#list>
            <#--属性循环-->

        </div>

        <div class="marginBottom10 px clearfix">
            <dl class="clearfix floatleft" style="">

                <dt>排序：</dt>
                <dd class="current"><a href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_0.html"
                                       dcs_id="sortorder_comprehensive_default" class="ac_listsort_dcs no">综合排序</a></dd>
                <dd><a href="https://shop.10086.cn/list/101_771_771_1_3_0_0_0_0_0_0.html" dcs_id="sortorder_sales_down"
                       class="ac_listsort_dcs down">销量</a></dd>
                <dd><a href="https://shop.10086.cn/list/101_771_771_1_1_0_0_0_0_0_0.html"
                       dcs_id="sortorder_price_default" class="ac_listsort_dcs no">价格</a></dd>
                <!-- 显示有货start -->
                <dt style="margin-left:15px"><a dcs_id="sortorder_stock_default" class="ac_listsort_dcs show_stock "
                                                href="https://shop.10086.cn/list/101_771_771_1_0_1_0_0_0_0_0.html">仅显示有货</a>
                </dt>
                <!-- 显示有货end -->
                <!-- 支持营业厅自取start -->
                <!-- 支持营业厅自取end -->
            </dl>
            <ul class="append clearfix floatright">
                <li class="count">共101件商品</li>
                <li class="line">|</li>
                <li class="operate">
                    <span class="prev">上一页<b></b><i></i></span>
                    <a class="next" href="https://shop.10086.cn/list/101_771_771_2_0_0_0_0_0_0_0.html?p=2">下一页<b></b><i></i></a>
                </li>
            </ul>
        </div>


        <div class="goodsList">
            <ul class="clearfix withhover">

                <#--商品循环start-->
                <#list skuList as sku>
                <li class="">
                    <div class="body">
                        <p class="img">
                            <a target="_blank" href="./details?skuId=${sku.skuId?c}" title="【${sku.brand.brandName}】${sku.skuName!}">
                                <img alt="【${sku.brand.brandName}】${sku.skuName}" class="lazy"
                                     src="${IMAGE_SERVER}${sku.skuImg!}"
                                     data-original="${IMAGE_SERVER}${sku.skuImg!}" style="display: inline;"/>
                            </a>
                        </p>
                        <p class="price red"><em class="fontYaHei size14">￥</em>${sku.skuPrice!'99999999.99'}</p>
                        <p class="name" title="【${sku.brand.brandName}】${sku.skuName} 赠200元移动话费券（7.16-7.25购机） 承诺在网24个月信用购机方案总价0元起">
                            <a target="_blank" href="./details?skuId=${sku.skuId?c}">【${sku.brand.brandName}】${sku.skuName!}
                                <span class="red">赠200元移动话费券（7.16-7.25购机） 承诺在网24个月信用购机方案总价0元起</span>
                            </a>
                        </p>
                        <p class="marginTop10">
                            <a target="_blank" href="./details?skuId=${sku.skuId?c}"
                               class="btn btnSmall btnGray marginRight10"><i></i><b></b>立即购买</a>
                            <a href="javascript:void(0);" class="btn btnSmall btnGray"><i></i><b></b>
                                <span class="ac_fav_add" goods_id="${sku.skuId?c}" goods_type="70000">收藏</span>
                            </a>
                        </p>
                        <span class="brandlogo">
                            <img src="${IMAGE_SERVER}${sku.brand.imgs}">
                        </span>
                    </div>
                </li>
                </#list>
                <#--商品循环end-->

                <li>
                    <div class="body">
                        <p class="img"><a target="_blank"
                                          href="https://shop.10086.cn/goods/771_771_1082982_1071935.html"
                                          title="【信用购机】iPhone 12 5G手机"><img alt="【信用购机】iPhone 12 5G手机" class="lazy"
                                                                            src="${IMAGE_SERVER}cloud/static/list/ts7x7sdtttvpe9xdf_170x170.png"
                                                                            data-original="//img1.shop.10086.cn/goods/ts7x7sdtttvpe9xdf_170x170.png"
                                                                            style="display: inline;"></a></p>
                        <p class="price red"><em class="fontYaHei size14">￥</em>5299</p>
                        <p class="name"
                           title="【信用购机】iPhone 12 5G手机购机送200元话费（7.16-7.25期间），信用购机至高优惠4680元！承诺在网6个月购机优惠1000元"><a
                                target="_blank" href="https://shop.10086.cn/goods/771_771_1082982_1071935.html">【信用购机】iPhone
                            12 5G手机<span class="red">
                                            购机送200元话费（7.16-7.25期间），信用购机至高优惠4680元！承诺在网6个月购机优惠1000元
                                    </span></a></p>
                        <p class="marginTop10">
                            <a target="_blank" href="https://shop.10086.cn/goods/771_771_1082982_1071935.html"
                               class="btn btnSmall btnGray marginRight10"><i></i><b></b>立即购买</a><a
                                href="javascript:void(0);" class="btn btnSmall btnGray"><i></i><b></b><span
                                class="ac_fav_add" goods_id="1082982" goods_type="70000">收藏</span></a>
                        </p>


                        <span class="brandlogo"><img
                                src="${IMAGE_SERVER}cloud/static/list/t2usc33yjc7edrdm.png"></span>
                    </div>
                </li>

                <li class="">
                    <div class="body">
                        <p class="img"><a target="_blank"
                                          href="https://shop.10086.cn/sale/m/771_771_1084747_1072994.html"
                                          title="【移动商城】OPPO Reno5 5G手机"><img alt="【移动商城】OPPO Reno5 5G手机" class="lazy"
                                                                             src="${IMAGE_SERVER}cloud/static/list/tssq4wu7sfhch9qy_170x170.png"
                                                                             data-original="//img1.shop.10086.cn/goods/tssq4wu7sfhch9qy_170x170.png"
                                                                             style="display: inline;"></a></p>
                        <p class="price red"><em class="fontYaHei size14">￥</em>2249</p>
                        <p class="name" title="【移动商城】OPPO Reno5 5G手机购机送200元话费（7.16-7.25期间），再送价值100元大容量充电宝！"><a
                                target="_blank" href="https://shop.10086.cn/sale/m/771_771_1084747_1072994.html">【移动商城】OPPO
                            Reno5 5G手机<span class="red">
                                            购机送200元话费（7.16-7.25期间），再送价值100元大容量充电宝！
                                    </span></a></p>
                        <p class="marginTop10"><a target="_blank"
                                                  href="https://shop.10086.cn/sale/m/771_771_1084747_1072994.html"
                                                  class="btn btnSmall btnGray marginRight10"><i></i><b></b>闪购</a> <a
                                target="_blank" href="https://shop.10086.cn/goods/771_771_1084747_1072986.html"
                                class="btn btnSmall btnGray"><i></i><b></b>普通商品</a></p>


                        <span class="saletype"><i class="sale5"></i></span>

                        <span class="brandlogo"><img
                                src="${IMAGE_SERVER}cloud/static/list/tme5qqjzptwkh4sk.png"></span>
                    </div>
                </li>

                <li>
                    <div class="body">
                        <p class="img"><a target="_blank"
                                          href="https://shop.10086.cn/sale/m/771_771_1084790_1072443.html"
                                          title="【移动商城】小米10S 5G手机"><img alt="【移动商城】小米10S 5G手机" class="lazy"
                                                                        src="${IMAGE_SERVER}cloud/static/list/tssht53xwf2tuf6rm_170x170.png"
                                                                        data-original="//img1.shop.10086.cn/goods/tssht53xwf2tuf6rm_170x170.png"
                                                                        style="display: inline;"></a></p>
                        <p class="price red"><em class="fontYaHei size14">￥</em>2719</p>
                        <p class="name" title="【移动商城】小米10S 5G手机承诺在网24个月 信用购机方案总价0元起"><a target="_blank"
                                                                                        href="https://shop.10086.cn/sale/m/771_771_1084790_1072443.html">【移动商城】小米10S
                            5G手机<span class="red">
                                            承诺在网24个月 信用购机方案总价0元起
                                    </span></a></p>
                        <p class="marginTop10"><a target="_blank"
                                                  href="https://shop.10086.cn/sale/m/771_771_1084790_1072443.html"
                                                  class="btn btnSmall btnGray marginRight10"><i></i><b></b>闪购</a> <a
                                target="_blank" href="https://shop.10086.cn/goods/771_771_1084790_1072582.html"
                                class="btn btnSmall btnGray"><i></i><b></b>普通商品</a></p>


                        <span class="saletype"><i class="sale5"></i></span>

                        <span class="brandlogo"><img
                                src="${IMAGE_SERVER}cloud/static/list/tq7x33jnsg2ffv3eg.png"></span>
                    </div>
                </li>
                <li>
                    <div class="body">
                        <p class="img"><a target="_blank"
                                          href="https://shop.10086.cn/goods/771_771_1082900_1072016.html"
                                          title="【移动商城】Redmi Note9 5G手机"><img alt="【移动商城】Redmi Note9 5G手机" class="lazy"
                                                                              src="${IMAGE_SERVER}cloud/static/list/tsmhutacn37tfg5mj_170x170.png"
                                                                              data-original="//img1.shop.10086.cn/goods/tsmhutacn37tfg5mj_170x170.png"
                                                                              style="display: inline;"></a></p>
                        <p class="price red"><em class="fontYaHei size14">￥</em>1359</p>
                        <p class="name" title="【移动商城】Redmi Note9 5G手机赠200元移动话费券（7.16-7.25购机） 承诺在网24个月信用购机方案总价0元起"><a
                                target="_blank" href="https://shop.10086.cn/goods/771_771_1082900_1072016.html">【移动商城】Redmi
                            Note9 5G手机<span class="red">
                                            赠200元移动话费券（7.16-7.25购机） 承诺在网24个月信用购机方案总价0元起
                                    </span></a></p>
                        <p class="marginTop10">
                            <a target="_blank" href="https://shop.10086.cn/goods/771_771_1082900_1072016.html"
                               class="btn btnSmall btnGray marginRight10"><i></i><b></b>立即购买</a><a
                                href="javascript:void(0);" class="btn btnSmall btnGray"><i></i><b></b><span
                                class="ac_fav_add" goods_id="1082900" goods_type="70000">收藏</span></a>
                        </p>


                        <span class="brandlogo"><img
                                src="${IMAGE_SERVER}cloud/static/list/tq7x33jnsg2ffv3eg.png"></span>
                    </div>
                </li>
            </ul>
        </div>


        <div class="pagination clearfix">
            <em class="marginRight20">第${skuListPageInfo.current}/${skuListPageInfo.pages}页</em><em class="marginRight20">共${skuListPageInfo.total}条</em><span class="prev">首页<b></b><i></i></span>&nbsp;<span
                class="prev">&lt;<b></b><i></i></span>&nbsp;<span class="current">1<b></b><i></i></span>&nbsp;<a
                href="https://shop.10086.cn/list/101_771_771_2_0_0_0_0_0_0_0.html?p=2">2<b></b><i></i></a>&nbsp;<a
                href="https://shop.10086.cn/list/101_771_771_3_0_0_0_0_0_0_0.html?p=3">3<b></b><i></i></a>&nbsp;<a
                href="https://shop.10086.cn/list/101_771_771_4_0_0_0_0_0_0_0.html?p=4">4<b></b><i></i></a>&nbsp;<a
                href="https://shop.10086.cn/list/101_771_771_5_0_0_0_0_0_0_0.html?p=5">5<b></b><i></i></a>&nbsp;<a
                href="https://shop.10086.cn/list/101_771_771_6_0_0_0_0_0_0_0.html?p=6">6<b></b><i></i></a>&nbsp;<a
                class="next"
                href="https://shop.10086.cn/list/101_771_771_2_0_0_0_0_0_0_0.html?p=2">&gt;<b></b><i></i></a>&nbsp;<a
                class="next" href="https://shop.10086.cn/list/101_771_771_6_0_0_0_0_0_0_0.html?p=6">末页<b></b><i></i></a>&nbsp;
            <!--
	<p class="shortCut">到第 <input type="text" value="1/8" class="txt-normal" /> 页</p>
	<p class="count">第 1/8 页 每页 12 项 共 90 项</p>
	<p class="body">
		<a href="#">&lt;&lt;</a>
		<a href="#">1</a>
		<a href="#">2</a>
		<a href="#">3</a>
		<span>4</span>
		<a href="#">5</a>
		<a href="#">6</a>
		<span>...</span>
		<a href="#">8</a>
		<a href="#">&gt;&gt;</a>
	</p>
	-->
        </div>

    </div>

</div>
<div class="mask wx_mask">
    <div id="" class="bg">
        <img src="${IMAGE_SERVER}cloud/static/list/guide_wxtq.png__347.png" class="g">
        <a href="javascript:void(0);" class="bt ac_btn_know"></a>
    </div>
</div>

<style type="text/css">
    .lowerIEtips {
        display: none;
        _display: block;
        _position: absolute;
    }
</style>
<#--<div class="globalMain margin10">
    <div class="footerService">
        <ul class="clearfix">
            <li>
                <dl class="clearfix gwzn">
                    <dt>购物指南</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_0" target="_blank" title="用户注册"
                           href="https://shop.10086.cn/help/771_771/14.html">用户注册</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_1" target="_blank" title="用户登录"
                           href="https://shop.10086.cn/help/771_771/18.html">用户登录</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_0_2" target="_blank" title="购物说明"
                           href="https://shop.10086.cn/help/771_771/7.html">购物说明</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix zffs">
                    <dt>付款方式</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_1_0" target="_blank" title="在线支付"
                           href="https://shop.10086.cn/help/771_771/27.html">在线支付</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_1_1" target="_blank" title="货到付款"
                           href="https://shop.10086.cn/help/771_771/29.html">货到付款</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix wlps">
                    <dt>物流配送</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_2_0" target="_blank" title="快递配送"
                           href="https://shop.10086.cn/help/771_771/30.html">快递配送</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_2_1" target="_blank" title="签收提示"
                           href="https://shop.10086.cn/help/771_771/19.html">签收提示</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix shfw">
                    <dt>售后服务</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_0" target="_blank" title="退换货原则"
                           href="https://shop.10086.cn/help/771_771/31.html">退换货原则</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_1" target="_blank" title="退款说明"
                           href="https://shop.10086.cn/help/771_771/12.html">退款说明</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_3_2" target="_blank" title="退货申请/查询"
                           href="https://shop.10086.cn/help/771_771/21.html">退货申请/查询</a>
                    </dd>
                </dl>
            </li>
            <li>
                <dl class="clearfix grzx">
                    <dt>个人中心</dt>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_0" target="_blank" title="我的订单"
                           href="https://shop.10086.cn/help/771_771/28.html">我的订单</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_1" target="_blank" title="充值交费"
                           href="https://shop.10086.cn/help/771_771/20.html">充值交费</a>
                    </dd>
                    <dd>
                        <a class="ac_dcs_base" dcs_id="footer_help_4_2" target="_blank" title="我的账户"
                           href="https://shop.10086.cn/help/771_771/16.html">我的账户</a>
                    </dd>
                </dl>
            </li>
        </ul>
    </div>
</div>-->
<#include "../common/footerNav.ftlh">
<#--<div id="footer">
    <p>
        <a href="http://www.10086.cn/aboutus/news/" target="_blank">新闻中心</a>
        | <a href="http://job.10086.cn/" target="_blank">诚聘英才</a>
        | <a href="https://b2b.10086.cn/b2b/main/preIndex.html" target="_blank">采购信息</a>
        | <a href="http://www.10086.cn/aboutus/hezuo/" target="_blank">企业合作</a>
        | <a href="http://www.10086.cn/web_notice/contact/" target="_blank">联系我们</a>
        | <a href="http://www.10086.cn/web_notice/navigation/" target="_blank">站点导航</a>
        | <a href="http://www.cmdi.chinamobile.com/" target="_blank">中国移动设计院</a>
        | <a href="http://www.10086.cn/web_notice/links/" target="_blank">友情链接</a>
        | <a href="https://www.10086.cn/events/djcx/" class="red" style="color:#ed2668" target="_blank">打击传销</a>
    </p>
    <p>掌上营业厅：<a href="http://wap.10086.cn/" target="_blank">wap.10086.cn</a> 语音自助服务：10086 短信营业厅：10086 <a
            href="http://www.10086.cn/support/service/channel/entity/" target="_blank">自助终端</a> <a
            href="http://www.10086.cn/support/service/channel/entity/" target="_blank">营业厅</a> <a
            href="http://www.10086.cn/cmccclient/index.htm" target="_blank">手机营业厅下载</a></p>
    <p style="width:300px; margin:0 auto;" class="clearfix">
        <a target="_blank"
           href="https://ss.knet.cn/verifyseal.dll?sn=e130905110100423008ilb000000&ct=df&a=1&pa=0.3082310492237422"
           class="floatleft"><img src="${IMAGE_SERVER}cloud/static/list/cnnic.png__0.png"
                                  align="absmiddle" oncontextmenu="return false;"></a>
        <span class="floatleft alignleft" style="padding-left:20px;">
			<a href="http://beian.miit.gov.cn/" target="_blank"><img
                    src="${IMAGE_SERVER}cloud/static/list/gov.gif__0.gif" align="absmiddle">京ICP备05002571号</a><br>　中国移动通信版权所有
		</span>
    </p>
</div>-->
<#include "../common/footer.ftlh">
<div class="mask" id="mask"></div>
<div class="lowerIEtips" style="position: fixed;_position: absolute;bottom:0px;display:none;_display:block;">
    <div class="tipcon"><span><img src="${IMAGE_SERVER}cloud/static/list/logo2.png__240.png"
                                   style="width: 160px; height: 29px;"></span>
        <p>您的浏览器版本过低，如果页面显示不正常，建议将浏览器升级到最新版本。</p><!-- <a class="close" id="closeTips"></a> --></div>
</div>

<div id="" class="rightfloatbox">
    <ul class="rightfloatnav" id="returntop" style="display: none;">
        <li><a dcs="fast_link_phone" target="_blank" href="https://shop.10086.cn/order/shoplist.php"
               class="ac_footer_sdc rfn_9 ac_cart1_count ac_dcs_base" dcs_id="NAV_RIGHTFLOAT_CART">购物车</a>
            <span class="cart-quan"><b></b><em>0</em><i></i></span></li>
        <li><a dcs="fast_link_phone" target="_blank" href="https://shop.10086.cn/list/101_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_1">购买手机</a></li>
        <li><a dcs="fast_link_package" target="_blank" href="https://shop.10086.cn/list/140_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_8">办理套餐</a></li>
        <li><a dcs="fast_link_service" target="_blank" href="https://shop.10086.cn/list/146_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_2">办理业务</a></li>
        <li><a dcs="fast_link_number" target="_blank" href="https://shop.10086.cn/list/134_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_3">选购号码</a></li>
        <li><a dcs="fast_link_accessory" target="_blank" href="https://shop.10086.cn/list/128_771_771_1_0_0.html"
               class="ac_footer_sdc rfn_4">挑选配件</a></li>
        <li><a dcs="fast_link_home" target="_blank" href="https://shop.10086.cn/i/?f=home" class="ac_footer_sdc rfn_5">个人中心</a>
        </li>
        <li><a dcs="fast_link_index" target="_blank" href="https://shop.10086.cn/mall_771_771.html"
               class="ac_footer_sdc rfn_6">返回首页</a></li>
        <li><a dcs="fast_link_zxkf" target="_blank"
               href="https://shop.10086.cn/ac/livechat-web-client/robertIndex?tenantId=1000078&code=BS&channelType=1011"
               class="ac_footer_sdc rfn_zxkf">在线客服</a></li>
        <li><a dcs="fast_link_top" href="https://shop.10086.cn/list/101_771_771_1_0_0_0_0_0_0_0.html#"
               class="ac_footer_sdc rfn_7">返回顶部</a></li>
    </ul>

    <div class="dorpdown-layer" style="display:none">


        <style type="text/css">
            .cart-layer .cart_list {
                width: 350px;
            }

            .height268 {
                height: 268px;
            }

            .cart-layer .loadingBlock {
                height: 75px;
            }
        </style>
        <div class="have_goods">
            <div class="cart-layer" style="border-bottom: 1px solid #ECECEC">
                <div class="loadingBlock"></div>
                <div class="cart_goodslist" style="display: none;">
                    <p class="smt top">最新加入的商品</p>
                    <p class="smt right">购物车</p>
                    <div id="content-1" class="cart_list mCustomScrollbar _mCS_2 mCS_no_scrollbar">
                        <div id="mCSB_2" class="mCustomScrollBox mCS-light mCSB_vertical mCSB_inside" tabindex="0"
                             style="max-height: 0px;">
                            <div id="mCSB_2_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y"
                                 style="position:relative; top:0; left:0;" dir="ltr">

                            </div>
                            <div id="mCSB_2_scrollbar_vertical"
                                 class="mCSB_scrollTools mCSB_2_scrollbar mCS-light mCSB_scrollTools_vertical"
                                 style="display: none;">
                                <div class="mCSB_draggerContainer">
                                    <div id="mCSB_2_dragger_vertical" class="mCSB_dragger"
                                         style="position: absolute; min-height: 30px; top: 0px;">
                                        <div class="mCSB_dragger_bar" style="line-height: 30px;"></div>
                                    </div>
                                    <div class="mCSB_draggerRail"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" btm black" style="display: none;">
                <p><span class="cartcount">共<b style="font-weight: normal">0</b>件商品</span> 共计：<span class="red">¥ <b
                        style="font-weight: normal"></b></span></p>
                <a href="https://shop.10086.cn/order/shoplist.php" class="btn btnGraySmall btnRed ac_dcs_base"
                   dcs_id="NAV_CART_GO">去购物车<em></em><i></i><b></b></a>
            </div>
        </div>
        <!--<img class="ajax_loading" style="margin-left: 155px;" src="//img0.shop.10086.cn/www/core/css/global/ajax_loading_max.gif__81.gif" />-->
        <div id="" class="nogoods btm black" style="display: none;">
            <p class="nogoods_p">购物车内暂时还没有商品</p>
            <p class="abate" style="display:none">您购物车里的商品均已失效</p>
            <a href="https://shop.10086.cn/order/shoplist.php"
               class="btn btnGraySmall btnRed">去购物车<em></em><i></i><b></b></a>
        </div>


        <b class="cart-mask	"></b>
    </div>
</div>


<script type="text/javascript" src="${IMAGE_SERVER}cloud/static/list/loader.js__357.js"></script>
<script src="${IMAGE_SERVER}cloud/static/list/sdc_mall.js__635.js"></script>
<script type="application/javascript">
    // 获取url中的参数
    function getQueryString(name) {
        var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
        var r = window.location.search.substr(1).match(reg);
        if (r != null) return unescape(r[2]); return null;
    }
    // 筛选条件
    let brandId = '';
    let price = '';
    let paraArr = [];
    let paraMap = {};
    let activeClass = 'current';
    // 品牌
    $('dl[type=brand] a').click(function () {
        $('dl[type=brand] dt span').removeClass(activeClass);
        $('dl[type=brand] dd ul li a').removeClass(activeClass);
        let bid = $(this).attr('brandid');
        brandId = bid;
        if (bid && bid != '') {
            $(this).addClass(activeClass);
        } else {
            $(this).parent().addClass(activeClass);
            brandId = '';
        }
        queryFieldChange();
    });
    // 价格
    $('dl[type=price] a').click(function () {
        $('dl[type=price] dt span').removeClass(activeClass);
        $('dl[type=price] dd ul li').removeClass(activeClass);
        $(this).parent().addClass(activeClass);
        let text = $(this).text();
        price = text;
        if (!text || text == '全部') {
            price = '';
        }
        queryFieldChange();
    });
    // 属性
    $('dl[type=feature] a').click(function () {
        let featureId = $(this).attr('featureid');
        let key = 'featureid_' + featureId;
        let sv = $(this).attr('sv');
        if (sv && sv != '') {
            // 非全部
            $(this).parent().parent().parent().parent().find('dt span').removeClass(activeClass);
            $(this).parent().parent().find('li').removeClass(activeClass);
        } else {
            $(this).parent().removeClass(activeClass);
            $(this).parent().parent().parent().find('dd ul li').removeClass(activeClass);
        }
        $(this).parent().addClass(activeClass);
        paraMap[featureId] = sv;
        queryFieldChange();
    });
    function queryFieldChange() {
        paraArr = [];
        for (const key in paraMap) {
            let v = paraMap[key];
            if (v && v != '') {
                paraArr.push(key + "_" + v);
            }
        }
        console.log(brandId);
        console.log(price);
        console.log(paraArr);
        window.location = window.location.href.split('?')[0] + '?catId=' + getQueryString('catId') + '&brandId=' +
            brandId + '&price=' + price + '&paras=' + paraArr.join(',');
    }
</script>
<script type="text/javascript">
    window.ENVOBJ = {
        "loc": {"province_id": 771, "city_id": 771},
        "loginurl": "https:\/\/login.10086.cn\/SSOCheck.action?channelID=12002&backUrl=https%3A%2F%2Fshop.10086.cn%2Flist%2F101_771_771_1_0_0_0_0_0_0_0.html%3Fforcelogin%3D1"
    };
    LOADJS('//img0.shop.10086.cn/combo/__623/script/jquery-1.10.2.js__script/cookie/jquery.cookie.js__script/iprompt/jquery.iprompt.js__script/formater.js__script/pubsub/jquery.pubsub.js__script/interactive/jquery.interactive.js__script/jquery.lazyload.js__www/core/js/global.js__www/core/js/fav.js__www/core/js/dcs_tracker.js__www/mod/search/js/shop_jsonp_search.js__script/mousewheel/jquery.mousewheel.js__script/customscrollbar/jquery.mCustomScrollbar.js__script/placeholder/jquery.placeholder.js', function () {
//	$.domains = window.ENVOBJ.domains;


        $
            .sub('click_login_mini', __mini_login)
            .sub('login_mini', __mini_login)
            .sub('login_mini_msg', __mini_login_msg)
        ;
        var _options = null
        var _spritebox = null;

        function __mini_login(event, options) {
            _options = options;
            var miniframe = $('#login_box').html();
            if (miniframe) {
                _spritebox = $('#jquery-interactive-box2').hide();
                $('#jquery-interactive-mask').hide();
                var $box = $.alert(miniframe, {
                    onLoad: function ($box) {
                        $box.find('.interactive-content').css({
                            'background-color': '#ECECEC'
                        });
                    },
                    onClose: function () {
                        $.pub('login_mini_cancel');
                        _options = null;
                        _spritebox = null;
                        $.UI.hide();
                    },
                    liveTime: null,
                    noCloser: false
                });
                return false;
            } else {
                return true;
            }
        }

        function __mini_login_msg(event, r) {
            if (window.initUser) {
                window.initUser(r);
            }
            $.UI.hide('alert');
            if (r.code == 0) {
                if (_options && typeof _options == 'object') $.ajax(_options);
                _options = null;
                if (_spritebox && _spritebox.length) {
                    $('#jquery-interactive-mask').show();
                    _spritebox.show();
                }
                _spritebox = null;
            } else {
                $.UI.hide();
            }
        }

        ;
        $(function () {
            $(".cart_list").mCustomScrollbar();
        });

        $(function () {
            /*$.sub('mouseover_cart1_count', __cart1_count).sub('msg_cart', __cart1_show, false);
            var list_lock = true;

            function __cart1_count() {
                if (list_lock) {
                    $.getJSON('/ajax/cartshop/list.json', function (r) {
                        if (r.code) {
                            $.alert(r.msg);
                        } else {
                            $.pub('msg_cart', r.data);
                        }
                    });
                }
                list_lock = false;
            }


            function __cart1_show(event, r) {
                var cartdata = r;
                var $cart_list = [];
                var $cartcount = null;
                if (cartdata && cartdata.cartcount) {
                    var total = 0, count = 0;
                    $('.dorpdown-layer .cart_list .mCSB_container').html(cartdata.content);
                    $('.have_goods .cartcount b,.rightMenu .cart .red,.rightfloatbox .cart-quan em').html(cartdata.cartcount);
                    $cart_list = $('.rightMenu .cart_list').find('li');
                    if ($cart_list.length > 5) {
                        $('.cart_list').addClass('height268');
                    } else {
                        $('.cart_list').removeClass('height268');
                    }
                    ;
                    $($cart_list).each(function () {
                        var $t = $(this);
                        total += parseInt($t.attr('num')) * parseInt($t.attr('price') * 100) || 0;
                        //count +=parseInt($t.attr('num'))||0;
                    });
                    $('.have_goods .btm .red b').text((total / 100).toFixed(2));
                    //$('.have_goods .btm .cartcount b').text(count);
                    $cartcount = $('.cart_list ul').attr('cartcount');
                    if ($cart_list.length == 0 && $cartcount) {
                        $('.dorpdown-layer .loadingBlock').hide();
                        $('.dorpdown-layer .nogoods_p').hide();
                        $('.dorpdown-layer .abate').show();
                        $('.dorpdown-layer .nogoods').show();
                        $('.dorpdown-layer .have_goods').hide();
                    } else {
                        $('.dorpdown-layer .nogoods').hide();
                        $('.dorpdown-layer .loadingBlock').hide();
                        $('.dorpdown-layer .have_goods').show();
                        $('.dorpdown-layer .cart_goodslist').show();
                        $('.dorpdown-layer .have_goods .btm').show();
                    }
                } else {
                    $('.have_goods .cartcount b,.rightMenu .cart .red,.rightfloatbox .cart-quan em').html('0');
                    $('.dorpdown-layer .loadingBlock').hide();
                    $('.dorpdown-layer .abate').hide();
                    $('.dorpdown-layer .nogoods_p').show();
                    $('.dorpdown-layer .nogoods').show();
                    $('.dorpdown-layer .have_goods').hide();
                };
            }*/

            var timer = null;
            $('.cart').hover(function () {
                var is_cart = '';
                if (is_cart) return false;
                clearTimeout(timer);
                $(".rightMenu .dorpdown-layer").show();
                //__hover_get_cart();
                //$.pub("hover_get_cart");
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $(".rightMenu .dorpdown-layer").hide();
                }, 100);
            });
            $('.dorpdown-layer').hover(function () {
                list_lock = false;
                clearTimeout(timer);
                $('.cart').addClass('current');
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    list_lock = true;
                    $('.cart').removeClass('current');
                    $('.rightMenu .dorpdown-layer').hide();
                }, 100);
            });


            $
                .sub('click_cartlist_delete', __cartlist_delete, false)
                .sub('cartlist_del', cartlist_del, false)
            ;

            function __cartlist_delete() {
                var $t = $(this);
                var cartcount = $t.closest('ul').attr('cartcount');
                $.getJSON('/ajax/cartshop/delete.json', {selected: $t.closest('li').attr('cartid')}, function (r) {
                    if (r.code) {
                        $.alert(r.msg);
                    } else {
                        $t.closest('li').remove();
                        $cart_list = $('.rightMenu .cart_list').find('li');
                        if ($cart_list.length > 5) {
                            $('.cart_list').addClass('height268');
                        } else {
                            $('.cart_list').removeClass('height268');
                        }
                        ;
                        $.pub('cartlist_del');
                    }
                    ;
                });
            }

            function cartlist_del() {
                var c_num = $('.cart .red').text();
                $('.have_goods .cartcount b,.rightMenu .cart .red,.rightfloatbox .cart-quan em').text(parseInt(c_num - 1));
                $('#returntop .cart-quan em').text(parseInt(c_num - 1));
                var total = 0;
                var $cart_list = $('.rightMenu .cart_list').find('li');
                $($cart_list).each(function () {
                    var $t = $(this);
                    total += parseInt($t.attr('num')) * parseInt($t.attr('price') * 100) || 0;
                });
                $('.have_goods .btm .red b').text((total / 100).toFixed(2));
                if (c_num && c_num - 1 != 0) {
                    $('.dorpdown-layer .nogoods').hide();
                    $('.dorpdown-layer .have_goods').show();
                } else {
                    $('.dorpdown-layer .nogoods').show();
                    $('.dorpdown-layer .have_goods').hide();
                }
                ;
            }
        });


        $(document).ready(function () {
            var timers = null;

            $(".cmccclient").hover(function () {
                clearTimeout(timers);
                var cmcc_left_1 = $('.cmccclient').position().left + 2;
                $('.ewm').css('left', cmcc_left_1);
                $('.ewm').show();
            }, function () {
                timers = setTimeout(function () {
                    $('.ewm').hide();
                }, 100);
            });
            $('.ewm').hover(function () {
                var cmcc_left_2 = $('.cmccclient').position().left + 2;
                clearTimeout(timers);
                $('.cmccclient').addClass('cmccclienthover');
                $(this).css('left', cmcc_left_2);
                $(this).show();
            }, function () {
                var $t = $(this);
                timers = setTimeout(function () {
                    $('.cmccclient').removeClass('cmccclienthover');
                    $t.hide();
                }, 100);
            });
        });


        window.initUser = function (r) {
            if (r.code == 0) {
                window.loginUser = r.data;
                var nickname = r.data.nick_name || r.data.user_name;
                var tmpnick = nickname.split('@')[0];
                var noread = (r.data.msg_remind || {}).noread || 0;
                var showeye = r.data.is_china_mobile ? '' : 'eye-hide'; // 互联网用户不显示眼睛
                var tmpstr =
                    '<span class="tel floatleft marginRight10" title="' + nickname + '">' + tmpnick + '</span><i class="floatleft marginRight10 icon_eye ' + showeye + ' ac_handle_mobile"></i>' +
                    '<span class="floatleft noticearea" >' +
                    ' <a href="https://shop.10086.cn/i/?f=mynews"  target="_blank" class="red floatleft">消息 ' + noread + '</a> </span>' +
                    '<a class="red bold" href="javascript:void(logout())" title="退出">[退 出]</a><em>|</em>';
                document.getElementById('userinfo').innerHTML = tmpstr;
                if ($.pub) {
                    $.pub('login_success', r.data);
                }
                // 当前登陆人插码 ,如果是手机号登录，写入手机号，否则清空
                if (_tag) {
                    if (r.data.is_china_mobile) {
                        _tag.setMobile(r.data.wtmobile);
                    } else {
                        _tag.setMobile();
                    }
                }
            } else if (r.code == 3) {
                $('#ssocheckframe').attr('src', r.data);
            } else {
                $.pub('user_not_login_after_query');
                $('.btnOnestepbuy').hide();
                // 当前登陆人插码 没登陆清空
                if (_tag) {
                    _tag.setMobile();
                }
            }
        }
        var userParam = {
            'province_id': '771',
            'city_id': '771'
        }
        userParam.update = 1;
        $.getJSON('/ajax/user/userinfo.json', userParam, initUser);


        ;
        $(function () {
            var provinceId = "771";	//省区编码
            var cityId = "771";	//市区编码
            var charset = "utf-8";

            $("#skeywords").search({
                type: 1,
                maxResult: 10,
                provinceId: provinceId,
                cityId: cityId,
                tabType: 1,
                tabName: '',
                showDefaultWord: 1,
                showHotSearchWord: 1,
                charset: charset
            }).change(function () {
                $(this).siblings('[name="from"]').val('10601');
            });
        });


        $(function () {
            $('.shopSearch .mainmenu').hover(function () {
                $(this).addClass('hover');
            }, function () {
                $(this).removeClass('hover');
            });
            var dcs_map = {
                '101': 'Home_FirstScreen_PHONE',
                '140': 'Home_FirstScreen_EXPENSE',
                '146': 'Home_FirstScreen_VAS',
                '134': 'Home_FirstScreen_NUMBER',
                '128': 'Home_FirstScreen_ACCESORY',
                'jiaohuafei': 'Home_FirstScreen_HUAFEI',
                'home_firstscreen_grzx': 'Home_FirstScreen_PERSONALCENTER',
                'home_firstscreen_ad_1': 'Home_FirstScreen_AD_1',
                'home_firstscreen_ad_2': 'Home_FirstScreen_AD_2',
                'home_firstscreen_ad_3': 'Home_FirstScreen_AD_3',
                'home_firstscreen_ad_4': 'Home_FirstScreen_AD_4',
                'home_firstscreen_ljcz': 'Home_FirstScreen_RECHARGE',
                'home_firstscreen_hfcz': 'Home_FirstScreen_HF_RECHARGE',
                'home_firstscreen_llcz': 'Home_FirstScreen_LL_RECHARGE',
                'home_firstscreen_30': 'Home_FirstScreen_30',
                'home_firstscreen_50': 'Home_FirstScreen_50',
                'home_firstscreen_100': 'Home_FirstScreen_100',
                'home_firstscreen_200': 'Home_FirstScreen_200',
                'home_firstscreen_500': 'Home_FirstScreen_500'
            };
            $.sub('click_dcstracker_homefirstscreen', __dcstracker_homefirstscreen);

            function __dcstracker_homefirstscreen() {
                var $t = $(this);
                $.dcstracker({
                    category: 'Home',
                    action: 'FirstScreen',
                    event: dcs_map[$t.attr('dcs_id')] || $t.attr('dcs_id')
                });
            }
        });


        $(document).ready(function () {
            var timer = null;
            $('#nav .title').hover(function () {
                clearTimeout(timer);
                $(".spnav .smore").css('display', 'none');
                $(".spnav .goodsNav").show();
            }, function () {
                $(".spnav .smore").css('display', 'none');
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
            $(".spnav .goodsNav").hover(function () {
                clearTimeout(timer);
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    $(".spnav .goodsNav").hide();
                }, 100);
            });
        });


        // $('.ac_dcs_base').not('.first .ac_dcs_base').mouseenter(function() {
        // 	$(this).css('border-top-color', '#0085D0');
        // 	$(this).closest('li').siblings().find('.ac_dcs_base').not('.shop_ini').css('border-top-color', '#EAEAEA');
        // }).eq(0).mouseenter();
        // $('.ac_dcs_base').not('.shop_ini').mouseout(function() {
        // 	$(this).css('border-top-color', '#EAEAEA');
        // })


        ;
        $(function () {
            $
                .sub('click_show_areabar', __show_areabar)
                .sub('click_show_city', __show_city)
                .sub('click_city_choose', __gotocity)
            ;

            //清除浮层
            function __clear_areabar() {
                $('#header').find('.area ul').hide();
            }

            //展开浮层
            function __show_areabar() {
                __clear_areabar();
                var $this = $(this);
                $this.next().show();
                return false;
            }

            function __gotocity(loc) {
                if (typeof loc != "string") {
                    loc = $(this).attr('location');
                }
                var locarray = loc.split('_');
                var pid = locarray[0], cid = locarray[1];
                var url = location.href;
                if (url.indexOf('/list/') > 0 || url.indexOf('/tags/') > 0) {
                    url = url.replace(/_\d{3}_\d{3,4}/i, "_" + loc);
                    setTimeout(function () {
                        location.href = url;
                    });
                } else {
                    setTimeout(function () {
                        location.href = "/mall_{loc}.html".replace("{loc}", loc);
                    });
                }
            }

            function getCityByProvince(province_id) {
                if (!window.allcity[province_id]) {
                    $.ajax({
                        async: false,
                        url: "/ajax/region/singleregion.json",
                        data: {province_id: province_id},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg)
                            } else {
                                window.allcity[province_id] = r.data || [];
                            }
                        },
                        dataType: 'json'
                    });
                }
                return window.allcity[province_id];
            }

            var $province = $('#header .province'),
                $city = $('#header .city'),
                current_province_id = $province.find('span').attr('province_id'),
                city_id = '771',
                reg = new RegExp('<!--|-->', 'g'),
                template = new Formater($('.header_area_template').html().replace(reg, '') || '<li><a href="#" target="_blank">{city_name}</a></li>'),
                city_name = '南宁'
            ;

            //点击省下拉项展开市浮层
            function __show_city() {
                var $this = $(this),
                    province_id = $this.attr('province_id'),
                    tmp = ''
                ;
                if ($this.attr('iscity')) {
                    __gotocity(province_id + "_" + province_id);
                    return false;
                }
                var data = getCityByProvince(province_id);
                $city.find('span').text('请选择');
                //var cityAreaWidth = (data.length < 4) ? 40*(data.length + 1) + 5 : 245;//根据市的个数，判断外框宽度
                $.each(data, function (inx, item) {
                    tmp += template.exec(item);
                });
                __clear_areabar();
                $this.closest('ul').prev().attr('province_id', $this.attr('province_id')).text($this.text());
                $city.find('ul').html(tmp).show();
                return false;
            }

            //点击其他dom收起浮层
            $(document).bind('click.area', function (e) {
                if ($(e.target).closest('.area').length == 0) {
                    __clear_areabar();
                }
                if ($(e.target).closest('.fs_box').length === 0) {
                    $('.fs_box ul').hide();
                }
            });

        })
        ;


        ;
        $(function () {
            var _mobileFuzzy = mobileFuzzy();

            $
                .sub('login_success', _mobileFuzzy.loginSuccess)
                .sub('click_send_msgcode4eye', _mobileFuzzy.sendMsgCode, false)
                .sub('click_handle_mobile', _mobileFuzzy.handleMobile, false)
            ;

            mobileFuzzy.$sms_mobile = $('#smsContent');

            function mobileFuzzy() {
                var mobile = null, isLogin = false, isShow = 0;
                var time = 60;
                var timer;

                // 填写mobile，并切换小眼睛的显示与隐藏
                function _handleMobile() {
                    var $eye = $('.userinfo .icon_eye');
                    isLogin && $('.userinfo .tel').text(mobile).attr('title', mobile);
                    mobile && (isShow ? $eye.removeClass('eye-close') : $eye.addClass('eye-close'));
                }

                // 发送验证码倒计时
                function _timeCountDown() {
                    var $msg_code = $('.sms-content .msg-code');
                    if (time === 0) {
                        clearInterval(timer);
                        $msg_code.removeClass('btnGray').addClass('ac_send_msgcode4eye btnBlue').find('span').text("重发验证码");
                        time = 60;
                        return false;
                    }
                    $msg_code.removeClass('btnBlue ac_send_msgcode4eye').addClass('btnGray').find('span').text(time + "s后发送");
                    time--;
                }

                // 弹出短信验证框
                function _popSmsBox() {
                    $.confirm($('#smsContent').html(), {
                        direction: null,
                        align: null,
                        mask: true,
                        noCloser: false,
                        preButtons: true,
                        onLoad: function ($box) {
                            $box.find('.mobile').html(mobile)
                        },
                        onAccept: _submitCheck
                    });
                }

                // 校验短信验证码是否正确，并设置返回值中的mobile和小眼睛状态等
                function _submitCheck() {
                    var flag = false;
                    $.ajax({
                        url: '/ajax/shownumber/submitcheck.json',
                        data: {msg_verify: $('.sms-content input[name="msg_verify"]').val()},
                        success: function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else if (r.data) {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                                flag = true;
                            }
                        },
                        dataType: 'json',
                        async: false
                    });
                    return flag;
                }

                // 点击小眼睛，控制手机号是否模糊化
                function _queryStatus() {
                    if (!isLogin) return;
                    $.getJSON('/ajax/shownumber/shownumber.json', {is_show: isShow}, function (r) {
                        if (r.code) {
                            $.alert(r.msg);
                        } else if (r.data) {
                            if (r.data.need_frame) {  // 后台告诉是否需要弹出短验窗口，need_frame=1表示当前登录状态会话下已经短信未校验过
                                _popSmsBox();
                            } else {
                                mobile = r.data.user_name;
                                isShow = r.data.num_show;
                                _handleMobile();
                            }
                        }
                    });
                }

                return {
                    // 校验是否登录，并填写用户名
                    loginSuccess: function () {
                        var user = arguments[0] instanceof jQuery.Event ? arguments[1] : arguments[0];
                        var nickname = user.nick_name || user.user_name;
                        // 如果是手机号用户，则设置isShow
                        if (user.is_china_mobile) {
                            isShow = user.num_show;
                            mobile = nickname;
                            isLogin = true;
                            _handleMobile();
                        }
                    },
                    handleMobile: _queryStatus,
                    // 发送短信验证码
                    sendMsgCode: function () {
                        $.getJSON('/ajax/shownumber/msg_send.json', function (r) {
                            if (r.code) {
                                $.alert(r.msg);
                            } else {
                                timer = setInterval(_timeCountDown, 1000);
                            }
                        });
                    }
                }
            }
        });


        /*
	;$(function(){
	$
	.sub("click_more",__more,false)
	.sub("click_up",__up,false)
	;
	function __more () {
		var $t=$(this);
		$t.hide().next().show().closest('.button').prev().find('.nopic').removeClass('hide');
	}
	function __up () {
		var $t=$(this);
		$t.hide().prev().show().closest('.button').prev().find('.nopic').addClass('hide');
	}
	$('.pic').hover(function() {
		$(this).closest('td').css('z-index', '9999');
	}, function() {
		$(this).closest('td').css('z-index', '0');
	});
	var index=$(".current").closest('td').attr('index');
	if (!isNaN(index) && index > 14) {$(".ac_more").click();};
	});
	*/
        ;$(function () {
            $
                .sub("click_more", __more, false)
                .sub("click_up", __up, false)
            ;

            function __more() {
                var $t = $(this);
                $t.hide().next().show().closest('.button').prev().find('.nopic').removeClass('hide');
                $t.hide().next().show().closest('.button').prev().find('li').removeClass('w1khide');
                $(".pp").removeClass("pp_ht");
            }

            function __up() {
                var $t = $(this);
                $t.hide().prev().show().closest('.button').prev().find('.nopic').addClass('hide');
                $t.hide().prev().show().closest('.button').prev().find('.nopic').addClass('w1khide');
                $t.hide().prev().show().closest('.button').prev().find('.narrow').addClass('w1khide');
                $(".pp").addClass('pp_ht');
            }

            $('.pic').hover(function () {
                $(this).closest('li a').css('z-index', '9999');
            }, function () {
                $(this).closest('li a').css('z-index', '0');
            });
            var index = $(".current").closest('li').attr('index');
            var li_show = 16;
            if ($('.selectFilter .pp li:visible').length == 12) {
                li_show = 12;
            }
            if (!isNaN(index) && index > li_show) {
                $(".ac_more").click();
            }
            ;
        });


        $.sub('click_listsort_dcs', __listsort_dcs, false);

        function __listsort_dcs() {
            var $t = $(this);
            var dcsid = $t.attr('dcs_id');
            $.dcstracker({
                action: 'LIST_FILTER',
                event: $t.attr('dcs_id')
            });
            setTimeout(function () {
                location.href = $t.attr('href');
            }, 500);
            return false;
        }


        ;$(function () {
            $
                .sub('click_dcstracker', __dcstracker)
                .sub('dcstracker_init', __dcstracker_init)
            ;

            function __dcstracker() {
                $.pub('dcstracker_init', 'dcstracker_init', $(this));
            }

            function __dcstracker_init(event, action, target) {
                var $t = $(target);
                $.dcstracker({
                    action: 'phone_List',
                    event: $t.attr('dcs_id')
                });
            }

            var catalog_type = "phone";
            $.getJSON('/ajax/goods/getreconmmendinfo.json', {
                province_id: 771,
                city_id: 771,
                catalog_type: catalog_type
            }, function (r) {
                if (r.data) {
                    $(".boutique").replaceWith(r.data);
                }
            });

            //吉林网选厅取蒙层cookie
            var maskShow = $.cookie("wx_mask");
            var current_province_id = 771;
            if (current_province_id == 431) {
                $('body,html').animate({scrollTop: 500}, 1000);
            }
            ;
            if (!maskShow && current_province_id == 431) {
                $('.wx_mask').show();
                $.cookie("wx_mask", 1, {expires: 30, path: '/', secure: true});
            }

            $('.ac_btn_know').click(function () {
                $('.mask').hide();
            });
        });


        ;
        $(function () {

            $(window).scroll(function () {
                if (sTop >= 0) {
                    if (isIE6()) {
                        var wheight = $(window).height;
                        var sTop = $(window).scrollTop();
                        var h = parseInt(wheight + sTop);
                        $('.lowerIEtips').stop().animate({marginTop: h}, 1).show();
                    }
                }
            }).scroll();

        });


        ;
        $(function () {
            $(".cart_list").mCustomScrollbar();
        });


        $(document).ready(function () {
            var timer = null;
            $('.rfn_9').hover(function () {
                clearTimeout(timer);
                $(".rightfloatbox .dorpdown-layer").show();
                // __hover_get_cart();
                //$.pub("hover_get_cart");
            }, function () {
                timer = setTimeout(function () {
                    $('.rfn_9').removeClass('hover');
                    $(".rightfloatbox .dorpdown-layer").hide();
                }, 100);
            });
            $('.rightfloatbox .dorpdown-layer').hover(function () {
                clearTimeout(timer);
                $('.rfn_9').addClass('hover');
                $(this).show();
            }, function () {
                timer = setTimeout(function () {
                    $('.rfn_9').removeClass('hover');
                    $(".rightfloatbox .dorpdown-layer").hide();
                }, 100);
            });

            $
                .sub('click_footer_sdc', __footer_sdc)
            ;

            function __footer_sdc() {
                var $t = $(this);
                $.dcstracker({
                    action: 'footer_fast_link',
                    event: $t.attr('dcs')
                });
            };
        });


    }, 'utf-8');
</script>


</body>
</html>