<!DOCTYPE html>
<!-- saved from url=(0053)https://shop.10086.cn/i/?f=home&welcome=1598407969731 -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="vertion" content="VERSION11">

    <meta name="twosize" content="true">
    <meta name="WT.LoginType" content="">
    <meta name="WT.event" content="">
    <meta name="WT.si_n" content="">
    <meta name="WT.cg_n" content="home">
    <meta name="description"
          content="欢迎您访问中国移动网上商城个人中心。中国移动官方网站为您提供业务介绍，手机话费充值查询，套餐资费介绍及网上查询办理，号码购买，优惠购机，积分查询，优惠活动等网上自助服务。">
    <meta name="keywords" content="个人中心，移动商城，中国移动通信，中国移动网上商城">
    <title>中国移动网上商城--个人中心</title>
    <link type="text/css" rel="stylesheet" href="${IMAGE_SERVER}cloud/static/user_center/css/all_c6a929c.css">
    <link type="text/css" rel="stylesheet" href="${IMAGE_SERVER}cloud/static/user_center/css/head1200.css">
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_center/css/stcmain_1ab76c9.css">
    <link type="text/css" rel="stylesheet" href="${IMAGE_SERVER}cloud/static/user_center/css/all_c6a929c.css">
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_center/js/base_1e4ead1.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_center/js/jquery-form_41314e0.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_center/js/requirepkg_d4d738d.js"></script>

    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_center/js/lc_search_5a8a14e.js"></script>
    <!--[if lte IE 9]>
    <script src="/i/service/html5shiv_f4d9dea.js"></script>
    <![endif]-->
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/appframe/kernel/css.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/css.js"></script>
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_center/css/ui-dialog_7c12633.css">
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_center/css/shop-ui-dialog_03f48b0.css">
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/componet_set_42306f9.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/componet_set_42306f9.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/js/head_456f66f.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/head_456f66f.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/js/tail_65e0761.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/tail_65e0761.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/tpl/easyentry_b448db8.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/easyentry_b448db8.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pmenu/menu_ea118dc.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/menu_ea118dc.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/user_c3137ab.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/user_c3137ab.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pmenu/js/menu_adb5acb.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/menu_adb5acb.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/ptop/ptop_50d35be.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/ptop_50d35be.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/myaccount_abb4732.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/myaccount_abb4732.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/js/myaccount_d3de9fe.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/myaccount_d3de9fe.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/js/fast_recharge_e3e3a83.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/fast_recharge_e3e3a83.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/mynews_d376d65.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/mynews_d376d65.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/shoppingcar/js/shoppingcar_d1d0a09.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/shoppingcar_d1d0a09.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/fee_74b5c82.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/fee_74b5c82.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/order_7f5a17e.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/order_7f5a17e.js"></script>
    <link rel="stylesheet" type="text/css" href="${IMAGE_SERVER}cloud/static/user_center/css/tail.css">
    <link rel="stylesheet" type="text/css" id="cssHead"
          href="${IMAGE_SERVER}cloud/static/user_center/css/head1200.css">
    <script type="text/javascript" charset="UTF-8"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/noticeTop_46a73d8.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/noticeTop_46a73d8.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/recharge_4d3f3eb.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/recharge_4d3f3eb.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/myfav_9d13add.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/myfav_9d13add.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="highcharts"
            src="${IMAGE_SERVER}cloud/static/user_center/js/highcharts_02e6a47.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/wish_7fbf0b5.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/wish_7fbf0b5.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/ptop/tpl/userinfo_2356e23.js"
            src="${IMAGE_SERVER}cloud/static/user_center/js/userinfo_2356e23.js"></script>
</head>
<body class="bg-f5">
<div id="stc-wrapper-top" class="stc-main-unappeare">
    <div class="ued-header ued-header-bg" id="stc_head">
        <div id="topbar" class="topbar">
            <div class="topbarcon">
                <div class="topleft">
                    <a id="tempBar0" href="http://www.chinamobileltd.com/?lang=en"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_ENGLISH&#39;);}">ENGLISH</a>
                    <a id="tempBar1" href="http://www.jl.10086.cn/power"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_ZQKH&#39;);}">政企客户</a>
                </div>
                <div class="topright">
                    <!--add by fenghy@20161215 购物车 start-->
                    <div class="dropdown div-shopping-trolley">
                        <a class="t4 dropdown-toggle " href="javascript:void(0);">购物车
                            <strong id="shoppingCarCount">0</strong>
                            <span></span>
                        </a>
                        <!--头部购物车列表  start-->
                        <div class="shopping-trolley-list"
                             style="border-top:none;border-bottom: 1px solid #eaeaea;background-color:#fff;"
                             id="headShoppingTrolley">
                        </div>
                        <!--头部购物车列表  end-->
                    </div>
                    <!--     ------购物车----end   -->
                    <span>|</span>
                    <div class="dropdown" id="divLogin"><span class="loginStr" id="loginStr" title="
            
                135****0153
            
      ">
            
                135****0153
            
      </span><a id="logout" class="login">[退出]</a><span id="mail"><span class="news-number-pic"></span><span
                                    class="news-number" id="newNumber">消息0</span></span></div>
                    <span>|</span>
                    <div class="dropdown" id="sjyyt">
                        <a class="t1 dropdown-toggle" id="tempBar2" href="http://www.10086.cn/cmccclient"
                           onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_SJYYT&#39;);}">手机营业厅</a>
                        <div class="dropdown-menu" id="yytbar" style="display: none;">
                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/ewm.jpg" id="yytbar-img"
                                 style="width: 100px; height: 100px;">
                            <p>扫一扫，随时查话费！</p>
                        </div>
                    </div>
                    <span>|</span>
                    <a id="tempBar3" href="http://jf.10086.cn/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_JFSC&#39;);}">积分商城</a>
                    <span>|</span>
                    <a id="tempBar4" href="http://www.10086.cn/aboutus/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_GYZGYD&#39;);}">关于中国移动</a>
                </div>
            </div>
        </div>
        <div class="container" id="container">
            <div id="middle" class="headcon">
                <div id="middleLeft" class="logocity">
                    <a class="logo" href="http://www.10086.cn/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_ZDH_LOGO&#39;);}">
                        <img src="${IMAGE_SERVER}cloud/static/user_center/images/logo.png" alt="中国移动欢迎您"
                             style="height: 42px; width: 230px;">
                    </a>
                    <div class="dropdown" style="z-index: 9999;">
                        <div class="topcity" id="dropdownMenu3">吉林</div>
                        <div class="topcity" id="dropdownMenu4">长春</div>
                    </div>
                </div>
                <div class="searchdiv">
                    <div class="searchbar input-group searchbar-hf">
                        <input value="" id="textkeywords" autocomplete="off" disableautocomplete="" class="form-control"
                               type="form-control" title="关键字必须至少有一个汉字或英文字母" name="qt" maxlength="20">
                        <ul id="textsearchKeyWord1598407968554" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchHistory1598407968554" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchKeyWord1466738567735" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchHistory1466738567735" class="search_toplist" style="display: none;"></ul>
                        <span class="input-group-btn span-hf">
										<input id="searchbtn" type="button"
                                               onclick="if (typeof(_tag)!= 'undefined&quot;){_tag.dcsMultiTrack(&quot;WT.event&quot;,&quot;INDEX_SS&quot;);}"
                                               class="btn btn-hf" value="搜索" style="font-size:14px">
									</span>
                    </div>
                    <div class="hot" id="texthotsearch"><a target="_blank" onclick="writeHotLog(this)" type=""
                                                           class="search_red fl"
                                                           href="http://www.10086.cn/5Gplus/?no_re=1">5G正式商用</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://shop.10086.cn/list/101_431_431_1_0_0_0_0_0_1_0.html?no_re=1">信用购机</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E7%A7%AF%E5%88%86%E5%85%91%E6%8D%A2&provinceId=431&cityId=431&from=10702&no_re=1">积分兑换</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E5%8D%8E%E4%B8%BAP30&provinceId=431&cityId=431&from=10702&no_re=1">华为P30</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_blue fl"
                                href="https://search.10086.cn/shop/list?key=4G%E6%B5%81%E9%87%8F%E5%8D%A1&provinceId=431&cityId=431&from=10702&no_re=1">4G流量卡</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E6%9C%8D%E5%8A%A1%E5%AF%86%E7%A0%81&provinceId=431&cityId=431&from=10702&no_re=1">服务密码</a>
                    </div>
                </div>
            </div>
            <div class="navbar">
                <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown" id="navTop4" style="width:219px;">
                            <a target="_blank" id="topA4" href="http://www.10086.cn/jl/">首页</a>
                        </li>
                        <li class="dropdown" id="navTop0">
                            <a target="_blank" class="dropdown-toggle" id="topA0"
                               href="http://shop.10086.cn/mall_431_431.html">移动商城
                                <ins></ins>
                            </a>
                            <div class="dropdown-menu" id="secMenu0" style="display: none;"><p><a target="_blank"
                                                                                                  onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_MSJ&#39;,false);}"
                                                                                                  href="http://shop.10086.cn/list/101_431_431_0_0_0_0.html">买手机</a>
                                </p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_BTC&#39;,false);}"
                                      href="http://shop.10086.cn/list/140_431_431_0_0_0_0.html">办套餐</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_BYW&#39;,false);}"
                                      href="http://shop.10086.cn/list/146_431_431_0_0_0_0.html">办业务</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_XHM&#39;,false);}"
                                      href="http://shop.10086.cn/list/128_431_431_0_0_0_0.html">挑配件</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_LJCZ&#39;,false);}"
                                      href="http://shop.10086.cn/i/?f=rechargecredit">立即充值</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_GRZX&#39;,false);}"
                                      href="http://shop.10086.cn/i/">个人中心</a></p></div>
                        </li>
                        <li class="dropdown" id="navTop1" style="border-top:2px solid #0085d0;height:38px;">
                            <a class="dropdown-toggle" id="topA1" style="height: 38px;">个人中心</a>
                        </li>
                        <li class="dropdown" id="navTop2">
                            <a target="_blank" class="dropdown-toggle" id="topA2"
                               href="http://shop.10086.cn/list/101_431_431_1_0_0_0_0_0_2_0.html">信用购机</a>
                        </li>
                        <li class="dropdown" id="navTop3"><a target="_blank" class="dropdown-toggle" id="topA3"
                                                             href="http://www.10086.cn/support/jl/">服务与支持</a>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="ued-location " id="stc_anchor">
        <a id="stc_shop_link" class="stc_crumb_a"
           href="https://login.10086.cn/SSOCheck.action?channelID=12002&backUrl=https://shop.10086.cn/">移动商城&nbsp;&gt;</a><a
                href="https://login.10086.cn/SSOCheck.action?channelID=12003&backUrl=https://shop.10086.cn/i/"
                id="stc_first_loc" class="pdlr-5 stc_crumb_a" style="display: none;">个人中心</a><span id="stc_first_arrow"
                                                                                                   style="display: none;">&gt;</span><span
                id="stc_second_loc" class="pdlr-5">个人中心</span>
    </div>
    <div class="ued-g1200 clearfix" id="mainContain">
        <div class="ued-side fl" id="mainMenu">
            <div class="ued-panel pd-10">
                <h3 class="ued-tit"><a id="shop_home" class="fwb fs-14 color-1" alis="home" code="070000">个人中心</a></h3>
                <div id="stcnavmenu">

                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>充值交费

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="rechargecredit" code="040300">话费充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelife" code="040900">生活缴费


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelove" code="040800">爱心充值

                                        <span class="new-func"></span>


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargegprs" code="040500">流量充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargeinterofth" code="040600">物联网充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargebroband" code="042000">宽带充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelandline" code="044000">固话充值


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="li-active list-second"><i></i>我的账户</a>
                            <ul class="list-c1-son" style="display:block;">

                                <li><a track-area="02" alis="mycoupons" code="020200">我的卡券</a></li>

                                <li><a track-area="02" alis="myfcode" code="020201">我的F码</a></li>

                                <li><a track-area="02" alis="billqry" code="020600">账单查询</a></li>

                                <li><a track-area="02" alis="billdetailqry" code="020700">详单查询</a></li>

                                <li><a track-area="02" alis="packremainqry" code="020400">套餐余量查询</a></li>

                                <li><a track-area="02" alis="busiqrydeal" code="020900">业务查询退订</a></li>

                                <li><a track-area="02" alis="pointqry" code="020300">积分明细查询</a></li>

                                <li><a track-area="02" alis="recharhisqry" code="020500">交费记录查询</a></li>

                                <li><a track-area="02" alis="setprotect" code="021500">呼死你-防护业务设置</a></li>

                                <li><a track-area="02" alis="belongqry" code="021000">归属地查询</a></li>

                                <li><a track-area="02" alis="haraprotect" code="021700">高频电话骚扰防护设置</a></li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的信息

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="custinfoqry" code="020800">个人信息


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="recaddrmag" code="010300">收货地址


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="passwordmg" code="060500" hlink="1">安全设置


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="invoicemag" code="010200">发票设置


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的订单

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="myorders" code="010600">商品订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="newBroadBandOrder" code="011500">宽带订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="mypreorders" code="010700">预购订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargerecord" code="010800">充值订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="myfav" code="010400">我的收藏


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="liferecharhisqry" code="011100">生活缴费订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="familyorder" code="011700">业务办理类订单


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的消息

                                <span class="news-noread-tip" style="display: none;"></span>

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="advicearrival" code="150100">消息订阅


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="mynews" code="150300">消息查看


                                        <span class="news-noread-tip" style="top: 0px; display: none;"></span>

                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="msgremind" code="150200">消息提醒设置


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>售后服务

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="myinvoice" code="120002">我的发票


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="returnorderqry" code="120001">退货申请/查询


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的邮箱

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="remail" code="130001">139邮箱


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                </div>
            </div>
            <!--<a class="mgt-10 none" href="javascript:void(0)" id="ggl"><img src=""/></a>-->
            <a class="mgt-10 none" href="javascript:void(0)" id="specProvince"><img
                        src="${IMAGE_SERVER}cloud/static/user_center/images/icon-211.png"></a>
            <a class="block mgt-10" href="javascript:void(0)" id="tocao">
                <!--<img src="/i/nresource/image/icon-11.png"/>--></a>
        </div>
        <div class="ued-main none" id="stc_opertaion_tip">
            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731" style="width:100%;height:109px;"
                 id="stc-module-banner">
        </div>
        <div class="ued-main" id="mainContent"><!--ued-panel star-->
            <div class="ued-panel">
                <div class="ued-grid mgb-10">
                    <div class="ued-g30 ued-gl" id="stc_home_banner">
                        <div class="ued-gbox bdr-1">
                            <div class="ued-top-wrap stc-one-line">
                                <div class="clearfix stc-one-line">
                                    <div class="ued-user fl" id="image-alert"><img
                                                style="border-radius:50%;cursor: pointer;"
                                                src="${IMAGE_SERVER}cloud/static/user_center/images/icon-user.jpg">
                                    </div>
                                    <!--<div class="ued-user js_lhlog fl" id="image-alert"><img style="border-radius:50%;"/></div>-->
                                </div>
                                <div class="ued-info stc-one-line">
                                    <!--ued-info-t star-->
                                    <div class="ued-info-t mgt-10 clearfix" id="stc_user_info">
                                        <span class="fl stc_top_welcome" id="stc_welcome">早上好，</span>
                                        <div class="ued-select fl js_select">
                                            <div>
      <span class="js_selItem selItem">
            
                135****0153
            
      </span>

                                                <span id="eyes" class="eyesclose"
                                                      style="width: 21px; height: 13px; display: inline-block; margin-left: 5px; cursor: pointer;"></span>


                                            </div>

                                        </div>
                                        <span class="fs-14" id="stc_careLang"></span>

                                    </div>
                                    <!--ued-info-b star-->
                                    <div class="ued-info-b" id="stc_user_acc" style="letter-spacing: 1px;">
                                        <ul class="clearfix fm-yahei">
                                            <li>
                                                <div class="vm js_hover2 rel">星级：<span class="rank"
                                                                                       id="stc_rank_info"><i
                                                                class="star pngfix"></i><i class="star pngfix"></i><i
                                                                class="star"></i><i class="star"></i><i
                                                                class="star"></i></span><span
                                                            class="fs-14 stc-level pdl-10">2星级</span>
                                                    <div class="ued-pop js_hoverCont"
                                                         style="opacity: 0.8; display: none;">星级得分：<span id="mylevel">175</span>
                                                    </div>
                                                </div>
                                            </li>
                                            <li class="pdl-0"><span
                                                        id="stc_user_bland">全球通</span>&nbsp;|&nbsp;当前套餐：<span
                                                        id="stc_cur_packages">4G飞享套餐58元（2019版）</span></li>
                                        </ul>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="ued-g30 ued-gl" id="stc_myaccount">
                        <div class="ued-gbox bdr-1 pdr-20 pd-10">
                            <h3 class="ued-tit">我的账户</h3>
                            <div class="mgt-20 myinfo">
                                <div class="clearfix mgt-10 ">
                                    <p class="fr"><span class="color-1 fs-18 inline-block mgr-10"
                                                        id="stc_balance">75.24</span><span
                                                id="stc_balance_unit">元</span><a href="javascript:;" class="bl-approve">交费&gt;</a>
                                    </p>
                                    可用余额：
                                </div>

                                <div class="clearfix mgt-15">
                                    <p class="fr"><span class="color-1 fs-18 inline-block mgr-10" id="stc_tolbalance">75.24</span><span
                                                id="stc_tolbalance_unit">元</span><a href="javascript:;"
                                                                                    class="bl-overall">账单&gt;</a></p>
                                    账户总余额
                                    <span class="ued-info2 rel js_info bg-tip-1" style="z-index: 11">
                <span style="width: 220px; left:-95px; top:25px;" class="ued-tag abs">
                    <em class="ued-cor-2"></em>
                    账户总余额包括可用余额、协议款余额、专项余额等
               </span>
            </span>：
                                </div>
                                <div class="clearfix mgt-15">
                                    <p class="fr"><span class="color-1 fs-18 inline-block mgr-10"
                                                        id="stc_real">58.00</span><span id="stc_real_unit">元</span><a
                                                href="javascript:;" class="bl-consume">详单&gt;</a></p>
                                    当月消费
                                    <span class="ued-info2 rel js_info bg-tip-1">
                <span style="width: 220px; left:-95px; top:25px;" class="ued-tag abs">
                    <em class="ued-cor-2"></em>
                    当月消费是本账期的一个消费总和
               </span>
            </span>：
                                </div>
                                <div class="clearfix mgt-15">
                                    <p class="fr"><span class="color-1 fs-18 inline-block mgr-10"
                                                        id="stc_point">3650</span><span id="stc_point_unit">分</span><a
                                                href="javascript:;" class="bl-integration"
                                                id="stc_point_jump">明细&gt;</a></p>
                                    我的积分：
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="ued-g40 ued-gr" id="stc_chargecent">
                        <div class="ued-gbox pd-10">
                            <div class="rel ued-tab-title js_ued_tab">
                                <ul class="nav-tab">
                                    <li class="curr w90"><a class="li-first fl fs-16">充话费</a></li>
                                    <li class="w90"><a class="fl fs-16">充流量</a></li>
                                </ul>
                                <div class="tab-arrow w60"></div>
                            </div>
                            <!--modify by fenghongye@20170122    start -->
                            <ul class="tab-content">
                                <li class="tab-pane on">
                                    <table class="ued-table-noborder mgt-10" cellspacing="0" cellpadding="0">
                                        <colgroup>
                                            <col width="80">
                                            <col>
                                        </colgroup>
                                        <tbody>
                                        <tr>
                                            <td class="pdt-10 pdb-10 pdl-0 pdr-0" width="90px">充值号码：</td>
                                            <td class="pdt-10 pdb-10" width="340"
                                                style="padding-left: 0px;padding-right:15px">
                                                <div class="select-box" style="position: relative">
                                                    <!--modify by zhangrui@20170719-->
                                                    <input type="text"
                                                           style="width: 140px; padding-top: 0px; height: 100%; color: rgb(51, 51, 51);"
                                                           class="ipt-style tel" sign="charge" value="" maxlength="11"
                                                           id="charge_tel" placeholder="请输入11位移动手机号码">
                                                    <label class="cred-arrow-1" id="charge_tel_err"
                                                           style="background: url(&quot;/i/nresource/image/icon-info.png&quot;) left 5px no-repeat;">长春</label>
                                                    <!-- <div class="phone abs" style="right:0;top:0"></div> -->
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="pdt-10 pdb-10 pdl-0 pdr-0" id="fare_amount" width="90px">充值金额：
                                            </td>
                                            <td class="pdt-10 pdb-10 rechargecredit-level" width="340"
                                                style="width:327px;padding-left: 0px;padding-right:0px">
                                                <p class="link-group fl" dif="1">
                                                    <!--modify by fenghy@20170228  档位值通过变量传递-->
                                                    <a href="javascript:void(0)" i="0" amount="50"
                                                       style="line-height: 30px;">50元</a>
                                                    <a href="javascript:void(0)" class="active" i="1" amount="100"
                                                       style="line-height: 30px;">100元</a>
                                                    <a href="javascript:void(0)" i="2" amount="300"
                                                       style="line-height: 30px;">300元</a>
                                                    <a href="javascript:void(0)" i="3" amount="500"
                                                       style="line-height: 30px;">500元</a>
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td class="color-1" id="min_discount">充值9.98折</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <div class="tc mgt-15">
                                        <button class="ued-btn" id="fare_btn">立即充值</button>
                                    </div>
                                </li>
                                <li class="tab-pane">
                                    <table class="ued-table-noborder mgt-10" cellspacing="0" cellpadding="0">
                                        <colgroup>
                                            <col width="80">
                                            <col>
                                        </colgroup>
                                        <tbody>
                                        <tr>
                                            <td class="pdt-10 pdb-10 pdl-0 pdr-0" width="90px">充值号码：</td>
                                            <td class="pdt-10 pdb-10" width="340"
                                                style="padding-left: 0px;padding-right:15px">
                                                <div class="select-box" style="position: relative">
                                                    <!--modify by zhangrui@20170719-->
                                                    <input type="text"
                                                           style="width: 140px; padding-top: 0px; height: 100%; color: rgb(51, 51, 51);"
                                                           class="ipt-style " sign="chargegprs" value="" maxlength="11"
                                                           id="chargegprs_tel" placeholder="请输入11位移动手机号码">
                                                    <label class="cred-arrow-1" id="chargegprs_tel_err"
                                                           style="background: url(&quot;/i/nresource/image/icon-info.png&quot;) left 5px no-repeat;">长春</label>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="pdt-10 pdb-10 pdl-0 pdr-0 pos-r" width="90px">
                                                <p class="pos-a" style="top:14px">充值档位：</p>
                                            </td>
                                            <td class="pdt-10 pdb-10" width="340"
                                                style="width:327px;padding-left: 0px;padding-right:0px">
                                                <p class="link-group fl rechargegprs-level">
                                                    <!--modify by fenghy@20170228  档位通过变量传递-->
                                                    <a href="javascript:void(0)" amount="300" class="mgb-10"
                                                       style="line-height: 30px;">300MB</a>
                                                    <a href="javascript:void(0)" amount="1024" class="active mgb-10"
                                                       style="line-height: 30px;">1G</a>
                                                    <a href="javascript:void(0)" amount="2048" class="mgb-10"
                                                       style="line-height: 30px;">2G</a>
                                                    <a href="javascript:void(0)" amount="3072" class="mgb-10"
                                                       style="line-height: 30px;">3G</a>
                                                    <a href="javascript:void(0)" amount="5120" class="mgb-10"
                                                       style="line-height: 30px;">5G</a>
                                                    <a href="javascript:void(0)" amount="10240" class="mgb-10"
                                                       style="line-height: 30px;">10G</a>
                                                    <a href="javascript:void(0)" amount="15360" class="mgb-10"
                                                       style="line-height: 30px;">15G</a>
                                                    <a href="javascript:void(0)" amount="30720" class="mgb-10"
                                                       style="line-height: 30px;">30G</a>
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td class="color-1" id=""></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <div class="tc">
                                        <button id="rechargegprs-btn" style="background-color:#0083d3;">立即充值</button>
                                    </div>
                                </li>
                            </ul>
                            <!--modify by fenghy@20170122         end-->
                        </div>

                    </div>
                </div>
            </div>
            <!--ued-panel star-->
            <div class="ued-panel pd-10 pdl-20 pdr-20 mgt-10" id="stc_packramin">
                <h3 class="ued-tit" id="stc_packramin_btn" style="cursor: pointer;">套餐余量</h3>
                <h3 class="ued-none-remain" id="show_msg"></h3>


                <div class="clearfix over-h mgl-50 mgt-5 pdt-30 ">
                    <span class="icon-meal icon-meal fl mgr-10"></span>
                    <span class="w120 fl" style="height:20px;line-height:20px">语音</span>
                    <!--Modify by tianhq@20160926-->

                    <span class="w80 fl mgr-10"
                          style="width:145px !important;height:20px;line-height:20px;margin-top:-2px;">共<span
                                class="fs-14">2400</span>分钟</span>


                    <div class="count-line fl mgt-5 mgr-20">
                        <div class="count-green rel" style="width:91%"><span>91%</span></div>
                    </div>


                    <span class="fl w120 mgt5" style="width:160px !important">剩余<span class="color-1 fs-14">2184</span>分钟</span>


                    <!-- <span class="fl">剩余日均<span class="color-1">20</span>分钟/天</span> -->
                </div>

                <div class="clearfix over-h mgl-50  pdt-30 pdb-20">
                    <span class="icon-meal icon-meal2 fl mgr-10"></span>
                    <span class="w120 fl" style="height:20px;line-height:20px">移动数据流量</span>
                    <!--Modify by tianhq@20160926-->


                    <span class="w80 fl mgr-10 fs-14"
                          style="width:145px !important;height:20px;line-height:20px;margin-top:-2px;">共<span
                                class="fs-14">40.00</span>GB</span>


                    <div class="count-line fl mgt-5 mgr-20">
                        <div class="count-green rel" style="width:95%"><span>95%</span></div>
                    </div>


                    <span class="fl w120 mgt5 fs-14" style="width:160px !important">剩余<span
                                class="color-1 fs-14">37.83</span>GB</span>


                    <!-- <span class="fl">剩余日均<span class="color-1">20</span>分钟/天</span> -->
                </div>


            </div>
            <!--ued-panel star-->
            <div class="ued-panel pd-10 pdl-20 pdr-20 mgt-10" id="stc_expnese_area">
                <h3 class="ued-tit">近六个月消费趋势<span class="color-4 mgl-25 fs-14">上月消费：<span class="color-1 fs-18"
                                                                                          id="stc_last_month">68.45</span><span
                                id="stc_last_month_unit">元</span></span><span class="color-4 mgl-15 fs-14">平均每月消费：<span
                                class="color-1 fs-18" id="stc_ava_expense">59.79</span>元</span></h3>

                <div id="chartline" class="mgt-15" style="height:190px;" data-highcharts-chart="0">
                    <div class="highcharts-container" id="highcharts-0"
                         style="position: relative; overflow: hidden; width: 985px; height: 190px; text-align: left; line-height: normal; z-index: 0; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
                        <svg version="1.1"
                             style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;"
                             xmlns="http://www.w3.org/2000/svg" width="985" height="190">
                            <desc>Created with Highcharts 4.0.3</desc>
                            <defs>
                                <lineargradient x1="0" y1="0" x2="0" y2="40" gradientUnits="userSpaceOnUse"
                                                id="highcharts-1">
                                    <stop offset="0" stop-color="#7687ff" stop-opacity="1"></stop>
                                    <stop offset="1" stop-color="#6a9eff" stop-opacity="1"></stop>
                                </lineargradient>
                                <clippath id="highcharts-2">
                                    <rect x="0" y="0" width="922" height="134"></rect>
                                </clippath>
                                <lineargradient x1="0" y1="0" x2="0" y2="1" id="highcharts-5">
                                    <stop offset="0" stop-color="#e3efff" stop-opacity="1"></stop>
                                    <stop offset="1" stop-color="#ffffff" stop-opacity="1"></stop>
                                </lineargradient>
                            </defs>
                            <rect x="0" y="0" width="985" height="190" strokeWidth="0" fill="#FFFFFF"
                                  class=" highcharts-background"></rect>
                            <g class="highcharts-grid" zIndex="1"></g>
                            <g class="highcharts-grid" zIndex="1">
                                <path fill="none" d="M 53 9.5 L 975 9.5" stroke="#C0C0C0" stroke-width="1"
                                      stroke-dasharray="4,3" zIndex="1" opacity="1"></path>
                                <path fill="none" d="M 53 77.5 L 975 77.5" stroke="#C0C0C0" stroke-width="1"
                                      stroke-dasharray="4,3" zIndex="1" opacity="1"></path>
                                <path fill="none" d="M 53 144.5 L 975 144.5" stroke="#C0C0C0" stroke-width="1"
                                      stroke-dasharray="4,3" zIndex="1" opacity="1"></path>
                            </g>
                            <g class="highcharts-axis" zIndex="2">
                                <path fill="none" d="M 53 144.5 L 975 144.5" stroke="#f8f8f8" stroke-width="1"
                                      zIndex="7" visibility="visible"></path>
                            </g>
                            <g class="highcharts-axis" zIndex="2"></g>
                            <g class="highcharts-series-group" zIndex="3">
                                <g class="highcharts-series" visibility="visible" zIndex="0.1"
                                   transform="translate(53,10) scale(1 1)" clip-path="url(#highcharts-2)">
                                    <path fill="url(#highcharts-5)"
                                          d="M 76.83333333333333 56.28 C 76.83333333333333 56.28 169.03333333333333 56.14599999999999 230.5 56.14599999999999 C 291.96666666666664 56.14599999999999 322.7 56.28 384.16666666666663 56.28 C 445.6333333333334 56.28 476.3666666666666 56.011999999999986 537.8333333333334 56.011999999999986 C 599.3 56.011999999999986 630.0333333333334 56.28 691.5 56.28 C 752.9666666666666 56.28 845.1666666666666 42.27699999999999 845.1666666666666 42.27699999999999 L 845.1666666666666 134 L 76.83333333333333 134"
                                          zIndex="0"></path>
                                    <path fill="none"
                                          d="M 76.83333333333333 56.28 C 76.83333333333333 56.28 169.03333333333333 56.14599999999999 230.5 56.14599999999999 C 291.96666666666664 56.14599999999999 322.7 56.28 384.16666666666663 56.28 C 445.6333333333334 56.28 476.3666666666666 56.011999999999986 537.8333333333334 56.011999999999986 C 599.3 56.011999999999986 630.0333333333334 56.28 691.5 56.28 C 752.9666666666666 56.28 845.1666666666666 42.27699999999999 845.1666666666666 42.27699999999999"
                                          stroke="#3c9cff" stroke-width="2" zIndex="1" stroke-linejoin="round"
                                          stroke-linecap="round"></path>
                                </g>
                                <g class="highcharts-markers" visibility="visible" zIndex="0.1"
                                   transform="translate(53,10) scale(1 1)" clip-path="none">
                                    <path fill="#3c9cff"
                                          d="M 845 38.27699999999999 C 850.328 38.27699999999999 850.328 46.27699999999999 845 46.27699999999999 C 839.672 46.27699999999999 839.672 38.27699999999999 845 38.27699999999999 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: visible;"></path>
                                    <path fill="#3c9cff"
                                          d="M 691 52.28 C 696.328 52.28 696.328 60.28 691 60.28 C 685.672 60.28 685.672 52.28 691 52.28 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: hidden;"></path>
                                    <path fill="#3c9cff"
                                          d="M 537 52.011999999999986 C 542.328 52.011999999999986 542.328 60.011999999999986 537 60.011999999999986 C 531.672 60.011999999999986 531.672 52.011999999999986 537 52.011999999999986 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: hidden;"></path>
                                    <path fill="#3c9cff"
                                          d="M 384 52.28 C 389.328 52.28 389.328 60.28 384 60.28 C 378.672 60.28 378.672 52.28 384 52.28 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: hidden;"></path>
                                    <path fill="#3c9cff"
                                          d="M 230 52.14599999999999 C 235.328 52.14599999999999 235.328 60.14599999999999 230 60.14599999999999 C 224.672 60.14599999999999 224.672 52.14599999999999 230 52.14599999999999 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: hidden;"></path>
                                    <path fill="#3c9cff"
                                          d="M 76 52.28 C 81.328 52.28 81.328 60.28 76 60.28 C 70.672 60.28 70.672 52.28 76 52.28 Z"
                                          stroke="#fff" stroke-width="3" style="visibility: hidden;"></path>
                                </g>
                            </g>
                            <g class="highcharts-axis-labels highcharts-xaxis-labels" zIndex="7">
                                <text x="129.83333333333331" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(153, 153, 153);"
                                      y="167" opacity="1">02月
                                </text>
                                <text x="283.5" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(153, 153, 153);"
                                      y="167" opacity="1">03月
                                </text>
                                <text x="437.1666666666667" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(153, 153, 153);"
                                      y="167" opacity="1">04月
                                </text>
                                <text x="590.8333333333333" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(153, 153, 153);"
                                      y="167" opacity="1">05月
                                </text>
                                <text x="744.5" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(153, 153, 153);"
                                      y="167" opacity="1">06月
                                </text>
                                <text x="898.1666666666666" text-anchor="middle"
                                      style="width: 134px; color: rgb(164, 164, 164); cursor: default; font-size: 15px; fill: rgb(0, 164, 255);"
                                      y="167" opacity="1">07月
                                </text>
                            </g>
                            <g class="highcharts-axis-labels highcharts-yaxis-labels" zIndex="7">
                                <text x="38" text-anchor="end"
                                      style="width:305px;color:#999999;cursor:default;font-size:15;fill:#999999;"
                                      y="147.5" opacity="1">0
                                </text>
                                <text x="38" text-anchor="end"
                                      style="width:305px;color:#999999;cursor:default;font-size:15;fill:#999999;"
                                      y="80.5" opacity="1">50
                                </text>
                                <text x="38" text-anchor="end"
                                      style="width:305px;color:#999999;cursor:default;font-size:15;fill:#999999;"
                                      y="13.5" opacity="1">100
                                </text>
                            </g>
                            <g class="highcharts-tooltip" zIndex="8"
                               style="cursor:default;padding:0;white-space:nowrap;" transform="translate(863,68)"
                               opacity="1" visibility="visible">
                                <path fill="none"
                                      d="M 5 0 L 29 0 35 -6 41 0 64 0 C 69 0 69 0 69 5 L 69 36 C 69 41 69 41 64 41 L 5 41 C 0 41 0 41 0 36 L 0 5 C 0 0 0 0 5 0"
                                      isShadow="true" stroke="black" stroke-opacity="0.049999999999999996"
                                      stroke-width="5" transform="translate(1, 1)" width="69" height="41"></path>
                                <path fill="none"
                                      d="M 5 0 L 29 0 35 -6 41 0 64 0 C 69 0 69 0 69 5 L 69 36 C 69 41 69 41 64 41 L 5 41 C 0 41 0 41 0 36 L 0 5 C 0 0 0 0 5 0"
                                      isShadow="true" stroke="black" stroke-opacity="0.09999999999999999"
                                      stroke-width="3" transform="translate(1, 1)" width="69" height="41"></path>
                                <path fill="none"
                                      d="M 5 0 L 29 0 35 -6 41 0 64 0 C 69 0 69 0 69 5 L 69 36 C 69 41 69 41 64 41 L 5 41 C 0 41 0 41 0 36 L 0 5 C 0 0 0 0 5 0"
                                      isShadow="true" stroke="black" stroke-opacity="0.15" stroke-width="1"
                                      transform="translate(1, 1)" width="69" height="41"></path>
                                <path fill="url(#highcharts-1)"
                                      d="M 5 0 L 29 0 35 -6 41 0 64 0 C 69 0 69 0 69 5 L 69 36 C 69 41 69 41 64 41 L 5 41 C 0 41 0 41 0 36 L 0 5 C 0 0 0 0 5 0"></path>
                                <text x="8" zIndex="1" style="font-size:16px;color:#fff;fill:#fff;" y="24">
                                    <tspan style="font-size: 12px;font-style:normal;">¥</tspan>
                                    <tspan dx="0">68.45</tspan>
                                </text>
                            </g>
                        </svg>
                    </div>
                </div>
            </div>
            <!--ued-panel star-->
            <div class="ued-panel pd-10 pdl-20 pdr-20 mgt-10 clearfix over-h" id="stc_order_area">
                <div class="fr">
                    <button class="ued-btn2 mgr-25" id="pre-order">预购订单</button>
                    <button class="ued-btn2" id="recharge-order">充值订单</button>
                </div>
                <span id="stc_myorders_btn" class="fs-16 mgt-3 fl">商品订单</span>
                <div class="point1 fl mgl-20 point-pp">待付款 <span class="color-3" id="order-wait">0</span>笔</div>
                <div class="point2 fl mgl-20 point-ss">已完成 <span class="color-3" id="order-ss">0</span>笔</div>
                <div class="point3 fl mgl-20 point-cl">已取消 <span class="color-3" id="order-cal">0</span>笔</div>
            </div>
            <!--ued-panel star-->
            <div class="ued-panel pd-10 pdl-20 pdr-20 mgt-10">
                <div class="ued-grid">
                    <div class="ued-g50 ued-gl" id="stc_myfav">
                        <div class="ued-gbox bdr-1 pdr-20">
                            <h3 id="stc_myfav_btn" class="ued-tit">我的收藏</h3>
                            <!--ued-viwe star-->
                            <div class="ued-viwe js_viwe h-200" style="text-align: center;height:200px;">


                                <div style="height:100px; text-align:center; padding:40px;">
                                    <div style="zoom: 1;display: inline-block;*display:inline;vertical-align: top;"><img
                                                src="${IMAGE_SERVER}cloud/static/user_center/images/myfav.png">
                                    </div>
                                    <div style="zoom: 1; display: inline-block; vertical-align: top;*display:inline; color: rgb(204, 204, 204); margin:9px 0 0 10px; text-align:left;">
                                        <div style="font-size: 12px;font-family: Microsoft YaHei;height: 30px;line-height: 30px;color:#dadada">
                                            您还未收藏任何商品呦
                                        </div>
                                        <div style="font-size: 12px;line-height: 25px;">赶快去<a class="store color-2"
                                                                                              target="_blank"
                                                                                              href="https://login.10086.cn/SSOCheck.action?channelID=12002&backUrl=https://shop.10086.cn/"
                                                                                              style="margin:0 5px;cursor:pointer; line-height:25px;text-decoration:none;">商城首页&gt;</a>看看吧
                                        </div>
                                    </div>
                                </div>


                            </div>
                            <!--ued-viwe end-->
                        </div>


                    </div>
                    <div class="ued-g50 ued-gr" id="stc_guesslove">
                        <div class="ued-gbox pdl-20">
                            <h3 class="ued-tit">猜你喜欢</h3>
                            <!--ued-viwe star-->
                            <div class="ued-viwe js_viwe" style="text-align: center;height:200px;">


                                <ul class="guess-love" id="guess_ul">


                                    <li>
                                        <a id="W15_rec_1_1044648_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1039586" skuinx="1"
                                           href="https://shop.10086.cn/goods/431_431_1044648_1039586.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1044648"
                                           _index="0">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t6q9kznxbwczczkc"
                                                 data-src="https://img1.shop.10086.cn/goods/t6q9kznxbwczczkc"
                                                 style="width:91px;height:91px;">
                                            <p class="">游戏玩家</p>
                                            <p class="mgt-5 color-1 bd">￥5.00</p>
                                        </a>


                                        <a id="W15_rec_2_1069184_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1049769" skuinx="2"
                                           href="https://shop.10086.cn/goods/431_431_1069184_1049769.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1069184"
                                           _index="1">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t7sun6n48y2ttn66u"
                                                 data-src="https://img1.shop.10086.cn/goods/t7sun6n48y2ttn66u"
                                                 style="width:91px;height:91px;">
                                            <p class="">咪咕圈圈会员</p>
                                            <p class="mgt-5 color-1 bd">￥5.00</p>
                                        </a>


                                        <a id="W15_rec_3_1060508_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1047951" skuinx="3"
                                           href="https://shop.10086.cn/goods/431_431_1060508_1047951.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1060508"
                                           _index="2">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t723q3xtu4ggttymhf"
                                                 data-src="https://img1.shop.10086.cn/goods/t723q3xtu4ggttymhf"
                                                 style="width:91px;height:91px;">
                                            <p class="">视频彩铃</p>
                                            <p class="mgt-5 color-1 bd">￥0.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_4_1044652_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1041744" skuinx="4"
                                           href="https://shop.10086.cn/goods/431_431_1044652_1041744.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1044652"
                                           _index="3">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t6q95pveq9qzxh22"
                                                 style="width:91px;height:91px;">
                                            <p class="">咪咕动漫</p>
                                            <p class="mgt-5 color-1 bd">￥3.00</p>
                                        </a>


                                        <a id="W15_rec_5_1014070_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1049770" skuinx="5"
                                           href="https://shop.10086.cn/goods/431_431_1014070_1049770.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1014070"
                                           _index="4">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t2yspp2grsubt9u5k"
                                                 style="width:91px;height:91px;">
                                            <p class="">和地图</p>
                                            <p class="mgt-5 color-1 bd">￥5.00</p>
                                        </a>


                                        <a id="W15_rec_6_1069185_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1049773" skuinx="6"
                                           href="https://shop.10086.cn/goods/431_431_1069185_1049773.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1069185"
                                           _index="5">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t7sur26nqpjttrvaf"
                                                 style="width:91px;height:91px;">
                                            <p class="">中国移动-12580</p>
                                            <p class="mgt-5 color-1 bd">￥3.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_7_1019512_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1014263" skuinx="7"
                                           href="https://shop.10086.cn/goods/431_431_1019512_1014263.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1019512"
                                           _index="6">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t274xkrr53df7r77v"
                                                 style="width:91px;height:91px;">
                                            <p class="">流量安心包</p>
                                            <p class="mgt-5 color-1 bd">￥0.00</p>
                                        </a>


                                        <a id="W15_rec_8_1044654_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1045342" skuinx="8"
                                           href="https://shop.10086.cn/goods/431_431_1044654_1045342.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1044654"
                                           _index="7">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t6q9ykrznmnzc7dd"
                                                 style="width:91px;height:91px;">
                                            <p class="">咪咕音乐</p>
                                            <p class="mgt-5 color-1 bd">￥4.00</p>
                                        </a>


                                        <a id="W15_rec_9_1069168_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1049728" skuinx="9"
                                           href="https://shop.10086.cn/goods/431_431_1069168_1049728.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1069168"
                                           _index="8">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t7suv23eut7tty2a2"
                                                 style="width:91px;height:91px;">
                                            <p class="">咪咕视频</p>
                                            <p class="mgt-5 color-1 bd">￥6.90</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_10_1064841_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1048829" skuinx="10"
                                           href="https://shop.10086.cn/goods/431_431_1064841_1048829.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1064841"
                                           _index="9">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/t77j783v3nxttqfgm"
                                                 style="width:91px;height:91px;">
                                            <p class="">网易态度包</p>
                                            <p class="mgt-5 color-1 bd">￥18.00</p>
                                        </a>


                                        <a id="W15_rec_11_1072482_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1064170" skuinx="11"
                                           href="https://shop.10086.cn/goods/431_431_1072482_1064170.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1072482"
                                           _index="10">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/th8ektxnutsttdtay"
                                                 style="width:91px;height:91px;">
                                            <p class="">OPPO Find X2 Pro兰博基尼版 12+512G手机 </p>
                                            <p class="mgt-5 color-1 bd">￥11999.00</p>
                                        </a>


                                        <a id="W15_rec_12_1077801_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1061870" skuinx="12"
                                           href="https://shop.10086.cn/goods/431_431_1077801_1061870.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1077801"
                                           _index="11">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/ths5j9zzvmedsm8n"
                                                 style="width:91px;height:91px;">
                                            <p class="">【优惠购机】vivo X30 5G 8+128G 全网通手机</p>
                                            <p class="mgt-5 color-1 bd">￥2399.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_13_1081266_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1064406" skuinx="13"
                                           href="https://shop.10086.cn/goods/431_431_1081266_1064406.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1081266"
                                           _index="12">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/th842cpak2stt24jd"
                                                 style="width:91px;height:91px;">
                                            <p class="">【华海创】华为新品P40 Pro 5G手机 8+256G </p>
                                            <p class="mgt-5 color-1 bd">￥6488.00</p>
                                        </a>


                                        <a id="W15_rec_14_1081783_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1065679" skuinx="14"
                                           href="https://shop.10086.cn/goods/431_431_1081783_1065679.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1081783"
                                           _index="13">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/thwg6rwd39jmpeqa"
                                                 style="width:91px;height:91px;">
                                            <p class="">vivo X50 128G/256G 5G版</p>
                                            <p class="mgt-5 color-1 bd">￥3198.00</p>
                                        </a>


                                        <a id="W15_rec_15_1074475_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1054645" skuinx="15"
                                           href="https://shop.10086.cn/goods/431_431_1074475_1054645.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1074475"
                                           _index="14">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/ta8smqapa2dttmsrx"
                                                 style="width:91px;height:91px;">
                                            <p class="">【熠天海纳】魅族16s 128GB 公开版4G智能手机</p>
                                            <p class="mgt-5 color-1 bd">￥3198.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_16_1075420_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1055904" skuinx="16"
                                           href="https://shop.10086.cn/goods/431_431_1075420_1055904.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1075420"
                                           _index="15">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/th3x2r76fxyttwggc"
                                                 style="width:91px;height:91px;">
                                            <p class="">华为nova5 8+128GB 公开版 4G智能手机</p>
                                            <p class="mgt-5 color-1 bd">￥2299.00</p>
                                        </a>


                                        <a id="W15_rec_17_1082353_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1067022" skuinx="17"
                                           href="https://shop.10086.cn/goods/431_431_1082353_1067022.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1082353"
                                           _index="16">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/th7zkuxff5qv8cm5"
                                                 style="width:91px;height:91px;">
                                            <p class="">【爱奇机】vivo Y3 标准版 3G+64/4+128GB</p>
                                            <p class="mgt-5 color-1 bd">￥799.00</p>
                                        </a>


                                        <a id="W15_rec_18_1078024_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1060268" skuinx="18"
                                           href="https://shop.10086.cn/goods/431_431_1078024_1060268.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1078024"
                                           _index="17">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/ths2xbr6phegey5"
                                                 style="width:91px;height:91px;">
                                            <p class="">【华创】荣耀20青春版 128G 全网通 4G拍照大屏手机</p>
                                            <p class="mgt-5 color-1 bd">￥1519.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_19_1075489_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1066369" skuinx="19"
                                           href="https://shop.10086.cn/goods/431_431_1075489_1066369.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1075489"
                                           _index="18">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/ths6m42z4enq673a"
                                                 style="width:91px;height:91px;">
                                            <p class="">华为新品 畅享20 Pro 6+128G 5G智能手机</p>
                                            <p class="mgt-5 color-1 bd">￥1699.00</p>
                                        </a>


                                        <a id="W15_rec_20_1077800_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1059870" skuinx="20"
                                           href="https://shop.10086.cn/goods/431_431_1077800_1059870.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1077800"
                                           _index="19">
                                            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"
                                                 data-src="https://img1.shop.10086.cn/goods/th84qbgznsttt2d9e"
                                                 style="width:91px;height:91px;">
                                            <p class="">【华海创】华为新品P40 5G手机 8+128G/8+256G </p>
                                            <p class="mgt-5 color-1 bd">￥4488.00</p>
                                        </a>
                                    </li>


                                    <li>
                                        <a id="W15_rec_1_1044648_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1039586" skuinx="1"
                                           href="https://shop.10086.cn/goods/431_431_1044648_1039586.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1044648"
                                           _index="0">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t6q9kznxbwczczkc"
                                                 data-src="https://img1.shop.10086.cn/goods/t6q9kznxbwczczkc"
                                                 style="width:91px;height:91px;">
                                            <p class="">游戏玩家</p>
                                            <p class="mgt-5 color-1 bd">￥5.00</p>
                                        </a>


                                        <a id="W15_rec_2_1069184_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1049769" skuinx="2"
                                           href="https://shop.10086.cn/goods/431_431_1069184_1049769.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1069184"
                                           _index="1">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t7sun6n48y2ttn66u"
                                                 data-src="https://img1.shop.10086.cn/goods/t7sun6n48y2ttn66u"
                                                 style="width:91px;height:91px;">
                                            <p class="">咪咕圈圈会员</p>
                                            <p class="mgt-5 color-1 bd">￥5.00</p>
                                        </a>


                                        <a id="W15_rec_3_1060508_b99c9f88b626424d957d7921f1ee8643" class="tc fl"
                                           target="_blank" skuid="1047951" skuinx="3"
                                           href="https://shop.10086.cn/goods/431_431_1060508_1047951.html?WT.ac=rec_search_009_431_b99c9f88b626424d957d7921f1ee8643_1060508"
                                           _index="2">
                                            <img src="${IMAGE_SERVER}cloud/static/user_center/images/t723q3xtu4ggttymhf"
                                                 data-src="https://img1.shop.10086.cn/goods/t723q3xtu4ggttymhf"
                                                 style="width:91px;height:91px;">
                                            <p class="">视频彩铃</p>
                                            <p class="mgt-5 color-1 bd">￥0.00</p>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="tab_pic_num" id="love-pro">
                                    <li class="arrowl"></li>
                                    <li class="arrowr"></li>
                                </ul>


                            </div>
                            <!--ued-viwe end-->
                        </div>


                    </div>
                </div>
            </div>
            <link type="text/css" rel="stylesheet"
                  href="${IMAGE_SERVER}cloud/static/user_center/css/home_7a48d81.css">

        </div>
        <div class="ued-main" id="stc_warm_tip">

        </div>
    </div>
    <div class="ued-footer mgt-10" id="stc_tail">
        <div class="footer">
            <div class="footcon"><p class="stc-footp"><a href="http://www.10086.cn/aboutus/news/">新闻中心</a><span>&nbsp;|&nbsp;</span><a
                            href="http://job.10086.cn/">诚聘英才</a><span>&nbsp;|&nbsp;</span><a
                            href="http://b2b.10086.cn/">采购信息</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/aboutus/hezuo/">企业合作</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/contact/">联系我们</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/navigation/">站点导航</a><span>&nbsp;|&nbsp;</span><a
                            href="http://labs.chinamobile.com/" target="_blank">中国移动研究院</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.cmdi.chinamobile.com/"
                            target="_blank">中国移动设计院</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.bj.10086.cn/sitemap">网站地图</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/links/">友情链接</a></p>
                <p class="stc-footp"><span>&nbsp;</span><span>掌上营业厅：</span><a
                            href="http://wap.10086.cn/">wap.10086.cn</a><span>&nbsp;语音自助服务：10086  短信营业厅：10086&nbsp;</span><a
                            href="http://www.10086.cn/support/channel/self_service/">自助终端</a><span>&nbsp;</span><a
                            href="http://www.10086.cn/support/channel/Entity1/">营业厅</a><span>&nbsp;</span><a
                            href="http://www.10086.cn/cmccclient/index.htm">手机营业厅下载</a></p>
                <p class="xuke">Copyright©1999-2020&nbsp;&nbsp;中国移动&nbsp;&nbsp;版权所有</p>
                <p class="xuke"><span>中华人民共和国增值电信业务经营许可证&nbsp;&nbsp;经营许可证编号：A2.B1.B2-20100001</span></p></div>
            <div class="footgov">
                <div id="KXWZ" class="kxyz"><span><a id="urlknet"
                                                     href="https://ss.knet.cn/verifyseal.dll?sn=e130905110100423008ilb000000&pa=500267"
                                                     target="_blank"><img
                                    alt="&#x53EF;&#x4FE1;&#x7F51;&#x7AD9;" name="KNET_seal"
                                    src="${IMAGE_SERVER}cloud/static/user_center/images/knetSealLogo.png"
                                    width="128" height="47" onclick="KNET_change(&#39;urlknet&#39;)"></a></span></div>
                <div class="govtxt"><p class="gov"><a href="http://www.miibeian.gov.cn/">京ICP备05002571号</a></p></div>
            </div>
        </div>
    </div>
    <div class="suspension_act canfloat" style="display: none; width: auto; right: 10px;" id="div_easy_entry">
        <!--快捷入口列表-->
        <div id="easyentry" class="suspension_con" style="width: 70px;float:right;">
            <div>
                <div class="stc-easy-entry-item stc-common-inline stc-easy-entry-itemsty-shoppingcar" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-item-shoppingcar" flag="inner"
                         ahref="javascript:void(0);">
                        <strong id="sideShoppingcarCount" class="shoppingcar-count">0</strong>
                    </div>
                    <div class="shopping-trolley-list side-shopping-list" id="sideShoppingTrolley">
                        <div class="side-shoplist-box">
                            <img style="margin: 5px auto;;width: 40px;height: 40px;"
                                 src="${IMAGE_SERVER}cloud/static/user_center/images/loading.gif">
                        </div>
                        <div class="blank-block"></div>
                    </div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-2 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/101_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-4 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/134_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-6 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/128_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-8 stc-easy-entry-other" flag="out"
                         ahref="https://shop.10086.cn/i/"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-10 stc-easy-entry-other" flag="inner"
                         ahref="http://shop.10086.cn/mall_431_431.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-14 stc-easy-entry-other" flag="out"
                         ahref="https://shop.10086.cn/ac/livechat-web-client/robertIndex?&channelType=1021&code=BS&tenantId=1000072"
                         id="order-online"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-12 stc-easy-entry-other" flag="inner"
                         ahref="javascript:scroll(0,0)"></div>
                </div>
                <div class="stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-love stc-easy-entry-other" flag="inner"
                         ahref="rechargelove"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="star-entry none" id="star_517_entry">
        <img src="${IMAGE_SERVER}cloud/static/user_center/images/img-517-star.png" width="80" height="80">
    </div>
</div>
<!-- #include virtual="/i/apps/pageapps/pfooter/index.html" -->
<!-- 弹框 遮罩层 -->
<div id="thick_bj"></div>
<!-- 新增弹框 -->
<div class="thick-content w500-t25" style="margin-left: -250px; margin-top: -85.5px;">
    <div class="thick-tit">
        <a class="fr mgt-15 mgr-15 js_x_close" href="javascript:void(0)"><img id="stc-change-img"
                                                                              src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"></a>
        修改头像
    </div>
    <div class="mgt-30" style="width:420px;margin:0 auto;">
        <p class="fs-18 color-11">推荐头像</p>
        <ul class="ued-list2 js_head_por" id="images-ul">

        </ul>
    </div>

    <div class="tc mgt-20 mgb-20">
        <button class="ued-btn8" id="save-image">保存头像</button>
    </div>
</div>
<script type="text/javascript">
    var _Constant = Namespace('all.constant');
    //var SHOPONLINE = true;//是否展示联系客服的按钮

    //将获取用户信息的替换掉。 @2016-06-26
    var getInfoSucc = function (data, app, stcDic) {
        $('#stc_shop_link').attr('href', stcDic.getShopLink());
        $('#stc_first_loc').attr('href', stcDic.getLoginaddr());
        //统一处理温馨提示及面包屑的问题，通过aop切面的形式
        require(["jqaop"], function (jqaop) {
            jqaop.aop.after({target: app, method: 'initpage'}, function (invocation) {
                var arg = this.initpage.arguments[0];
                //by zhongbin 2017/9/25 设置f码
                $('#mainContain').attr('data-f', arg);
                require(["/i/apps/pageapps/pwarm/stcSpecialPart_ba7ece1.js", "/i/service/model/componet_set_42306f9.js"], function (sspart, comSet) {
                    var item = arg;
                    //首次登录生活交费界面重置标识20170808 start
                    if (item == 'rechargelife') {
                        _Constant.FIRSTLOGINLIFEPAGE = true;
                    }
                    //end
                    if (comSet.isMenuItem(item)) {//判断是否属于菜单里边的内容
                        //修改点击后一级菜单不展开，同时二级菜单无选中颜色的问题 @2016-06-21
                        $(".list-c1-son>li>a").each(function (e, e1) {
                            $(e1).removeClass('color-2');
                            if ($(e1).attr('alis') == item) {
                                //$(e1).parent().parent().parent().addClass('js_list_active');
                                $(e1).addClass('color-2');
                                if (!$(e1).parent().parent().parent().children().eq(0).hasClass('li-active')) {
                                    $(e1).parent().parent().parent().children().eq(0).trigger('click');
                                }

                            }
                        });
                        var _obj = comSet.getObjectByName(item, 0);
                        _Constant.CURRFUNC = item;
                        _Constant.RCURRFUNCODE = (typeof _obj != "undefined" && _obj != null) ? _obj.funcode : null;
                        //修改面包屑去菜单的名称 @2016-04-16
                        var obj = comSet.getObjectByName(item, 0);
                        if (_Constant.CURRENTMENUS != '' && typeof _Constant.CURRENTMENUS != 'undefined') {
                            for (var i = 0; i < _Constant.CURRENTMENUS.menu.length; i++) {
                                if (typeof _Constant.CURRENTMENUS.menu[i].child != 'undefined') {
                                    for (var j = 0; j < _Constant.CURRENTMENUS.menu[i].child.length; j++) {
                                        if (item == _Constant.CURRENTMENUS.menu[i].child[j].inx) {
                                            obj = _Constant.CURRENTMENUS.menu[i].child[j];
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                        _Constant.CURRFUNCODE = obj.funcode;
                        sspart.getCrumbPart(item, obj);
                        if (obj.funcode != '042000') {//当宽带充值时不调用公共的温馨提示
                            sspart.getWarmTipPart(app.data[0].mobile, '', obj.funcode);
                        }
                        //运营位设置   @lujx 2017-09-04
                        var paras = {
                            'areaID': obj.funcode,
                            'provCode': '100',
                            'channel': '00',
                            mobile: app.data[0].mobile
                        };
                        sspart.getOperationInfo(paras, obj);
                    }
                });
            });
        });
        //modified by zhouhong 20161128 判断如果是积分支付结果页则切换帐号到充值的手机号 start
        //app.initpage('stcMenu',{mobile:data.loginValue,data:data});   //引入左侧菜单区域，增加菜单选中的效果
        var uri = require('uri');
        var pid = new uri(location.href).getQueryParamValue("f");
        var _p = new uri(location.href).getQueryParamValue("p");
        if (pid == "rechargejf" && _p == "1" && data.userType == "1") {
            var req_data = {};
            //处理url参数,将url中的所有参数都原数传递给接口
            if (__params.length > 0) {//__params在constant.js中
                for (var k in __params) {
                    req_data[__params[k][0]] = __params[k][1];
                }
            }
            require(["/i/service/model/recharge_4d3f3eb.js"], function (recharge) {
                recharge.getPayCallBack(req_data, function (pay_data) {
                    app.initpage('stcMenu', {mobile: pay_data.mobile, data: data});   //引入左侧菜单区域，增加菜单选中的效果
                }, function (code, msg) {
                    //own.showSelectMobile(userInfo);
                    app.initpage('stcMenu', {mobile: data.loginValue, data: data});
                }, function (status, msg) {
                    //own.showSelectMobile(userInfo);
                    app.initpage('stcMenu', {mobile: data.loginValue, data: data});
                });
            });
        } else {
            app.initpage('stcMenu', {mobile: data.loginValue, data: data});   //引入左侧菜单区域，增加菜单选中的效果
        }
        //modified by zhouhong 20161128 如果是积分支付结果页则切换帐号到充值的手机号 end
        if (typeof pid == 'undefined' || pid == '' || pid == 'home') {
            pid = 'home';
            $('#stc_first_loc').hide();
            $('#stc_first_arrow').hide();
            $('#stc_second_loc').html('个人中心');
            app.initpage(pid);
        }
        //插码调用
        stcEcode.startGlobalTrack(data);//插码,基本码
        require(["/i/apps/pageapps/pheader/js/head_456f66f.js", "/i/apps/pageapps/pheader/js/tail_65e0761.js", "/i/apps/pageapps/pheader/tpl/easyentry_b448db8.js"], function (head, tail, easy) {
            head.initHead(tail, easy, data);

//			add by fenghy@20161220   start
//			判断用户是否登录
            require(["appmanage", "/i/apps/serviceapps/shoppingcar/js/shoppingcar_d1d0a09.js", "cookie"], function (app, shoppingcar) {
                $.cookie('inx', 'myorders', {secure: true});
                $.cookie('inx2', 'returnorderqry', {secure: true});
                var req = {};
                if (app.data[0].data.userType == "2") {//未登录,获取购物车个数即可
                    shoppingcar.getShoppingCartNumber();
                } else {
                    req.userId = app.data[0].data.loginValue;
                    req.userType = app.data[0].data.userType;
                    req.tempKey = $.cookie('cart_code_key');
                    shoppingcar.mergeShoppingCarGoods(req);//已经登录,那么先合并购物车,再去调用购物车个数接口
                }
                shoppingcar.init();//购物车初始函数,主要是为dom元素绑定事件
            });
//			---------------end
        });
    };

    $(function () {
        require(["appmanage", "stcDic", "stcutil"], function (app, stcDic, stcutil) {
            var objurl = window.location.protocol + "//search.10086.cn/log_collecter/logCollecter.js";
            // stcutil.loadScript(objurl);
            //特殊节日添加背景的代码逻辑  @2016-06-27
            if (stcDic.duanWu() == '0') {
                $('body').addClass('bg-body');
                $('#stc_head').removeClass('ued-header-bg');
                //隐藏搜索框原有样式
                $(".searchbar-hf").addClass("searchbar2");
                $(".span-hf").addClass("input-group-btn1");
                $(".btn-hf").addClass("btn1");
                //因中秋皮肤与字体冲突，改动字体颜色，只中秋时生效
                $("#dropdownMenu3").addClass("temfestival");
                $("#dropdownMenu4").addClass("temfestival");
                $("#stc_anchor").addClass("temfestival");
            }
            require(["commonutil", "uri"], function (ajaxUtil, uri) {
                ajaxUtil.GET('/v1/auth/loginfo', {}, function (data) {
                    if (data.userType == '25' || data.userType == '26') {//25,26为接口返回的注册帐号绑定状态，一个为绑定了，一个为未绑定
                        data.userType = 1;
                        data.provice = '000'; //注册帐号的省份编码为000
                    } else if (parseInt(data.userType) == 4) {//手机号码,接口返回4,
                        data.userType = 0;
                    } else if (parseInt(data.userType) == 3) {//异网账号,接口返回3,//如果异网账号接入后需要修改类型的判断 @lujx 2019-03-15
                        data.userType = 1;
                        data.provice = '998'; //异网账号的省份编码为998
                    } else {
                        data.provice = '999'; //未登录的省份编码为999
                    }
                    var encryptToken = 'yxfmxifprj';
                    if (!$.isEmptyObject(data.encryptToken)) {
                        encryptToken = data.encryptToken;
                    }
                    sessionStorage.setItem('encryptToken', encryptToken);
                    getInfoSucc(data, app, stcDic);
                    $("#specProvince").on('click', function () {
                        window.location.href = "https://www.he.10086.cn/service/basicBusi/openAndClosePhone!init.action";
                    });
                }, function () {
                    sessionStorage.setItem('encryptToken', 'yxfmxifprj');
                    var posi = new uri(location.href).getQueryParamValue("f");
                    if (posi != null) {
                        if (stcutil.inArray(posi, stcDic.getNologinFun())) {
                            getInfoSucc(stcDic.getDefaultUserInfo(), app, stcDic);
                        } else {
                            /*$('#mainContent').empty();
                            $('#mainContent').addClass('bg-f1');
                            var temp = document.createElement('div');
                            $(temp).addClass('bg-main-err width-100 h-380');
                            $('#mainContent').append(temp);*/
                            app.initpage('stcMenu', {
                                mobile: stcDic.getDefaultUserInfo().loginValue,
                                data: stcDic.getDefaultUserInfo()
                            });
                            app.initpage("stcError");
                        }
                    } else {
                        app.initpage('stcMenu', {
                            mobile: stcDic.getDefaultUserInfo().loginValue,
                            data: stcDic.getDefaultUserInfo()
                        });
                        app.initpage("stcError");
                    }
                }, function () {
                    sessionStorage.setItem('encryptToken', 'yxfmxifprj');
                    var posi = new uri(location.href).getQueryParamValue("f");
                    var item = {"funCode": "999001", "operDesc": posi};//代表走进error的打点 @2016-09-22
                    var stcLog = require('stclog');
                    stcLog.info(null, item);
                    if (posi != null) {
                        if (stcutil.inArray(posi, stcDic.getNologinFun())) {
                            getInfoSucc(stcDic.getDefaultUserInfo(), app, stcDic);
                        } else {
                            app.initpage('stcMenu', {
                                mobile: stcDic.getDefaultUserInfo().loginValue,
                                data: stcDic.getDefaultUserInfo()
                            });
                            app.initpage("stcError");
                        }
                    } else {
                        app.initpage('stcMenu', {
                            mobile: stcDic.getDefaultUserInfo().loginValue,
                            data: stcDic.getDefaultUserInfo()
                        });
                        app.initpage("stcError");
                    }
                });
            });
            //打点日志
            require(["stclog"], function (stclog) {
                stclog.init();
            })
        })
    });
    var sus = $("div.suspension_act");
    var suspension_clo = $("div.suspension_clo");
    if (screen.width > 1024) {
        sus.css('right', '10px');
    } else {
        sus.css('right', '10px');
    }
    $(window).scroll(function () {//当页面滚动条变化时，执行的函数
//		var scrollTop = $(window).scrollTop(0);//禁止浏览器滚屏:浏览器窗口相对滚动条顶部的偏移为0
        var scrollTop = $(window).scrollTop();//当前滚动条滚动的距离
        if (scrollTop == 0) {
            sus.hide();//当滚动条置顶时，隐藏浮动菜单
        } else {
            sus.show();//当滚动条滚动时，显示浮动菜单
            sus.addClass("canfloat");//浮动菜单绝对定位于浏览器左侧正中
        }
    });


</script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/sub_1bc8e4c.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/sdc_mall_346a383.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/jquery.eraser.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/tripledes_c4dce8b.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/mode-ecb_851d991.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_center/js/aes_29b7e6b.js"></script>
<!--[if lte IE 9]>
<script src="/i/service/model/excanvas_c0cad58.js"></script>
<![endif]-->


<div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
    <div class="xl-chrome-ext-bar__logo"></div>

    <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
    <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
</div>
</body>
</html>