<!DOCTYPE html>
<!-- saved from url=(0053)https://shop.10086.cn/i/?f=home&welcome=1598407969731 -->
<html class="has-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="vertion" content="VERSION11">

    <meta name="twosize" content="true">
    <meta name="WT.LoginType" content="">
    <meta name="WT.event" content="">
    <meta name="WT.si_n" content="">
    <meta name="WT.cg_n" content="recaddrmag">
    <meta name="description"
          content="欢迎您访问中国移动网上商城个人中心。中国移动官方网站为您提供业务介绍，手机话费充值查询，套餐资费介绍及网上查询办理，号码购买，优惠购机，积分查询，优惠活动等网上自助服务。">
    <meta name="keywords" content="个人中心，移动商城，中国移动通信，中国移动网上商城">
    <title>中国移动网上商城--个人中心</title>
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_location/css/all_c6a929c.css">
    <link type="text/css" rel="stylesheet" href="${IMAGE_SERVER}cloud/static/user_location/css/head1200.css">
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_location/css/stcmain_1ab76c9.css">
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_location/css/all_c6a929c.css">
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_location/js/base_1e4ead1.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_location/js/jquery-form_41314e0.js"></script>
    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_location/js/requirepkg_d4d738d.js"></script>

    <script type="text/javascript" charset="utf-8"
            src="${IMAGE_SERVER}cloud/static/user_location/js/lc_search_5a8a14e.js"></script>
    <!--[if lte IE 9]>
    <script src="/i/service/html5shiv_f4d9dea.js"></script>
    <![endif]-->
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/appframe/kernel/css.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/css.js"></script>
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_location/css/ui-dialog_7c12633.css">
    <link type="text/css" rel="stylesheet"
          href="${IMAGE_SERVER}cloud/static/user_location/css/shop-ui-dialog_03f48b0.css">
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/componet_set_42306f9.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/componet_set_42306f9.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/js/head_456f66f.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/head_456f66f.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/js/tail_65e0761.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/tail_65e0761.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pheader/tpl/easyentry_b448db8.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/easyentry_b448db8.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pmenu/menu_ea118dc.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/menu_ea118dc.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/user_c3137ab.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/user_c3137ab.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pmenu/js/menu_adb5acb.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/menu_adb5acb.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/ptop/ptop_50d35be.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/ptop_50d35be.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/myaccount_abb4732.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/myaccount_abb4732.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/js/myaccount_d3de9fe.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/myaccount_d3de9fe.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/js/fast_recharge_e3e3a83.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/fast_recharge_e3e3a83.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/mynews_d376d65.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/mynews_d376d65.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/shoppingcar/js/shoppingcar_d1d0a09.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/shoppingcar_d1d0a09.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/fee_74b5c82.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/fee_74b5c82.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/order_7f5a17e.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/order_7f5a17e.js"></script>
    <link rel="stylesheet" type="text/css" href="${IMAGE_SERVER}cloud/static/user_location/css/tail.css">
    <link rel="stylesheet" type="text/css" id="cssHead"
          href="${IMAGE_SERVER}cloud/static/user_location/css/head1200.css">
    <script type="text/javascript" charset="UTF-8"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/noticeTop_46a73d8.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/noticeTop_46a73d8.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/recharge_4d3f3eb.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/recharge_4d3f3eb.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/home/tpl/myfav_9d13add.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/myfav_9d13add.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="highcharts"
            src="${IMAGE_SERVER}cloud/static/user_location/js/highcharts_02e6a47.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/wish_7fbf0b5.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/wish_7fbf0b5.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/ptop/tpl/userinfo_2356e23.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/userinfo_2356e23.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pwarm/stcSpecialPart_ba7ece1.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/stcSpecialPart_ba7ece1.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/addr/js/addr_f382683.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/addr_f382683.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/model/address_fbe3f1c.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/address_fbe3f1c.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pwarm/tpl/warmtip_444a516.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/warmtip_444a516.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/pageapps/pwarm/tpl/noractivy_661d963.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/noractivy_661d963.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/service/checkbox_radio_copy_306f60e.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/checkbox_radio_copy_306f60e.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/addr/tpl/province_3d57317.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/province_3d57317.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_"
            data-requiremodule="/i/apps/serviceapps/addr/tpl/addrsinfo_9a421ae.js"
            src="${IMAGE_SERVER}cloud/static/user_location/js/addrsinfo_9a421ae.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="btncommit"
            src="${IMAGE_SERVER}cloud/static/user_location/js/btncommit_56ee244.js"></script>
</head>
<body class="bg-f5">
<div id="stc-wrapper-top" class="stc-main-unappeare">
    <div class="ued-header ued-header-bg" id="stc_head">
        <div id="topbar" class="topbar">
            <div class="topbarcon">
                <div class="topleft">
                    <a id="tempBar0" href="http://www.chinamobileltd.com/?lang=en"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_ENGLISH&#39;);}">ENGLISH</a>
                    <a id="tempBar1" href="http://www.jl.10086.cn/power"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_ZQKH&#39;);}">政企客户</a>
                </div>
                <div class="topright">
                    <!--add by fenghy@20161215 购物车 start-->
                    <div class="dropdown div-shopping-trolley">
                        <a class="t4 dropdown-toggle " href="javascript:void(0);">购物车
                            <strong id="shoppingCarCount">0</strong>
                            <span></span>
                        </a>
                        <!--头部购物车列表  start-->
                        <div class="shopping-trolley-list"
                             style="border-top:none;border-bottom: 1px solid #eaeaea;background-color:#fff;"
                             id="headShoppingTrolley">
                        </div>
                        <!--头部购物车列表  end-->
                    </div>
                    <!--     ------购物车----end   -->
                    <span>|</span>
                    <div class="dropdown" id="divLogin"><span class="loginStr" id="loginStr" title="
            
                135****0153
            
      ">
            
                135****0153
            
      </span><a id="logout" class="login">[退出]</a><span id="mail"><span class="news-number-pic"></span><span
                                    class="news-number" id="newNumber">消息0</span></span></div>
                    <span>|</span>
                    <div class="dropdown" id="sjyyt">
                        <a class="t1 dropdown-toggle" id="tempBar2" href="http://www.10086.cn/cmccclient"
                           onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_SJYYT&#39;);}">手机营业厅</a>
                        <div class="dropdown-menu" id="yytbar" style="display: none;">
                            <img src="${IMAGE_SERVER}cloud/static/user_location/images/ewm.jpg"
                                 id="yytbar-img" style="width: 100px; height: 100px;">
                            <p>扫一扫，随时查话费！</p>
                        </div>
                    </div>
                    <span>|</span>
                    <a id="tempBar3" href="http://jf.10086.cn/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_JFSC&#39;);}">积分商城</a>
                    <span>|</span>
                    <a id="tempBar4" href="http://www.10086.cn/aboutus/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_TOP_GYZGYD&#39;);}">关于中国移动</a>
                </div>
            </div>
        </div>
        <div class="container" id="container">
            <div id="middle" class="headcon">
                <div id="middleLeft" class="logocity">
                    <a class="logo" href="http://www.10086.cn/"
                       onclick="javascript:if(typeof(_tag)!= &#39;undefined&#39;){_tag.dcsMultiTrack(&#39;WT.event&#39;,&#39;INDEX_ZDH_LOGO&#39;);}">
                        <img src="${IMAGE_SERVER}cloud/static/user_location/images/logo.png" alt="中国移动欢迎您"
                             style="height: 42px; width: 230px;">
                    </a>
                    <div class="dropdown" style="z-index: 9999;">
                        <div class="topcity" id="dropdownMenu3">吉林</div>
                        <div class="topcity" id="dropdownMenu4">长春</div>
                    </div>
                </div>
                <div class="searchdiv">
                    <div class="searchbar input-group searchbar-hf">
                        <input value="" id="textkeywords" autocomplete="off" disableautocomplete="" class="form-control"
                               type="form-control" title="关键字必须至少有一个汉字或英文字母" name="qt" maxlength="20">
                        <ul id="textsearchKeyWord1598407968554" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchHistory1598407968554" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchKeyWord1466738567735" class="search_toplist" style="display: none;"></ul>
                        <ul id="textsearchHistory1466738567735" class="search_toplist" style="display: none;"></ul>
                        <span class="input-group-btn span-hf">
										<input id="searchbtn" type="button"
                                               onclick="if (typeof(_tag)!= 'undefined'){_tag.dcsMultiTrack('WT.event',&quot;INDEX_SS&quot;);}"
                                               class="btn btn-hf" value="搜索" style="font-size:14px">
									</span>
                    </div>
                    <div class="hot" id="texthotsearch"><a target="_blank" onclick="writeHotLog(this)" type=""
                                                           class="search_red fl"
                                                           href="http://www.10086.cn/5Gplus/?no_re=1">5G正式商用</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://shop.10086.cn/list/101_431_431_1_0_0_0_0_0_1_0.html?no_re=1">信用购机</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E7%A7%AF%E5%88%86%E5%85%91%E6%8D%A2&provinceId=431&cityId=431&from=10702&no_re=1">积分兑换</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E5%8D%8E%E4%B8%BAP30&provinceId=431&cityId=431&from=10702&no_re=1">华为P30</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_blue fl"
                                href="https://search.10086.cn/shop/list?key=4G%E6%B5%81%E9%87%8F%E5%8D%A1&provinceId=431&cityId=431&from=10702&no_re=1">4G流量卡</a><a
                                target="_blank" onclick="writeHotLog(this)" type="" class="search_red fl"
                                href="https://search.10086.cn/shop/list?key=%E6%9C%8D%E5%8A%A1%E5%AF%86%E7%A0%81&provinceId=431&cityId=431&from=10702&no_re=1">服务密码</a>
                    </div>
                </div>
            </div>
            <div class="navbar">
                <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown" id="navTop4" style="width:219px;">
                            <a target="_blank" id="topA4" href="http://www.10086.cn/jl/">首页</a>
                        </li>
                        <li class="dropdown" id="navTop0">
                            <a target="_blank" class="dropdown-toggle" id="topA0"
                               href="http://shop.10086.cn/mall_431_431.html">移动商城
                                <ins></ins>
                            </a>
                            <div class="dropdown-menu" id="secMenu0" style="display: none;"><p><a target="_blank"
                                                                                                  onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_MSJ&#39;,false);}"
                                                                                                  href="http://shop.10086.cn/list/101_431_431_0_0_0_0.html">买手机</a>
                                </p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_BTC&#39;,false);}"
                                      href="http://shop.10086.cn/list/140_431_431_0_0_0_0.html">办套餐</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_BYW&#39;,false);}"
                                      href="http://shop.10086.cn/list/146_431_431_0_0_0_0.html">办业务</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_XHM&#39;,false);}"
                                      href="http://shop.10086.cn/list/128_431_431_0_0_0_0.html">挑配件</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_LJCZ&#39;,false);}"
                                      href="http://shop.10086.cn/i/?f=rechargecredit">立即充值</a></p>
                                <p><a target="_blank"
                                      onclick="javascript:if(true){stcEcode.commTrack(&#39;UCenter_Title_GRZX&#39;,false);}"
                                      href="http://shop.10086.cn/i/">个人中心</a></p></div>
                        </li>
                        <li class="dropdown" id="navTop1" style="border-top:2px solid #0085d0;height:38px;">
                            <a class="dropdown-toggle" id="topA1" style="height: 38px;">个人中心</a>
                        </li>
                        <li class="dropdown" id="navTop2">
                            <a target="_blank" class="dropdown-toggle" id="topA2"
                               href="http://shop.10086.cn/list/101_431_431_1_0_0_0_0_0_2_0.html">信用购机</a>
                        </li>
                        <li class="dropdown" id="navTop3"><a target="_blank" class="dropdown-toggle" id="topA3"
                                                             href="http://www.10086.cn/support/jl/">服务与支持</a>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="ued-location " id="stc_anchor">
        <a id="stc_shop_link" class="stc_crumb_a"
           href="https://login.10086.cn/SSOCheck.action?channelID=12002&backUrl=https://shop.10086.cn/">移动商城&nbsp;&gt;</a><a
                href="https://login.10086.cn/SSOCheck.action?channelID=12003&backUrl=https://shop.10086.cn/i/"
                id="stc_first_loc" class="pdlr-5 stc_crumb_a" style="display: inline;">个人中心</a><span
                id="stc_first_arrow" style="display: inline;">&gt;</span><span id="stc_second_loc"
                                                                               class="pdlr-5">收货地址</span>
    </div>
    <div class="ued-g1200 clearfix" id="mainContain" data-f="recaddrmag">
        <div class="ued-side fl" id="mainMenu">
            <div class="ued-panel pd-10">
                <h3 class="ued-tit"><a id="shop_home" class="fwb fs-14 color-1" alis="home" code="070000">个人中心</a></h3>
                <div id="stcnavmenu">

                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>充值交费

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="rechargecredit" code="040300">话费充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelife" code="040900">生活缴费


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelove" code="040800">爱心充值

                                        <span class="new-func"></span>


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargegprs" code="040500">流量充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargeinterofth" code="040600">物联网充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargebroband" code="042000">宽带充值


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargelandline" code="044000">固话充值


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="li-active list-second"><i></i>我的账户</a>
                            <ul class="list-c1-son" style="display:block;">

                                <li><a track-area="02" alis="mycoupons" code="020200">我的卡券</a></li>

                                <li><a track-area="02" alis="myfcode" code="020201">我的F码</a></li>

                                <li><a track-area="02" alis="billqry" code="020600">账单查询</a></li>

                                <li><a track-area="02" alis="billdetailqry" code="020700">详单查询</a></li>

                                <li><a track-area="02" alis="packremainqry" code="020400">套餐余量查询</a></li>

                                <li><a track-area="02" alis="busiqrydeal" code="020900">业务查询退订</a></li>

                                <li><a track-area="02" alis="pointqry" code="020300">积分明细查询</a></li>

                                <li><a track-area="02" alis="recharhisqry" code="020500">交费记录查询</a></li>

                                <li><a track-area="02" alis="setprotect" code="021500">呼死你-防护业务设置</a></li>

                                <li><a track-area="02" alis="belongqry" code="021000">归属地查询</a></li>

                                <li><a track-area="02" alis="haraprotect" code="021700">高频电话骚扰防护设置</a></li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second li-active"><i></i>我的信息

                            </a>
                            <ul class="list-c1-son" style="display: block;">

                                <li>
                                    <a track-area="02" alis="custinfoqry" code="020800">个人信息


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="recaddrmag" code="010300" class="color-2">收货地址


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="passwordmg" code="060500" hlink="1">安全设置


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="invoicemag" code="010200">发票设置


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的订单

                            </a>
                            <ul class="list-c1-son" style="display: none;">

                                <li>
                                    <a track-area="02" alis="myorders" code="010600">商品订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="newBroadBandOrder" code="011500">宽带订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="mypreorders" code="010700">预购订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="rechargerecord" code="010800">充值订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="myfav" code="010400">我的收藏


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="liferecharhisqry" code="011100">生活缴费订单


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="familyorder" code="011700">业务办理类订单


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的消息

                                <span class="news-noread-tip" style="display: none;"></span>

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="advicearrival" code="150100">消息订阅


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="mynews" code="150300">消息查看


                                        <span class="news-noread-tip" style="top: 0px; display: none;"></span>

                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="msgremind" code="150200">消息提醒设置


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>售后服务

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="myinvoice" code="120002">我的发票


                                    </a>
                                </li>

                                <li>
                                    <a track-area="02" alis="returnorderqry" code="120001">退货申请/查询


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                    <ul class="list-c1 js_list_active">
                        <li>
                            <a class="list-second"><i></i>我的邮箱

                            </a>
                            <ul class="list-c1-son">

                                <li>
                                    <a track-area="02" alis="remail" code="130001">139邮箱


                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>


                </div>
            </div>
            <!--<a class="mgt-10 none" href="javascript:void(0)" id="ggl"><img src=""/></a>-->
            <a class="mgt-10 none" href="javascript:void(0)" id="specProvince"><img
                        src="${IMAGE_SERVER}cloud/static/user_location/images/icon-211.png"></a>
            <a class="block mgt-10" href="javascript:void(0)" id="tocao">
                <!--<img src="/i/nresource/image/icon-11.png"/>--></a>
        </div>
        <div class="ued-main none" id="stc_opertaion_tip">
            <img src="https://shop.10086.cn/i/?f=home&welcome=1598407969731" style="width:100%;height:109px;"
                 id="stc-module-banner">
        </div>
        <div class="ued-main" id="mainContent"><!--
	作者：guoxx
	时间：2016-02-04
	描述：  收货地址
-->
            <div class="ued-panel pd-10 pdl-20 pdr-20">
                <h3 class="ued-tit">收货地址</h3>
                <form id="acceptpersonform">
                    <table class="ued-table-noborder mgt-10" cellspacing="0" cellpadding="0">
                        <colgroup>
                            <col width="120">
                            <col>
                        </colgroup>
                        <tbody class="test">
                        <tr>
                            <td class="tr"><span class="color-1 mgr-10">*</span>收货人：</td>
                            <td class="pdt-10 pdb-10" id="acceptPersonAddr">
                                <input type="text" class="ued-iptBig2 w280 " name="name" placeholder="请输入收货人姓名"
                                       id="name_input">
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12" id="name_tip_err"
                                      style="display: none;">请输入收货人姓名</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="tr"><span class="color-1 mgr-10">*</span>所在地区：</td>
                            <td class="pdt-10 pdb-10">
                                <div class="ued-select2 ued-select3 fl mgr-10 js_select2" style="width:272px;">
                                    <input class="ued-text" readonly="readonly" id="province_span" pcid=""
                                           placeholder="请选择省市区">
                                    <span class="tag-select"></span>
                                    <div class="none prov-box-top clearfix">
                                        <p class="prov_box_size active">省份</p>
                                        <p class="prov_box_size">城市</p>
                                        <p class="prov_box_size">县区</p>
                                    </div>
                                    <div class="prov-box none">
                                        <div class="region_list" depth="0" style="display: block;">
                                            <div class="clearfix col-box">
                                                <div class="sort">A-G</div>
                                                <div class="sort_list">
                                                    <a pcid="110000" class="ac_location_region"
                                                       href="javascript:void(0)">北京</a>
                                                    <a pcid="340000" class="ac_location_region"
                                                       href="javascript:void(0)">安徽</a>
                                                    <a pcid="500000" class="ac_location_region"
                                                       href="javascript:void(0)">重庆</a>
                                                    <a pcid="350000" class="ac_location_region"
                                                       href="javascript:void(0)">福建</a>
                                                    <a pcid="440000" class="ac_location_region"
                                                       href="javascript:void(0)">广东</a>
                                                    <a pcid="450000" class="ac_location_region"
                                                       href="javascript:void(0)">广西</a>
                                                    <a pcid="620000" class="ac_location_region"
                                                       href="javascript:void(0)">甘肃</a>
                                                    <a pcid="520000" class="ac_location_region"
                                                       href="javascript:void(0)">贵州</a>
                                                </div>
                                            </div>
                                            <div class="clearfix col-box">
                                                <div class="sort">H-J</div>
                                                <div class="sort_list">
                                                    <a pcid="130000" class="ac_location_region"
                                                       href="javascript:void(0)">河北</a>
                                                    <a pcid="410000" class="ac_location_region"
                                                       href="javascript:void(0)">河南</a>
                                                    <a pcid="230000" class="ac_location_region"
                                                       href="javascript:void(0)">黑龙江</a>
                                                    <a pcid="460000" class="ac_location_region"
                                                       href="javascript:void(0)">海南</a>
                                                    <a pcid="420000" class="ac_location_region"
                                                       href="javascript:void(0)">湖北</a>
                                                    <a pcid="430000" class="ac_location_region"
                                                       href="javascript:void(0)">湖南</a>
                                                    <a pcid="220000" class="ac_location_region"
                                                       href="javascript:void(0)">吉林</a>
                                                    <a pcid="320000" class="ac_location_region"
                                                       href="javascript:void(0)">江苏</a>
                                                    <a pcid="360000" class="ac_location_region"
                                                       href="javascript:void(0)">江西</a>
                                                </div>
                                            </div>
                                            <div class="clearfix col-box">
                                                <div class="sort">L-S</div>
                                                <div class="sort_list">
                                                    <a pcid="210000" class="ac_location_region"
                                                       href="javascript:void(0)">辽宁</a>
                                                    <a pcid="640000" class="ac_location_region"
                                                       href="javascript:void(0)">宁夏</a>
                                                    <a pcid="150000" class="ac_location_region"
                                                       href="javascript:void(0)">内蒙古</a>
                                                    <a pcid="630000" class="ac_location_region"
                                                       href="javascript:void(0)">青海</a>
                                                    <a pcid="310000" class="ac_location_region"
                                                       href="javascript:void(0)">上海</a>
                                                    <a pcid="510000" class="ac_location_region"
                                                       href="javascript:void(0)">四川</a>
                                                    <a pcid="370000" class="ac_location_region"
                                                       href="javascript:void(0)">山东</a>
                                                    <a pcid="140000" class="ac_location_region"
                                                       href="javascript:void(0)">山西</a>
                                                    <a pcid="610000" class="ac_location_region"
                                                       href="javascript:void(0)">陕西</a>
                                                </div>
                                            </div>
                                            <div class="clearfix col-box">
                                                <div class="sort">T-Z</div>
                                                <div class="sort_list">
                                                    <a pcid="120000" class="ac_location_region"
                                                       href="javascript:void(0)">天津</a>
                                                    <a pcid="650000" class="ac_location_region"
                                                       href="javascript:void(0)">新疆</a>
                                                    <a pcid="540000" class="ac_location_region"
                                                       href="javascript:void(0)">西藏</a>
                                                    <a pcid="530000" class="ac_location_region"
                                                       href="javascript:void(0)">云南</a>
                                                    <a pcid="330000" class="ac_location_region"
                                                       href="javascript:void(0)">浙江</a>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="region_list" depth="1"
                                             style="display: none; padding-left: 41px;padding-top: 10px;">

                                        </div>
                                        <div class="region_list" depth="2"
                                             style="display: none; padding-left: 41px;padding-top: 10px;">
                                        </div>
                                    </div>
                                </div>
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12"
                                      id="region_tip_err" style="display: none;">地址信息不完整</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="tr"><span class="color-1 mgr-10 ">*</span>详细地址：</td>
                            <td class="pdt-10 pdb-10">
                                <span id="detail_pro"></span>
                                <input type="text" class="ued-iptBig2 w280 " name="street" placeholder="请输入详细地址"
                                       id="addr_detail">
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12"
                                      id="addr_detail_tip_err" style="display: none;">请输入详细地址</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="tr">手机号码：</td>
                            <td class="pdt-10 pdb-10">
                                <input type="text" class="ued-iptBig2 w280 " name="telphone" placeholder="请输入手机号码"
                                       maxlength="11" id="tel_input">
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12" id="tel_tip_err"
                                      style="display: none;">手机和固定电话至少填写一个</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="tr">固话号码：</td>
                            <td class="pdt-10 pdb-10" id="g_phone">
                                <input type="text" class="ued-iptBig2" maxlength="4" style="width: 40px;"
                                       name="area_num" placeholder="区号" id="area_num"> - <input type="text"
                                                                                                class="ued-iptBig2"
                                                                                                maxlength="8"
                                                                                                style="width:80px;"
                                                                                                name="phone_num"
                                                                                                placeholder="电话号码"
                                                                                                id="phone_num"> - <input
                                        type="text" class="ued-iptBig2" maxlength="5" style="width:50px;"
                                        placeholder="分机号" name="extension_num" id="extension_num">
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12"
                                      id="phone_tip_err" style="display: none;">手机和固定电话至少填写一个</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="tr">邮政编码：</td>
                            <td class="pdt-10 pdb-10">
                                <input type="text" class="ued-iptBig2 w280 " name="zipCode" placeholder="请输入邮政编码"
                                       maxlength="6" id="zip_code">
                                <span class="color-1 mgl-10 tip-err-middle tip-comm-bg-1 pdl-20 fs-12"
                                      id="zip_code_tip_err" style="display: none;">请输入邮政编码</span>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="pdt-10 pdb-10">
                                <!-- 模拟多选框 for属性对应input id;ID不能重复 -->
                                <label class="checkbox mgr-20" for="ver-1" id="checkbox_lab"><span
                                            class="icon"></span><span class="icon-to-fade"></span>
                                    <input type="checkbox" id="ver-1" name="default_lab" value="0">设为默认<span
                                            class="icon"></span><span class="icon-to-fade"></span></label>
                                <label class="checkbox mgr-20 mgl-23" for="ver-2" id="checkbox_lab2"><span
                                            class="icon"></span><span class="icon-to-fade"></span>
                                    <input type="checkbox" id="ver-2" name="default_lab2" value="0">设为一键购<span
                                            class="icon"></span><span class="icon-to-fade"></span></label>
                            </td>
                        </tr>
                        <tr class="addr_save">
                            <td></td>
                            <td class="pdt-10 pdb-10 "><input class="ued-btn" type="button" name="addr_submit"
                                                              id="addr_submit" value="保存"></td>
                        </tr>
                        <tr class="addr_modify" style="display: none;">
                            <td></td>
                            <td class="pdt-10 pdb-10 "><input type="button" class="ued-btn" name="addr_modify"
                                                              id="addr_modify" value="修改"><input type="button"
                                                                                                 class="ued-btn"
                                                                                                 name="addr_cancel"
                                                                                                 id="addr_cancel"
                                                                                                 value="取消"
                                                                                                 style="margin-left: 20px;">
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
                <p class="mgt-30 color-1">已保存了<span id="addrs_num">1</span>条地址，最多只能保存<span id="addrs_limit">20</span>条地址
                </p>
                <table width="100%" cellspacing="0" cellpadding="0" border="0" class="ued-table mgt-20">
                    <!--<colgroup><col width="145" /><col /><col width="145" /></colgroup>-->
                    <thead>
                    <tr>
                        <th width="145px">收货人</th>
                        <th width="350px">收货地址</th>
                        <th width="100px">邮编</th>
                        <th width="169px">手机/电话</th>
                        <th width="240px">操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_oper err" id="addrs_info">

                    <tr class="addrinfolist">
                        <td class="bd-4">王先生</td>
                        <td class="bd-4">吉林省长春市高新技术开发区前进大街1111号</td>
                        <td class="bd-4"></td>
                        <td class="bd-4">185****1234<br></td>
                        <td class="bd-4 tl" id="operator" i="0">

                            <div class="fl wid-82">
                                <a class="pdr-5 modify color-2" style="margin-left: 20px;">修改</a><span
                                        class="color-2">|</span><a class="pdl-5 delete color-2">删除</a>
                            </div>


                            <div class="fl pdl-12">
                                <img src="${IMAGE_SERVER}cloud/static/user_location/images/icon-20.png"
                                     style="margin-top:5px">
                                <span class="" style="width:82px;*width:80px;">默认地址</span>
                                <a class="color-2 oper-link default_span2" style="visibility: hidden;">设为一键购</a>
                            </div>

                        </td>
                    </tr>


                    </tbody>
                </table>
            </div>
        </div>
        <div class="ued-main" id="stc_warm_tip"></div>
    </div>
    <div class="ued-footer mgt-10" id="stc_tail">
        <div class="footer">
            <div class="footcon"><p class="stc-footp"><a href="http://www.10086.cn/aboutus/news/">新闻中心</a><span>&nbsp;|&nbsp;</span><a
                            href="http://job.10086.cn/">诚聘英才</a><span>&nbsp;|&nbsp;</span><a
                            href="http://b2b.10086.cn/">采购信息</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/aboutus/hezuo/">企业合作</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/contact/">联系我们</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/navigation/">站点导航</a><span>&nbsp;|&nbsp;</span><a
                            href="http://labs.chinamobile.com/" target="_blank">中国移动研究院</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.cmdi.chinamobile.com/"
                            target="_blank">中国移动设计院</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.bj.10086.cn/sitemap">网站地图</a><span>&nbsp;|&nbsp;</span><a
                            href="http://www.10086.cn/web_notice/links/">友情链接</a></p>
                <p class="stc-footp"><span>&nbsp;</span><span>掌上营业厅：</span><a
                            href="http://wap.10086.cn/">wap.10086.cn</a><span>&nbsp;语音自助服务：10086  短信营业厅：10086&nbsp;</span><a
                            href="http://www.10086.cn/support/channel/self_service/">自助终端</a><span>&nbsp;</span><a
                            href="http://www.10086.cn/support/channel/Entity1/">营业厅</a><span>&nbsp;</span><a
                            href="http://www.10086.cn/cmccclient/index.htm">手机营业厅下载</a></p>
                <p class="xuke">Copyright©1999-2020&nbsp;&nbsp;中国移动&nbsp;&nbsp;版权所有</p>
                <p class="xuke"><span>中华人民共和国增值电信业务经营许可证&nbsp;&nbsp;经营许可证编号：A2.B1.B2-20100001</span></p></div>
            <div class="footgov">
                <div id="KXWZ" class="kxyz"><span><a id="urlknet"
                                                     href="https://ss.knet.cn/verifyseal.dll?sn=e130905110100423008ilb000000&pa=500267"
                                                     target="_blank"><img
                                    alt="&#x53EF;&#x4FE1;&#x7F51;&#x7AD9;" name="KNET_seal"
                                    src="${IMAGE_SERVER}cloud/static/user_location/images/knetSealLogo.png"
                                    width="128" height="47" onclick="KNET_change(&#39;urlknet&#39;)"></a></span></div>
                <div class="govtxt"><p class="gov"><a href="http://www.miibeian.gov.cn/">京ICP备05002571号</a></p></div>
            </div>
        </div>
    </div>
    <div class="suspension_act canfloat" style="display: none; width: auto; right: 10px;" id="div_easy_entry">
        <!--快捷入口列表-->
        <div id="easyentry" class="suspension_con" style="width: 70px;float:right;">
            <div>
                <div class="stc-easy-entry-item stc-common-inline stc-easy-entry-itemsty-shoppingcar" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-item-shoppingcar" flag="inner"
                         ahref="javascript:void(0);">
                        <strong id="sideShoppingcarCount" class="shoppingcar-count">0</strong>
                    </div>
                    <div class="shopping-trolley-list side-shopping-list" id="sideShoppingTrolley">
                        <div class="side-shoplist-box">
                            <img style="margin: 5px auto;;width: 40px;height: 40px;"
                                 src="${IMAGE_SERVER}cloud/static/user_location/images/loading.gif">
                        </div>
                        <div class="blank-block"></div>
                    </div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-2 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/101_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-4 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/134_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-6 stc-easy-entry-other" flag="out"
                         ahref="http://shop.10086.cn/list/128_431_431_0_0_0_0.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-8 stc-easy-entry-other" flag="out"
                         ahref="https://shop.10086.cn/i/"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-10 stc-easy-entry-other" flag="inner"
                         ahref="http://shop.10086.cn/mall_431_431.html"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-14 stc-easy-entry-other" flag="out"
                         ahref="https://shop.10086.cn/ac/livechat-web-client/robertIndex?&channelType=1021&code=BS&tenantId=1000072"
                         id="order-online"></div>
                </div>

                <div class="stc-easy-entry-item stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-12 stc-easy-entry-other" flag="inner"
                         ahref="javascript:scroll(0,0)"></div>
                </div>
                <div class="stc-common-inline" hit="false">
                    <div class="stc-easy-entry-item-ico stc-easy-entry-itemsty-love stc-easy-entry-other" flag="inner"
                         ahref="rechargelove"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="star-entry none" id="star_517_entry">
        <img src="${IMAGE_SERVER}cloud/static/user_location/images/img-517-star.png" width="80" height="80">
    </div>
</div>
<!-- #include virtual="/i/apps/pageapps/pfooter/index.html" -->
<!-- 弹框 遮罩层 -->
<div id="thick_bj"></div>
<!-- 新增弹框 -->
<div class="thick-content w500-t25" style="margin-left: -250px; margin-top: -85.5px;">
    <div class="thick-tit">
        <a class="fr mgt-15 mgr-15 js_x_close" href="javascript:void(0)"><img id="stc-change-img"
                                                                              src="https://shop.10086.cn/i/?f=home&welcome=1598407969731"></a>
        修改头像
    </div>
    <div class="mgt-30" style="width:420px;margin:0 auto;">
        <p class="fs-18 color-11">推荐头像</p>
        <ul class="ued-list2 js_head_por" id="images-ul">

        </ul>
    </div>

    <div class="tc mgt-20 mgb-20">
        <button class="ued-btn8" id="save-image">保存头像</button>
    </div>
</div>
<script type="text/javascript">
    var _Constant = Namespace('all.constant');
    //var SHOPONLINE = true;//是否展示联系客服的按钮

    //将获取用户信息的替换掉。 @2016-06-26
    var getInfoSucc = function (data, app, stcDic) {
        $('#stc_shop_link').attr('href', stcDic.getShopLink());
        $('#stc_first_loc').attr('href', stcDic.getLoginaddr());
        //统一处理温馨提示及面包屑的问题，通过aop切面的形式
        require(["jqaop"], function (jqaop) {
            jqaop.aop.after({target: app, method: 'initpage'}, function (invocation) {
                var arg = this.initpage.arguments[0];
                //by zhongbin 2017/9/25 设置f码
                $('#mainContain').attr('data-f', arg);
                require(["/i/apps/pageapps/pwarm/stcSpecialPart_ba7ece1.js", "/i/service/model/componet_set_42306f9.js"], function (sspart, comSet) {
                    var item = arg;
                    //首次登录生活交费界面重置标识20170808 start
                    if (item == 'rechargelife') {
                        _Constant.FIRSTLOGINLIFEPAGE = true;
                    }
                    //end
                    if (comSet.isMenuItem(item)) {//判断是否属于菜单里边的内容
                        //修改点击后一级菜单不展开，同时二级菜单无选中颜色的问题 @2016-06-21
                        $(".list-c1-son>li>a").each(function (e, e1) {
                            $(e1).removeClass('color-2');
                            if ($(e1).attr('alis') == item) {
                                //$(e1).parent().parent().parent().addClass('js_list_active');
                                $(e1).addClass('color-2');
                                if (!$(e1).parent().parent().parent().children().eq(0).hasClass('li-active')) {
                                    $(e1).parent().parent().parent().children().eq(0).trigger('click');
                                }

                            }
                        });
                        var _obj = comSet.getObjectByName(item, 0);
                        _Constant.CURRFUNC = item;
                        _Constant.RCURRFUNCODE = (typeof _obj != "undefined" && _obj != null) ? _obj.funcode : null;
                        //修改面包屑去菜单的名称 @2016-04-16
                        var obj = comSet.getObjectByName(item, 0);
                        if (_Constant.CURRENTMENUS != '' && typeof _Constant.CURRENTMENUS != 'undefined') {
                            for (var i = 0; i < _Constant.CURRENTMENUS.menu.length; i++) {
                                if (typeof _Constant.CURRENTMENUS.menu[i].child != 'undefined') {
                                    for (var j = 0; j < _Constant.CURRENTMENUS.menu[i].child.length; j++) {
                                        if (item == _Constant.CURRENTMENUS.menu[i].child[j].inx) {
                                            obj = _Constant.CURRENTMENUS.menu[i].child[j];
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                        _Constant.CURRFUNCODE = obj.funcode;
                        sspart.getCrumbPart(item, obj);
                        if (obj.funcode != '042000') {//当宽带充值时不调用公共的温馨提示
                            sspart.getWarmTipPart(app.data[0].mobile, '', obj.funcode);
                        }
                        //运营位设置   @lujx 2017-09-04
                        var paras = {
                            'areaID': obj.funcode,
                            'provCode': '100',
                            'channel': '00',
                            mobile: app.data[0].mobile
                        };
                        sspart.getOperationInfo(paras, obj);
                    }
                });
            });
        });
        //modified by zhouhong 20161128 判断如果是积分支付结果页则切换帐号到充值的手机号 start
        //app.initpage('stcMenu',{mobile:data.loginValue,data:data});   //引入左侧菜单区域，增加菜单选中的效果
        var uri = require('uri');
        var pid = new uri(location.href).getQueryParamValue("f");
        var _p = new uri(location.href).getQueryParamValue("p");
        if (pid == "rechargejf" && _p == "1" && data.userType == "1") {
            var req_data = {};
            //处理url参数,将url中的所有参数都原数传递给接口
            if (__params.length > 0) {//__params在constant.js中
                for (var k in __params) {
                    req_data[__params[k][0]] = __params[k][1];
                }
            }
            require(["/i/service/model/recharge_4d3f3eb.js"], function (recharge) {
                recharge.getPayCallBack(req_data, function (pay_data) {
                    app.initpage('stcMenu', {mobile: pay_data.mobile, data: data});   //引入左侧菜单区域，增加菜单选中的效果
                }, function (code, msg) {
                    //own.showSelectMobile(userInfo);
                    app.initpage('stcMenu', {mobile: data.loginValue, data: data});
                }, function (status, msg) {
                    //own.showSelectMobile(userInfo);
                    app.initpage('stcMenu', {mobile: data.loginValue, data: data});
                });
            });
        } else {
            app.initpage('stcMenu', {mobile: data.loginValue, data: data});   //引入左侧菜单区域，增加菜单选中的效果
        }
        //modified by zhouhong 20161128 如果是积分支付结果页则切换帐号到充值的手机号 end
        if (typeof pid == 'undefined' || pid == '' || pid == 'home') {
            pid = 'home';
            $('#stc_first_loc').hide();
            $('#stc_first_arrow').hide();
            $('#stc_second_loc').html('个人中心');
            app.initpage(pid);
        }
        //插码调用
        stcEcode.startGlobalTrack(data);//插码,基本码
        require(["/i/apps/pageapps/pheader/js/head_456f66f.js", "/i/apps/pageapps/pheader/js/tail_65e0761.js", "/i/apps/pageapps/pheader/tpl/easyentry_b448db8.js"], function (head, tail, easy) {
            head.initHead(tail, easy, data);

//			add by fenghy@20161220   start
//			判断用户是否登录
            require(["appmanage", "/i/apps/serviceapps/shoppingcar/js/shoppingcar_d1d0a09.js", "cookie"], function (app, shoppingcar) {
                $.cookie('inx', 'myorders', {secure: true});
                $.cookie('inx2', 'returnorderqry', {secure: true});
                var req = {};
                if (app.data[0].data.userType == "2") {//未登录,获取购物车个数即可
                    shoppingcar.getShoppingCartNumber();
                } else {
                    req.userId = app.data[0].data.loginValue;
                    req.userType = app.data[0].data.userType;
                    req.tempKey = $.cookie('cart_code_key');
                    shoppingcar.mergeShoppingCarGoods(req);//已经登录,那么先合并购物车,再去调用购物车个数接口
                }
                shoppingcar.init();//购物车初始函数,主要是为dom元素绑定事件
            });
//			---------------end
        });
    };

    $(function () {
        require(["appmanage", "stcDic", "stcutil"], function (app, stcDic, stcutil) {
            var objurl = window.location.protocol + "//search.10086.cn/log_collecter/logCollecter.js";
            // stcutil.loadScript(objurl);
            //特殊节日添加背景的代码逻辑  @2016-06-27
            if (stcDic.duanWu() == '0') {
                $('body').addClass('bg-body');
                $('#stc_head').removeClass('ued-header-bg');
                //隐藏搜索框原有样式
                $(".searchbar-hf").addClass("searchbar2");
                $(".span-hf").addClass("input-group-btn1");
                $(".btn-hf").addClass("btn1");
                //因中秋皮肤与字体冲突，改动字体颜色，只中秋时生效
                $("#dropdownMenu3").addClass("temfestival");
                $("#dropdownMenu4").addClass("temfestival");
                $("#stc_anchor").addClass("temfestival");
            }
            require(["commonutil", "uri"], function (ajaxUtil, uri) {
                ajaxUtil.GET('/v1/auth/loginfo', {}, function (data) {
                    if (data.userType == '25' || data.userType == '26') {//25,26为接口返回的注册帐号绑定状态，一个为绑定了，一个为未绑定
                        data.userType = 1;
                        data.provice = '000'; //注册帐号的省份编码为000
                    } else if (parseInt(data.userType) == 4) {//手机号码,接口返回4,
                        data.userType = 0;
                    } else if (parseInt(data.userType) == 3) {//异网账号,接口返回3,//如果异网账号接入后需要修改类型的判断 @lujx 2019-03-15
                        data.userType = 1;
                        data.provice = '998'; //异网账号的省份编码为998
                    } else {
                        data.provice = '999'; //未登录的省份编码为999
                    }
                    var encryptToken = 'yxfmxifprj';
                    if (!$.isEmptyObject(data.encryptToken)) {
                        encryptToken = data.encryptToken;
                    }
                    sessionStorage.setItem('encryptToken', encryptToken);
                    getInfoSucc(data, app, stcDic);
                    $("#specProvince").on('click', function () {
                        window.location.href = "https://www.he.10086.cn/service/basicBusi/openAndClosePhone!init.action";
                    });
                }, function () {
                    sessionStorage.setItem('encryptToken', 'yxfmxifprj');
                    var posi = new uri(location.href).getQueryParamValue("f");
                    if (posi != null) {
                        if (stcutil.inArray(posi, stcDic.getNologinFun())) {
                            getInfoSucc(stcDic.getDefaultUserInfo(), app, stcDic);
                        } else {
                            /*$('#mainContent').empty();
                            $('#mainContent').addClass('bg-f1');
                            var temp = document.createElement('div');
                            $(temp).addClass('bg-main-err width-100 h-380');
                            $('#mainContent').append(temp);*/
                            app.initpage('stcMenu', {
                                mobile: stcDic.getDefaultUserInfo().loginValue,
                                data: stcDic.getDefaultUserInfo()
                            });
                            app.initpage("stcError");
                        }
                    } else {
                        app.initpage('stcMenu', {
                            mobile: stcDic.getDefaultUserInfo().loginValue,
                            data: stcDic.getDefaultUserInfo()
                        });
                        app.initpage("stcError");
                    }
                }, function () {
                    sessionStorage.setItem('encryptToken', 'yxfmxifprj');
                    var posi = new uri(location.href).getQueryParamValue("f");
                    var item = {"funCode": "999001", "operDesc": posi};//代表走进error的打点 @2016-09-22
                    var stcLog = require('stclog');
                    stcLog.info(null, item);
                    if (posi != null) {
                        if (stcutil.inArray(posi, stcDic.getNologinFun())) {
                            getInfoSucc(stcDic.getDefaultUserInfo(), app, stcDic);
                        } else {
                            app.initpage('stcMenu', {
                                mobile: stcDic.getDefaultUserInfo().loginValue,
                                data: stcDic.getDefaultUserInfo()
                            });
                            app.initpage("stcError");
                        }
                    } else {
                        app.initpage('stcMenu', {
                            mobile: stcDic.getDefaultUserInfo().loginValue,
                            data: stcDic.getDefaultUserInfo()
                        });
                        app.initpage("stcError");
                    }
                });
            });
            //打点日志
            require(["stclog"], function (stclog) {
                stclog.init();
            })
        })
    });
    var sus = $("div.suspension_act");
    var suspension_clo = $("div.suspension_clo");
    if (screen.width > 1024) {
        sus.css('right', '10px');
    } else {
        sus.css('right', '10px');
    }
    $(window).scroll(function () {//当页面滚动条变化时，执行的函数
//		var scrollTop = $(window).scrollTop(0);//禁止浏览器滚屏:浏览器窗口相对滚动条顶部的偏移为0
        var scrollTop = $(window).scrollTop();//当前滚动条滚动的距离
        if (scrollTop == 0) {
            sus.hide();//当滚动条置顶时，隐藏浮动菜单
        } else {
            sus.show();//当滚动条滚动时，显示浮动菜单
            sus.addClass("canfloat");//浮动菜单绝对定位于浏览器左侧正中
        }
    });


</script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/sub_1bc8e4c.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/sdc_mall_346a383.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/jquery.eraser.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/tripledes_c4dce8b.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/mode-ecb_851d991.js"></script>
<script type="text/javascript" charset="utf-8"
        src="${IMAGE_SERVER}cloud/static/user_location/js/aes_29b7e6b.js"></script>
<!--[if lte IE 9]>
<script src="/i/service/model/excanvas_c0cad58.js"></script>
<![endif]-->


<div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
    <div class="xl-chrome-ext-bar__logo"></div>

    <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
    <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
</div>
</body>
</html>